export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --ansi \
  --info=inline-right \
  --layout=reverse \
  --border=none \
  --color=bg+:#2c2e3a \
  --color=bg:#1b1d25 \
  --color=border:#3cb05c \
  --color=fg:#c7c7b3 \
  --color=gutter:#1b1d25 \
  --color=header:#de9f5c \
  --color=hl+:#d84040 \
  --color=hl:#d84040 \
  --color=info:#737a94 \
  --color=marker:#d74a9b \
  --color=pointer:#d74a9b \
  --color=prompt:#58d879 \
  --color=query:#c7c7b3:regular \
  --color=scrollbar:#3cb05c \
  --color=separator:#de9f5c \
  --color=spinner:#d74a9b \
  --highlight-line
"