export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --ansi \
  --info=inline-right \
  --layout=reverse \
  --border=none \
  --color=bg+:#e9e9e9 \
  --color=bg:#dadada \
  --color=border:#6f9a6b \
  --color=fg:#5e8888 \
  --color=gutter:#dadada \
  --color=header:#aa724e \
  --color=hl+:#b54c69 \
  --color=hl:#b54c69 \
  --color=info:#777984 \
  --color=marker:#934b7f \
  --color=pointer:#934b7f \
  --color=prompt:#557f51 \
  --color=query:#5e8888:regular \
  --color=scrollbar:#6f9a6b \
  --color=separator:#aa724e \
  --color=spinner:#934b7f \
  --highlight-line
"