-- Theme: lvim
-- Author: lvim-org
-- License: BSD 3-Clause License
-- Source: https://github.com/lvim-org/lvim-colorscheme
local lvim = {
    bg_01 = "#242B30",
    bg_02 = "#272F35",
    bg_03 = "#2A3339",
    fg = "#81a386",
    color_0 = "#56adb7",
    color_1 = "#158FA7",
    color_2 = "#90c1a3",
    color_3 = "#FF7A66",
    color_4 = "#1C9898",
    color_5 = "#A7C080",
    color_6 = "#628b97",
    color_7 = "#ff5c57",
    color_8 = "#E6C068",
    color_9 = "#F2AF5C",
    color_10 = "#F2994B",
    color_11 = "#43ACAB",
    color_12 = "#8fbcbb",
    color_13 = "#F05F4E",
    color_14 = "#458588",
    term_0 = "#2E3440",
    term_8 = "#FF7A66",
    term_1 = "#F05F4E",
    term_9 = "#F05F4E",
    term_2 = "#A7C080",
    term_10 = "#A7C080",
    term_3 = "#1F8C8C",
    term_11 = "#1F8C8C",
    term_4 = "#2AA198",
    term_12 = "#2AA198",
    term_5 = "#83a598",
    term_13 = "#83a598",
    term_6 = "#F2994B",
    term_14 = "#F2994B",
    term_7 = "#00839F",
    term_15 = "#00839F",
    color_error = "#F05F4E",
    color_warning = "#F2994B",
    color_success = "#A7C080",
    color_info = "#E6C068",
    color_hint = "#00839F",
    color_add = "#90c1a3",
    color_delete = "#F05F4E",
    color_change = "#E6C068",
    color_change_delete = "#F2994B",
    hl_01 = "#46555A",
    hl_02 = "#3A464A",
    hl_03 = "#2d3639",
    none = "NONE",
}

function lvim.terminal_color()
    vim.g.terminal_color_0 = lvim.term_0
    vim.g.terminal_color_1 = lvim.term_1
    vim.g.terminal_color_2 = lvim.term_2
    vim.g.terminal_color_3 = lvim.term_3
    vim.g.terminal_color_4 = lvim.term_4
    vim.g.terminal_color_5 = lvim.term_5
    vim.g.terminal_color_6 = lvim.term_6
    vim.g.terminal_color_7 = lvim.term_7
    vim.g.terminal_color_8 = lvim.term_8
    vim.g.terminal_color_9 = lvim.term_9
    vim.g.terminal_color_10 = lvim.term_10
    vim.g.terminal_color_11 = lvim.term_11
    vim.g.terminal_color_12 = lvim.term_12
    vim.g.terminal_color_13 = lvim.term_13
    vim.g.terminal_color_14 = lvim.term_14
    vim.g.terminal_color_15 = lvim.term_15
end

function lvim.highlight(group, color)
    local style = color.style and "gui=" .. color.style or "gui=NONE"
    local fg = color.fg and "guifg=" .. color.fg or "guifg=NONE"
    local bg = color.bg and "guibg=" .. color.bg or "guibg=NONE"
    local sp = color.sp and "guisp=" .. color.sp or ""
    vim.api.nvim_command("highlight " .. group .. " " .. style .. " " .. fg .. " " .. bg .. " " .. sp)
end

function lvim.load_syntax()
    local syntax = {
        Normal = { fg = lvim.fg, bg = lvim.bg_03 },
        Terminal = { fg = lvim.fg, bg = lvim.bg_03 },
        SignColumn = { fg = lvim.fg, bg = lvim.none },
        FoldColumn = { fg = lvim.color_10, bg = lvim.none },
        VertSplit = { fg = lvim.bg_01, bg = lvim.bg_01 },
        Folded = { fg = lvim.fg, bg = lvim.hl_02 },
        EndOfBuffer = { fg = lvim.bg_02, bg = lvim.none },
        IncSearch = { fg = lvim.bg_01, bg = lvim.color_10 },
        Search = { fg = lvim.bg_01, bg = lvim.color_10 },
        ColorColumn = { fg = lvim.none, bg = lvim.bg_01 },
        Conceal = { fg = lvim.color_12, bg = lvim.none },
        Cursor = { fg = lvim.none, bg = lvim.none, style = "reverse" },
        vCursor = { fg = lvim.none, bg = lvim.none, style = "reverse" },
        iCursor = { fg = lvim.none, bg = lvim.none, style = "reverse" },
        lCursor = { fg = lvim.none, bg = lvim.none, style = "reverse" },
        CursorIM = { fg = lvim.none, bg = lvim.none, style = "reverse" },
        CursorColumn = { fg = lvim.none, bg = lvim.bg_02 },
        CursorLine = { fg = lvim.none, bg = lvim.bg_02 },
        LineNr = { fg = lvim.hl_01, bg = lvim.none },
        qfLineNr = { fg = lvim.color_5, bg = lvim.none },
        CursorLineNr = { fg = lvim.color_5, bg = lvim.none },
        DiffAdd = { fg = lvim.bg_02, bg = lvim.color_6 },
        DiffChange = { fg = lvim.bg_02, bg = lvim.color_3 },
        DiffDelete = { fg = lvim.bg_02, bg = lvim.color_0 },
        DiffText = { fg = lvim.bg_02, bg = lvim.fg },
        Directory = { fg = lvim.color_8, bg = lvim.none },
        ErrorMsg = { fg = lvim.color_error, bg = lvim.none },
        WarningMsg = { fg = lvim.color_warning, bg = lvim.none },
        ModeMsg = { fg = lvim.color_6, bg = lvim.none },
        FocusedSymbol = { fg = lvim.color_5 },
        MatchParen = { fg = lvim.color_0, bg = lvim.none },
        NonText = { fg = lvim.fg },
        Whitespace = { fg = lvim.bg_02 },
        SpecialKey = { fg = lvim.fg },
        Pmenu = { fg = lvim.color_10, bg = lvim.bg_01 },
        PmenuSel = { fg = lvim.bg_03, bg = lvim.color_10 },
        PmenuSelBold = { fg = lvim.bg_03, bg = lvim.color_10 },
        PmenuSbar = { fg = lvim.none, bg = lvim.bg_01 },
        PmenuThumb = { fg = lvim.color_9, bg = lvim.color_4 },
        WildMenu = { fg = lvim.color_10, bg = lvim.color_5 },
        Question = { fg = lvim.color_3 },
        Tabline = { fg = lvim.color_10, bg = lvim.none },
        TabLineFill = { style = lvim.none },
        TabLineSel = { fg = lvim.fg, bg = lvim.none },
        StatusLine = { fg = lvim.color_10, bg = lvim.bg_01, style = "bold" },
        StatusLineNC = { fg = lvim.color_10, bg = lvim.bg_01, style = "bold" },
        SpellBad = { fg = lvim.bg_02, bg = lvim.color_7 },
        SpellCap = { fg = lvim.bg_02, bg = lvim.color_7 },
        SpellLocal = { fg = lvim.bg_02, bg = lvim.color_7 },
        SpellRare = { fg = lvim.bg_02, bg = lvim.color_7 },
        Visual = { fg = lvim.bg_01, bg = lvim.color_10 },
        VisualNOS = { fg = lvim.bg_01, bg = lvim.color_10 },
        QuickFixLine = { fg = lvim.color_9 },
        Debug = { fg = lvim.color_2 },
        debugBreakpoint = { fg = lvim.bg_03, bg = lvim.color_0 },
        Boolean = { fg = lvim.color_2 },
        Number = { fg = lvim.color_13 },
        Float = { fg = lvim.fg, bg = lvim.bg_01 },
        NormalFloat = { fg = lvim.fg, bg = lvim.bg_01 },
        FloatBorder = { fg = lvim.bg_01, bg = lvim.bg_01 },
        PreProc = { fg = lvim.color_9 },
        PreCondit = { fg = lvim.color_9 },
        Include = { fg = lvim.color_9 },
        Define = { fg = lvim.color_3 },
        Conditional = { fg = lvim.color_5 },
        Repeat = { fg = lvim.color_10 },
        Keyword = { fg = lvim.color_2 },
        Typedef = { fg = lvim.color_0 },
        Exception = { fg = lvim.color_0 },
        Statement = { fg = lvim.color_0 },
        Error = { fg = lvim.color_error },
        StorageClass = { fg = lvim.color_2 },
        Tag = { fg = lvim.color_8 },
        Label = { fg = lvim.color_2 },
        Structure = { fg = lvim.color_2 },
        Operator = { fg = lvim.color_5 },
        Title = { fg = lvim.color_2 },
        Special = { fg = lvim.fg },
        SpecialChar = { fg = lvim.fg },
        Type = { fg = lvim.color_11 },
        Function = { fg = lvim.color_3 },
        String = { fg = lvim.color_4 },
        Character = { fg = lvim.color_5 },
        Constant = { fg = lvim.color_7 },
        Macro = { fg = lvim.color_7 },
        Identifier = { fg = lvim.color_8 },
        Comment = { fg = lvim.color_6 },
        SpecialComment = { fg = lvim.color_6 },
        Todo = { fg = lvim.color_6 },
        Delimiter = { fg = lvim.color_5 },
        Ignore = { fg = lvim.color_12 },
        Underlined = { style = "underline" },
        Bold = { style = "bold" },
        Italic = { style = "italic" },
        DiagnosticError = { fg = lvim.color_error, bg = lvim.none },
        DiagnosticWarn = { fg = lvim.color_warning, bg = lvim.none },
        DiagnosticInfo = { fg = lvim.color_info, bg = lvim.none },
        DiagnosticHint = { fg = lvim.color_hint, bg = lvim.none },
        UIPrompt = { fg = lvim.fg, bg = lvim.hl_02 },
        UIPromptSelect = { fg = lvim.fg, bg = lvim.hl_02, style = "bold" },
        WinBar = { bg = lvim.bg_01, fg = lvim.color_10 },
        LightBulb = { fg = lvim.color_10, bg = lvim.none },
        LightBulbVirtualText = { fg = lvim.color_10, bg = lvim.none },
        CodeBlock = { bg = lvim.hl_03 },
        OrgTSHeadlineLevel1 = { fg = lvim.term_7, style = "bold" },
        OrgTSHeadlineLevel2 = { fg = lvim.term_4, style = "bold" },
        OrgTSHeadlineLevel3 = { fg = lvim.color_5, style = "bold" },
        OrgTSHeadlineLevel4 = { fg = lvim.color_8, style = "bold" },
        OrgTSHeadlineLevel5 = { fg = lvim.color_10, style = "bold" },
        OrgTSHeadlineLevel6 = { fg = lvim.color_13, style = "bold" },
        OrgTSHeadlineLevel7 = { fg = lvim.term_3, style = "bold" },
        OrgTSHeadlineLevel8 = { fg = lvim.color_3, style = "bold" },
        OrgHeadlineLevel1 = { fg = lvim.term_7, style = "bold" },
        OrgHeadlineLevel2 = { fg = lvim.term_4, style = "bold" },
        OrgHeadlineLevel3 = { fg = lvim.color_5, style = "bold" },
        OrgHeadlineLevel4 = { fg = lvim.color_8, style = "bold" },
        OrgHeadlineLevel5 = { fg = lvim.color_10, style = "bold" },
        OrgHeadlineLevel6 = { fg = lvim.color_13, style = "bold" },
        OrgHeadlineLevel7 = { fg = lvim.term_3, style = "bold" },
        OrgHeadlineLevel8 = { fg = lvim.color_3, style = "bold" },
        OrgDone = { fg = lvim.color_5, style = "bold" },
        OrgHalf = { fg = lvim.color_8, style = "bold" },
        OrgUnDone = { fg = lvim.color_13, style = "bold" },
    }
    return syntax
end

function lvim.load_plugin_syntax()
    local plugin_syntax = {
        TSAnnotation = { fg = lvim.color_0 },
        TSAttribute = { fg = lvim.color_1 },
        TSBoolean = { fg = lvim.color_2 },
        TSCharacter = { fg = lvim.color_5 },
        TSConditional = { fg = lvim.color_4 },
        TSConstant = { fg = lvim.color_5 },
        TSEmphasis = { fg = lvim.color_3 },
        TSError = { fg = lvim.color_7 },
        TSException = { fg = lvim.color_1 },
        TSField = { fg = lvim.color_4 },
        TSFloat = { fg = lvim.color_10 },
        TSFuncBuiltin = { fg = lvim.color_3 },
        TSFuncMacro = { fg = lvim.color_12 },
        TSKeywordFunction = { fg = lvim.color_7 },
        TSLiteral = { fg = lvim.color_10 },
        TSNamespace = { fg = lvim.color_5 },
        TSNumber = { fg = lvim.color_1 },
        TSParameterReference = { fg = lvim.color_2 },
        TSPunctSpecial = { fg = lvim.color_3 },
        TSRepeat = { fg = lvim.color_4 },
        TSString = { fg = lvim.color_5 },
        TSStringEscape = { fg = lvim.color_6 },
        TSStringRegex = { fg = lvim.color_7 },
        TSStrong = { fg = lvim.color_1 },
        TSStructure = { fg = lvim.color_9 },
        TSText = { fg = lvim.color_10 },
        TSTitle = { fg = lvim.color_11 },
        TSTypeBuiltin = { fg = lvim.color_3 },
        TSUnderline = { fg = lvim.color_13 },
        TSURI = { fg = lvim.color_10, style = "italic" },
        TSInclude = { fg = lvim.color_0 },
        TSPunctBracket = { fg = lvim.color_2 },
        TSPunctDelimiter = { fg = lvim.color_2 },
        TSType = { fg = lvim.color_11 },
        TSFunction = { fg = lvim.color_2 },
        TSTagDelimiter = { fg = lvim.color_6 },
        TSProperty = { fg = lvim.color_7 },
        TSMethod = { fg = lvim.color_1 },
        TSParameter = { fg = lvim.color_9 },
        TSConstructor = { fg = lvim.color_3 },
        TSVariable = { fg = lvim.color_9 },
        TSOperator = { fg = lvim.color_7 },
        TSKeyword = { fg = lvim.color_5 },
        TSVariableBuiltin = { fg = lvim.color_10 },
        TSTag = { fg = lvim.color_3 },
        TSLabel = { fg = lvim.color_1 },
        DashboardShortCut = { fg = lvim.color_10 },
        DashboardHeader = { fg = lvim.color_0 },
        DashboardCenter = { fg = lvim.color_7 },
        DashboardFooter = { fg = lvim.color_5 },
        vimCommentTitle = { fg = lvim.color_12 },
        vimLet = { fg = lvim.color_2 },
        vimVar = { fg = lvim.color_7 },
        vimFunction = { fg = lvim.color_1 },
        vimIsCommand = { fg = lvim.fg },
        vimCommand = { fg = lvim.color_8 },
        vimNotFunc = { fg = lvim.color_9 },
        vimUserFunc = { fg = lvim.color_5 },
        vimFuncName = { fg = lvim.color_3 },
        diffAdded = { fg = lvim.color_add },
        diffRemoved = { fg = lvim.color_delete },
        diffChanged = { fg = lvim.color_change },
        diffOldFile = { fg = lvim.color_3 },
        diffNewFile = { fg = lvim.color_2 },
        diffFile = { fg = lvim.color_7 },
        diffLine = { fg = lvim.color_12 },
        diffIndexLine = { fg = lvim.color_9 },
        gitcommitSummary = { fg = lvim.color_0 },
        gitcommitUntracked = { fg = lvim.color_12 },
        gitcommitDiscarded = { fg = lvim.color_12 },
        gitcommitSelected = { fg = lvim.color_12 },
        gitcommitUnmerged = { fg = lvim.color_12 },
        gitcommitOnBranch = { fg = lvim.color_12 },
        gitcommitArrow = { fg = lvim.color_12 },
        gitcommitFile = { fg = lvim.color_6 },
        NeogitBranch = { fg = lvim.color_6 },
        NeogitRemote = { fg = lvim.color_6 },
        NeogitHunkHeader = { fg = lvim.color_0, bg = lvim.bg_02 },
        NeogitHunkHeaderHighlight = { fg = lvim.color_0, bg = lvim.bg_02 },
        NeogitDiffContextHighlight = { fg = lvim.color_add, bg = lvim.bg_02 },
        NeogitDiffDeleteHighlight = { fg = lvim.color_delete, bg = lvim.bg_02 },
        NeogitDiffAddHighlight = { fg = lvim.color_add, bg = lvim.bg_02 },
        NeogitDiffAdd = { fg = lvim.color_add, bg = lvim.bg_02 },
        NeogitDiffDelete = { fg = lvim.color_delete, bg = lvim.bg_02 },
        VistaBracket = { fg = lvim.color_12 },
        VistaChildrenNr = { fg = lvim.color_8 },
        VistaKind = { fg = lvim.color_9 },
        VistaScope = { fg = lvim.color_0 },
        VistaScopeKind = { fg = lvim.color_8 },
        VistaTag = { fg = lvim.color_9 },
        VistaPrefix = { fg = lvim.color_12 },
        VistaColon = { fg = lvim.color_9 },
        VistaIcon = { fg = lvim.color_3 },
        VistaLineNr = { fg = lvim.fg },
        GitGutterAdd = { fg = lvim.color_add },
        GitGutterChange = { fg = lvim.color_change },
        GitGutterDelete = { fg = lvim.color_delete },
        GitGutterChangeDelete = { fg = lvim.color_change_delete },
        GitSignsAdd = { fg = lvim.color_add, bg = lvim.none },
        GitSignsChange = { fg = lvim.color_change, bg = lvim.none },
        GitSignsDelete = { fg = lvim.color_delete, bg = lvim.none },
        GitSignsAddNr = { fg = lvim.color_add, bg = lvim.none },
        GitSignsChangeNr = { fg = lvim.color_change, bg = lvim.none },
        GitSignsDeleteNr = { fg = lvim.color_delete, bg = lvim.none },
        GitSignsAddLn = { fg = lvim.color_add, bg = lvim.none },
        GitSignsChangeLn = { fg = lvim.color_change, bg = lvim.none },
        GitSignsDeleteLn = { fg = lvim.color_delete, bg = lvim.none },
        SignifySignAdd = { fg = lvim.color_add },
        SignifySignChange = { fg = lvim.color_change },
        SignifySignDelete = { fg = lvim.color_delete },
        dbui_tables = { fg = lvim.color_8 },
        DiagnosticVirtualTextError = { fg = lvim.color_error, bg = lvim.bg_03 },
        DiagnosticVirtualTextWarn = { fg = lvim.color_warning, bg = lvim.bg_03 },
        DiagnosticVirtualTextInfo = { fg = lvim.color_info, bg = lvim.bg_03 },
        DiagnosticVirtualTextHint = { fg = lvim.color_info, bg = lvim.bg_03 },
        SignatureAtiveParameter = { fg = lvim.color_info, bg = lvim.bg_03 },
        DiagnosticUnderlineError = {
            style = "undercurl",
            sp = lvim.color_error,
        },
        DiagnosticUnderlineWarn = {
            style = "undercurl",
            sp = lvim.color_warning,
        },
        DiagnosticUnderlineInfo = {
            style = "undercurl",
            sp = lvim.color_info,
        },
        DiagnosticUnderlineHint = {
            style = "undercurl",
            sp = lvim.color_info,
        },
        DiagnosticFloatingError = { fg = lvim.color_error },
        DiagnosticFloatingWarn = { fg = lvim.color_warning },
        DiagnosticFloatingInfo = { fg = lvim.color_info },
        DiagnosticFloatingHint = { fg = lvim.color_info },
        LvimFocusNormal = { bg = lvim.bg_01 },
        LvimHelperNormal = { fg = lvim.color_6, bg = lvim.bg_02 },
        LvimHelperTitle = { fg = lvim.color_9, bg = lvim.none },
        SnapNormal = { fg = lvim.color_6, bg = lvim.none },
        SnapBorder = { fg = lvim.color_1, bg = lvim.none },
        SnapSelect = { fg = lvim.bg_03, bg = lvim.color_9 },
        SnapMultiSelect = { fg = lvim.bg_03, bg = lvim.color_9 },
        SnapPrompt = { fg = lvim.color_9, bg = lvim.none },
        SnapPosition = { fg = lvim.color_9, bg = lvim.none },
        NvimTreeNormal = { bg = lvim.bg_01 },
        NvimTreeCursorLine = { bg = lvim.bg_03 },
        NvimTreeFolderName = { fg = lvim.color_5 },
        NvimTreeOpenedFolderName = { fg = lvim.color_5 },
        NvimTreeEmptyFolderName = { fg = lvim.color_5 },
        NvimTreeRootFolder = { fg = lvim.color_5 },
        NvimTreeSpecialFile = { fg = lvim.fg, bg = lvim.none, style = "NONE" },
        NvimTreeFolderIcon = { fg = lvim.color_5 },
        NvimTreeIndentMarker = { fg = lvim.hl_01 },
        NvimTreeSignError = { fg = lvim.color_error },
        NvimTreeSignWarning = { fg = lvim.color_warning },
        NvimTreeSignInformation = { fg = lvim.color_info },
        NvimTreeSignHint = { fg = lvim.color_info },
        NvimTreeLspDiagnosticsError = { fg = lvim.color_error },
        NvimTreeLspDiagnosticsWarning = { fg = lvim.color_warning },
        NvimTreeLspDiagnosticsInformation = { fg = lvim.color_info },
        NvimTreeLspDiagnosticsHint = { fg = lvim.color_info },
        NvimTreeWindowPicker = { gui = "bold", fg = lvim.bg_03, bg = lvim.color_9 },
        TroubleNormal = { bg = lvim.bg_01 },
        TroubleError = { bg = lvim.color_error },
        TroubleWarning = { bg = lvim.color_warning },
        TroubleInformation = { bg = lvim.color_info },
        TroubleTextError = { fg = lvim.color_error },
        TroubleTextWarning = { fg = lvim.color_warning },
        TroubleTextHint = { fg = lvim.color_info },
        TroubleTextInformation = { fg = lvim.color_0 },
        TroubleText = { fg = lvim.color_0 },
        TroubleCount = { fg = lvim.color_0 },
        TelescopeBorder = { bg = lvim.bg_01, fg = lvim.bg_01 },
        TelescopePromptBorder = { bg = lvim.hl_02, fg = lvim.hl_02 },
        TelescopePromptNormal = { bg = lvim.hl_02, fg = lvim.fg },
        TelescopePromptPrefix = { bg = lvim.hl_02, fg = lvim.color_3 },
        TelescopeNormal = { bg = lvim.bg_01, fg = lvim.fg },
        TelescopePreviewTitle = { bg = lvim.color_5, fg = lvim.bg_03 },
        TelescopePromptTitle = { bg = lvim.color_3, fg = lvim.bg_03 },
        TelescopeResultsTitle = { bg = lvim.bg_01, fg = lvim.bg_01 },
        TelescopeMatching = { bg = lvim.none, fg = lvim.color_3 },
        TelescopeSelection = { bg = lvim.hl_02, fg = lvim.color_3 },
        TelescopeSelectionCaret = { bg = lvim.bg_01, fg = lvim.color_3 },
        TelescopeMultiSelection = { bg = lvim.hl_02, fg = lvim.color_11 },
        LspInstallerHeader = { gui = "bold", fg = lvim.color_5 },
        LspInstallerGreen = { fg = lvim.color_5 },
        LspInstallerError = { fg = lvim.color_7 },
        LspInstallerOrange = { fg = lvim.color_9 },
        LspInstallerMuted = { fg = lvim.fg },
        LspInstallerHighlighted = { fg = lvim.color_12 },
        LspInstallerVersionCheckLoader = { gui = "bold", bg = lvim.bg_03, fg = lvim.fg },
        LspInstallerVersionCheckLoaderDone = { gui = "bold", bg = lvim.bg_03, fg = lvim.color_5 },
        LspInstallerVaderSaber = { fg = lvim.color_3 },
        LspReferenceRead = { bg = lvim.hl_01 },
        LspReferenceText = { bg = lvim.hl_01 },
        LspReferenceWrite = { bg = lvim.hl_01 },
        BufferCurrent = { fg = lvim.color_8 },
        BufferCurrentIndex = { fg = lvim.color_8 },
        BufferCurrentMod = { fg = lvim.color_8 },
        BufferCurrentSign = { fg = lvim.fg },
        BufferCurrentTarget = { fg = lvim.color_8 },
        BufferVisible = { fg = lvim.color_3 },
        BufferVisibleIndex = { fg = lvim.color_3 },
        BufferVisibleMod = { fg = lvim.color_3 },
        BufferVisibleSign = { fg = lvim.fg },
        BufferVisibleTarget = { fg = lvim.color_3 },
        BufferInactive = { fg = lvim.color_3 },
        BufferInactiveIndex = { fg = lvim.color_3 },
        BufferInactiveMod = { fg = lvim.color_3 },
        BufferInactiveSign = { fg = lvim.fg },
        BufferInactiveTarget = { fg = lvim.color_3 },
        BufferTabpages = { fg = lvim.none },
        BufferTabpageFill = { fg = lvim.none },
        BufferCurrentIcon = { fg = lvim.color_3 },
        BufferVisibleIcon = { fg = lvim.color_3 },
        BufferInactiveIcon = { fg = lvim.color_3 },
        IndentBlanklineChar = { fg = lvim.hl_02, bg = lvim.none },
        IndentBlanklineSpaceCharBlankline = { fg = lvim.color_1, bg = lvim.none },
        IndentBlanklineContextChar = { fg = lvim.color_1, bg = lvim.none },
        ClapDir = { fg = lvim.color_4, bg = lvim.bg_03 },
        ClapFile = { fg = lvim.color_4, bg = lvim.bg_03 },
        ClapCurrentSelection = { fg = lvim.color_8, bg = lvim.bg_03 },
        ClapCurrentSelectionSign = { fg = lvim.color_8, bg = lvim.bg_03 },
        ClapInput = { fg = lvim.fg, bg = lvim.bg_03 },
        ClapSpinner = { fg = lvim.fg, bg = lvim.bg_03 },
        ClapSearchText = { fg = lvim.color_4, bg = lvim.bg_03 },
        ClapPreview = { fg = lvim.fg, bg = lvim.bg_03 },
        ClapSelected = { fg = lvim.fg, bg = lvim.bg_03 },
        ClapSelectedSign = { fg = lvim.fg, bg = lvim.bg_03 },
        VimwikiHeader1 = { fg = lvim.color_10 },
        VimwikiHeader2 = { fg = lvim.color_8 },
        VimwikiHeader3 = { fg = lvim.color_5 },
        VimwikiHeader4 = { fg = lvim.color_4 },
        VimwikiHeader5 = { fg = lvim.color_7 },
        VimwikiHeader6 = { fg = lvim.color_0 },
        VimwikiLink = { fg = lvim.color_1 },
        VimwikiHeaderChar = { fg = lvim.color_2 },
        VimwikiHR = { fg = lvim.color_12 },
        VimwikiList = { fg = lvim.color_13 },
        VimwikiTag = { fg = lvim.color_5 },
        calendar = { bg = lvim.bg_01 },
        SniprunVirtualTextOk = { bg = lvim.color1, fg = lvim.color_success },
        SniprunFloatingWinOk = { bg = lvim.color1, fg = lvim.color_success },
        SniprunVirtualTextErr = { bg = lvim.color1, fg = lvim.color_error },
        SniprunFloatingWinErr = { bg = lvim.color1, fg = lvim.color_error },
        HopNextKey = { fg = lvim.color_7, style = "bold" },
        HopNextKey1 = { fg = lvim.color_8, style = "bold" },
        HopNextKey2 = { fg = lvim.color_10, style = "bold" },
        HopUnmatched = { fg = lvim.color_6, sp = lvim.color_6 },
        NotifyERRORBorder = { fg = lvim.color_error },
        NotifyWARNBorder = { fg = lvim.color_warning },
        NotifyINFOBorder = { fg = lvim.color_info },
        NotifyDEBUGBorder = { fg = lvim.color_hint },
        NotifyTRACEBorder = { fg = lvim.color_hint },
        NotifyERRORIcon = { fg = lvim.color_error },
        NotifyWARNIcon = { fg = lvim.color_warning },
        NotifyINFOIcon = { fg = lvim.color_info },
        NotifyDEBUGIcon = { fg = lvim.color_hint },
        NotifyTRACEIcon = { fg = lvim.color_hint },
        NotifyERRORTitle = { fg = lvim.color_error },
        NotifyWARNTitle = { fg = lvim.color_warning },
        NotifyINFOTitle = { fg = lvim.color_info },
        NotifyDEBUGTitle = { fg = lvim.color_hint },
        NotifyTRACETitle = { bg = lvim.color_hint },
        NotifyERRORBody = { bg = lvim.none },
        NotifyWARNBody = { bg = lvim.none },
        NotifyINFOBody = { bg = lvim.none },
        NotifyDEBUGBody = { bg = lvim.none },
        NotifyTRACEBody = { bg = lvim.none },
    }
    return plugin_syntax
end

local async_load_plugin

async_load_plugin = vim.loop.new_async(vim.schedule_wrap(function()
    lvim.terminal_color()
    local syntax = lvim.load_plugin_syntax()
    for group, colors in pairs(syntax) do
        lvim.highlight(group, colors)
    end
    async_load_plugin:close()
end))

function lvim.colorscheme()
    vim.api.nvim_command("hi clear")
    if vim.fn.exists("syntax_on") then
        vim.api.nvim_command("syntax reset")
    end
    vim.o.background = "dark"
    vim.o.termguicolors = true
    vim.g.colors_name = "lvim"
    local syntax = lvim.load_syntax()
    for group, colors in pairs(syntax) do
        lvim.highlight(group, colors)
    end
    async_load_plugin:send()
end

lvim.colorscheme()

return lvim
