-- lvim-colorscheme.extra.hyprland: generate the hyprland border colours.
--
--     ln -sf .../extras/hyprland/LvimNord_dark.conf ~/.config/hypr/colors.conf
--     # then in hyprland.conf: source = ~/.config/hypr/colors.conf
--
-- The two border colours and nothing else. hyprland's general { } block also
-- holds gaps, border_size and layout, which are the user's — so this file
-- carries the assignments alone and is sourced AFTER the block that would
-- otherwise define them: hyprland takes the last assignment it reads.
--
-- rgba(rrggbbaa), so the palette's # is dropped and full opacity appended.
--
---@module "lvim-colorscheme.extra.desktop.hyprland"

local M = {}

---@param hex string
---@return string
local function rgba(hex)
    return "rgba(" .. hex:gsub("^#", "") .. "ff)"
end

--- @param colors ColorScheme
--- @return string
function M.generate(colors)
    local lines = {
        "# " .. (colors._style_name or "Lvim") .. " — generated by lvim-colorscheme.",
        "# Sourced from hyprland.conf, after the general block it overrides.",
        "",
        "general {",
        "    col.active_border = " .. rgba(colors.yellow_dark),
        "    col.inactive_border = " .. rgba(colors.green_dark),
        "}",
        "",
    }
    return table.concat(lines, "\n")
end

return M
