-- lvim-colorscheme.extra.mango: generate the mango colour block from the palette.
--
--     ln -sf .../extras/mango/LvimNord_dark.conf ~/.config/mango/colors.conf
--     # then in config.conf: source=~/.config/mango/colors.conf
--
-- ONLY the eight colour options. mango's appearance.conf carries borderpx,
-- gaps and the rest of its layout; those are the user's and stay there, with a
-- source= line pulling this file in. A generated file that also carried layout
-- would overwrite a hand-tuned window gap on every theme switch.
--
-- mango takes no #rrggbb: its colours are 0xrrggbbaa, so the palette values are
-- stripped of their # and given a full-opacity alpha here.
--
-- The role mapping is baked in rather than configurable, because it is a
-- property of the palette rather than of the machine: three of the eight
-- matched a palette colour exactly (green, purple, red) and the other five were
-- hand-tuned against the 48 palettes. Changing one means regenerating, which is
-- the honest cost of the choice living with the colours it is chosen from.
--
---@module "lvim-colorscheme.extra.desktop.mango"

local M = {}

--- 0xrrggbbff from a #rrggbb palette value.
---@param hex string
---@return string
local function argb(hex)
    return "0x" .. hex:gsub("^#", "") .. "ff"
end

--- @param colors ColorScheme
--- @return string
function M.generate(colors)
    local lines = {
        "# " .. (colors._style_name or "Lvim") .. " — generated by lvim-colorscheme.",
        "# Sourced from config.conf; every other appearance option stays in appearance.conf.",
        "",
        "rootcolor=" .. argb(colors.bg_dark),
        "bordercolor=" .. argb(colors.green_dark),
        "focuscolor=" .. argb(colors.yellow_dark),
        "maximizescreencolor=" .. argb(colors.green),
        "urgentcolor=" .. argb(colors.red),
        "scratchpadcolor=" .. argb(colors.green),
        "globalcolor=" .. argb(colors.purple),
        "overlaycolor=" .. argb(colors.teal),
        "",
    }
    return table.concat(lines, "\n")
end

return M
