-- lvim-colorscheme.extra.niri: generate the niri border colours.
--
--     ln -sf .../extras/niri/LvimNord_dark.kdl ~/.config/niri/incl/99-colors.kdl
--     # then in config.kdl, LAST: include "./incl/99-colors.kdl"
--
-- niri keeps its colours nested — layout { focus-ring { … } border { … } } —
-- so this file repeats that nesting and carries the colour nodes alone. width,
-- proportion and the rest of the layout stay in the user's own include.
--
-- MEASURED with niri 26.04: a second layout block arriving through include
-- validates, so the nesting may legitimately be split across files. NOT
-- measured: which of two definitions of the same key wins. The include has to
-- come last for this to be the override it is meant to be, and that ordering is
-- unverified until it is watched on a running niri — until then niri is better
-- switched by rewriting its lines than by sourcing this.
--
---@module "lvim-colorscheme.extra.desktop.niri"

local M = {}

--- @param colors ColorScheme
--- @return string
function M.generate(colors)
    local focus = colors.yellow_dark
    local border = colors.green_dark
    -- a6 is the alpha the urgent colour has always carried: the border is meant
    -- to read as a wash over the window, not as a solid frame.
    local urgent = colors.red .. "a6"

    local lines = {
        "// " .. (colors._style_name or "Lvim") .. " — generated by lvim-colorscheme.",
        "// Included from config.kdl, LAST, so these override the layout above.",
        "",
        "layout {",
        "    focus-ring {",
        '        active-color "' .. focus .. '"',
        '        inactive-color "' .. border .. '"',
        "    }",
        "    border {",
        '        active-color "' .. focus .. '"',
        '        inactive-color "' .. border .. '"',
        '        urgent-color "' .. urgent .. '"',
        "    }",
        "}",
        "",
    }
    return table.concat(lines, "\n")
end

return M
