[style.description]
foreground = { rgb = { r = 157, g = 164, b = 164 } }

[style.command_name]
foreground = { rgb = { r = 80, g = 145, b = 193 } }
bold = true

[style.example_text]
foreground = { rgb = { r = 120, g = 143, b = 151 } }

[style.example_code]
foreground = { rgb = { r = 133, g = 146, b = 57 } }

[style.example_variable]
foreground = { rgb = { r = 212, g = 113, b = 72 } }
italic = true
