[style.description]
foreground = { rgb = { r = 179, g = 175, b = 178 } }

[style.command_name]
foreground = { rgb = { r = 115, g = 141, b = 152 } }
bold = true

[style.example_text]
foreground = { rgb = { r = 169, g = 123, b = 159 } }

[style.example_code]
foreground = { rgb = { r = 122, g = 142, b = 126 } }

[style.example_variable]
foreground = { rgb = { r = 169, g = 138, b = 137 } }
italic = true
