[style.description]
foreground = { rgb = { r = 179, g = 175, b = 178 } }

[style.command_name]
foreground = { rgb = { r = 93, g = 109, b = 116 } }
bold = true

[style.example_text]
foreground = { rgb = { r = 137, g = 104, b = 130 } }

[style.example_code]
foreground = { rgb = { r = 120, g = 139, b = 124 } }

[style.example_variable]
foreground = { rgb = { r = 169, g = 138, b = 137 } }
italic = true
