[style.description]
foreground = { rgb = { r = 178, g = 183, b = 199 } }

[style.command_name]
foreground = { rgb = { r = 108, g = 139, b = 195 } }
bold = true

[style.example_text]
foreground = { rgb = { r = 128, g = 135, b = 169 } }

[style.example_code]
foreground = { rgb = { r = 110, g = 147, b = 108 } }

[style.example_variable]
foreground = { rgb = { r = 184, g = 137, b = 112 } }
italic = true
