[style.description]
foreground = { rgb = { r = 94, g = 136, b = 136 } }

[style.command_name]
foreground = { rgb = { r = 76, g = 121, b = 157 } }
bold = true

[style.example_text]
foreground = { rgb = { r = 121, g = 136, b = 144 } }

[style.example_code]
foreground = { rgb = { r = 114, g = 124, b = 62 } }

[style.example_variable]
foreground = { rgb = { r = 171, g = 96, b = 68 } }
italic = true
