[style.description]
foreground = { rgb = { r = 94, g = 136, b = 136 } }

[style.command_name]
foreground = { rgb = { r = 80, g = 137, b = 166 } }
bold = true

[style.example_text]
foreground = { rgb = { r = 139, g = 154, b = 131 } }

[style.example_code]
foreground = { rgb = { r = 123, g = 126, b = 61 } }

[style.example_variable]
foreground = { rgb = { r = 141, g = 82, b = 43 } }
italic = true
