[style.description]
foreground = { rgb = { r = 188, g = 189, b = 189 } }

[style.command_name]
foreground = { rgb = { r = 104, g = 133, b = 173 } }
bold = true

[style.example_text]
foreground = { rgb = { r = 119, g = 133, b = 149 } }

[style.example_code]
foreground = { rgb = { r = 123, g = 153, b = 138 } }

[style.example_variable]
foreground = { rgb = { r = 200, g = 142, b = 98 } }
italic = true
