[style.description]
foreground = { rgb = { r = 188, g = 189, b = 189 } }

[style.command_name]
foreground = { rgb = { r = 114, g = 146, b = 189 } }
bold = true

[style.example_text]
foreground = { rgb = { r = 117, g = 130, b = 146 } }

[style.example_code]
foreground = { rgb = { r = 137, g = 170, b = 154 } }

[style.example_variable]
foreground = { rgb = { r = 212, g = 147, b = 96 } }
italic = true
