[style.description]
foreground = { rgb = { r = 101, g = 156, b = 156 } }

[style.command_name]
foreground = { rgb = { r = 57, g = 155, b = 211 } }
bold = true

[style.example_text]
foreground = { rgb = { r = 104, g = 153, b = 155 } }

[style.example_code]
foreground = { rgb = { r = 128, g = 153, b = 91 } }

[style.example_variable]
foreground = { rgb = { r = 225, g = 149, b = 86 } }
italic = true
