EnableImagePreviewing: true
InlineImagePreview: true
ImagePreviewBackend: "chafa"

OutputFolder: "MyImages"
ColorCorrectionBackend: nn

themes:
- name: "LvimEverforest"
  colors:
    - "#2c3339"
    - "#272e33"
    - "#23292d"
    - "#1f2427"
    - "#1a1f21"
    - "#455156"
    - "#6e776c"
    - "#697167"
    - "#646c62"
    - "#5f675d"
    - "#5a6158"
    - "#7a8478"
    - "#42728b"
    - "#527a57"
    - "#75783a"
    - "#cc7942"
    - "#635d71"
    - "#cb4f4f"
    - "#af9e6b"

- name: "LvimKanagawa"
  colors:
    - "#292a32"
    - "#25262d"
    - "#202127"
    - "#1b1c21"
    - "#17181c"
    - "#1a1a22"
    - "#5d5d79"
    - "#54546d"
    - "#54546D"
    - "#505067"
    - "#4b4b61"
    - "#51515b"
    - "#4d699b"
    - "#597b75"
    - "#6e8156"
    - "#c99460"
    - "#766b90"
    - "#b65252"
    - "#e0c286"

- name: "LvimGruvbox"
  colors:
    - "#353231"
    - "#2c2a29"
    - "#222120"
    - "#1d1c1b"
    - "#181714"
    - "#433f3e"
    - "#746c63"
    - "#6c645c"
    - "#645c54"
    - "#5c544d"
    - "#544c45"
    - "#63584f"
    - "#42728b"
    - "#527a57"
    - "#75783a"
    - "#cc7942"
    - "#635d71"
    - "#cb4f4f"
    - "#af9e6b"

- name: "LvimLight"
  colors:
    - "#eeeeee"
    - "#e9e9e9"
    - "#E4E4E4"
    - "#dfdfdf"
    - "#dadada"
    - "#262f34"
    - "#55a6ab"
    - "#4c969a"
    - "#5e8888"
    - "#3c7478"
    - "#93b6b6"
    - "#789698"
    - "#0879a9"
    - "#01778a"
    - "#748c50"
    - "#a96400"
    - "#1981bd"
    - "#ac4135"
    - "#7e652f"

- name: "LvimDark"
  colors:
    - "#364149"
    - "#2b343a"
    - "#20272b"
    - "#1c2125"
    - "#181d1f"
    - "#2f3940"
    - "#55a6ab"
    - "#4c969a"
    - "#5e8888"
    - "#3c7478"
    - "#374646"
    - "#4d6263"
    - "#0A85B9"
    - "#018FA6"
    - "#8AA55F"
    - "#FF9C2A"
    - "#177ab3"
    - "#e65e4f"
    - "#edc060"

- name: "LvimDarker"
  colors:
    - "#323c43"
    - "#272f34"
    - "#1c2225"
    - "#181c1f"
    - "#141819"
    - "#2b343a"
    - "#55a6ab"
    - "#4c969a"
    - "#5e8888"
    - "#3c7478"
    - "#374646"
    - "#4d6263"
    - "#0A85B9"
    - "#018FA6"
    - "#8AA55F"
    - "#FF9C2A"
    - "#177ab3"
    - "#e65e4f"
    - "#edc060"

