# Lvim Colorscheme GruvboxDarker
[theme-colors]
bg-color = "1a1918"
border-color = "222120"
text-color = "645c54"
tab-text-color = "bb755e"
hops-table-header-bg-color = "201f1e"
hops-table-header-text-color = "746c63"
hops-table-row-active-text-color = "757845"
hops-table-row-inactive-text-color = "64584e"
hops-chart-selected-color = "757845"
hops-chart-unselected-color = "64584e"
hops-chart-axis-color = "222120"
frequency-chart-bar-color = "527a57"
frequency-chart-text-color = "645c54"
flows-chart-bar-selected-color = "757845"
flows-chart-bar-unselected-color = "222120"
flows-chart-text-current-color = "746c63"
flows-chart-text-non-current-color = "64584e"
samples-chart-color = "757845"
samples-chart-lost-color = "ca4f4f"
help-dialog-bg-color = "1e1d1c"
help-dialog-text-color = "645c54"
settings-dialog-bg-color = "1e1d1c"
settings-tab-text-color = "bb755e"
settings-table-header-text-color = "746c63"
settings-table-header-bg-color = "201f1e"
settings-table-row-text-color = "645c54"
map-world-color = "222120"
map-radius-color = "af9e6b"
map-selected-color = "757845"
map-info-panel-border-color = "222120"
map-info-panel-bg-color = "1e1d1c"
map-info-panel-text-color = "645c54"
info-bar-bg-color = "201f1e"
info-bar-text-color = "645c54"
