# Lvim Colorscheme EverforestDark
[theme-colors]
bg-color = "1f2424"
border-color = "272e2e"
text-color = "808e7c"
tab-text-color = "bf775f"
hops-table-header-bg-color = "252c2c"
hops-table-header-text-color = "889784"
hops-table-row-active-text-color = "8c9031"
hops-table-row-inactive-text-color = "7a906f"
hops-chart-selected-color = "75783a"
hops-chart-unselected-color = "535d4e"
hops-chart-axis-color = "272e2e"
frequency-chart-bar-color = "527a57"
frequency-chart-text-color = "808e7c"
flows-chart-bar-selected-color = "75783a"
flows-chart-bar-unselected-color = "272e2e"
flows-chart-text-current-color = "818e7e"
flows-chart-text-non-current-color = "7a906f"
samples-chart-color = "75783a"
samples-chart-lost-color = "cb4f4f"
help-dialog-bg-color = "232929"
help-dialog-text-color = "849380"
settings-dialog-bg-color = "232929"
settings-tab-text-color = "c87b61"
settings-table-header-text-color = "889784"
settings-table-header-bg-color = "252c2c"
settings-table-row-text-color = "849380"
map-world-color = "272e2e"
map-radius-color = "af9e6b"
map-selected-color = "75783a"
map-info-panel-border-color = "272e2e"
map-info-panel-bg-color = "232929"
map-info-panel-text-color = "849380"
info-bar-bg-color = "252c2c"
info-bar-text-color = "869682"
