# Lvim Colorscheme LvimDark
[theme-colors]
bg-color = "1c2327"
border-color = "242b2f"
text-color = "5e8888"
tab-text-color = "c6614d"
hops-table-header-bg-color = "22292d"
hops-table-header-text-color = "55a6ab"
hops-table-row-active-text-color = "7e965a"
hops-table-row-inactive-text-color = "4d6263"
hops-chart-selected-color = "7e965a"
hops-chart-unselected-color = "4d6263"
hops-chart-axis-color = "242b2f"
frequency-chart-bar-color = "448595"
frequency-chart-text-color = "5e8888"
flows-chart-bar-selected-color = "7e965a"
flows-chart-bar-unselected-color = "242b2f"
flows-chart-text-current-color = "55a6ab"
flows-chart-text-non-current-color = "4d6263"
samples-chart-color = "7e965a"
samples-chart-lost-color = "d75e52"
help-dialog-bg-color = "20272b"
help-dialog-text-color = "5e8888"
settings-dialog-bg-color = "20272b"
settings-tab-text-color = "c6614d"
settings-table-header-text-color = "55a6ab"
settings-table-header-bg-color = "22292d"
settings-table-row-text-color = "5e8888"
map-world-color = "242b2f"
map-radius-color = "d8b36f"
map-selected-color = "7e965a"
map-info-panel-border-color = "242b2f"
map-info-panel-bg-color = "20272b"
map-info-panel-text-color = "5e8888"
info-bar-bg-color = "22292d"
info-bar-text-color = "5e8888"
