# Lvim Colorscheme DraculaSoft
[theme-colors]
bg-color = "252732"
border-color = "2d2f3a"
text-color = "c7c7b3"
tab-text-color = "c578a1"
hops-table-header-bg-color = "2b2d38"
hops-table-header-text-color = "c2c2b7"
hops-table-row-active-text-color = "649c70"
hops-table-row-inactive-text-color = "878fad"
hops-chart-selected-color = "62966d"
hops-chart-unselected-color = "727a98"
hops-chart-axis-color = "2d2f3a"
frequency-chart-bar-color = "66938a"
frequency-chart-text-color = "c7c7b3"
flows-chart-bar-selected-color = "62966d"
flows-chart-bar-unselected-color = "2d2f3a"
flows-chart-text-current-color = "c2c2b7"
flows-chart-text-non-current-color = "878fad"
samples-chart-color = "62966d"
samples-chart-lost-color = "bc6060"
help-dialog-bg-color = "292b36"
help-dialog-text-color = "c7c7b3"
settings-dialog-bg-color = "292b36"
settings-tab-text-color = "c77ba3"
settings-table-header-text-color = "c2c2b7"
settings-table-header-bg-color = "2b2d38"
settings-table-row-text-color = "c7c7b3"
map-world-color = "2d2f3a"
map-radius-color = "adb27e"
map-selected-color = "62966d"
map-info-panel-border-color = "2d2f3a"
map-info-panel-bg-color = "292b36"
map-info-panel-text-color = "c7c7b3"
info-bar-bg-color = "2b2d38"
info-bar-text-color = "c7c7b3"
