# Lvim Colorscheme CatppuccinDark
[theme-colors]
bg-color = "191a23"
border-color = "21222b"
text-color = "b2b7c7"
tab-text-color = "b976a7"
hops-table-header-bg-color = "1f2029"
hops-table-header-text-color = "b2b7c7"
hops-table-row-active-text-color = "6b8d69"
hops-table-row-inactive-text-color = "7b82a4"
hops-chart-selected-color = "6b8d69"
hops-chart-unselected-color = "6c7393"
hops-chart-axis-color = "21222b"
frequency-chart-bar-color = "65878e"
frequency-chart-text-color = "b2b7c7"
flows-chart-bar-selected-color = "6b8d69"
flows-chart-bar-unselected-color = "21222b"
flows-chart-text-current-color = "b2b7c7"
flows-chart-text-non-current-color = "7b82a4"
samples-chart-color = "6b8d69"
samples-chart-lost-color = "b7657a"
help-dialog-bg-color = "1d1e27"
help-dialog-text-color = "b2b7c7"
settings-dialog-bg-color = "1d1e27"
settings-tab-text-color = "b976a7"
settings-table-header-text-color = "b2b7c7"
settings-table-header-bg-color = "1f2029"
settings-table-row-text-color = "b2b7c7"
map-world-color = "21222b"
map-radius-color = "b8a47e"
map-selected-color = "6b8d69"
map-info-panel-border-color = "21222b"
map-info-panel-bg-color = "1d1e27"
map-info-panel-text-color = "b2b7c7"
info-bar-bg-color = "1f2029"
info-bar-text-color = "b2b7c7"
