# Lvim Colorscheme NightfoxSoft
[theme-colors]
bg-color = "192433"
border-color = "212c3b"
text-color = "bcbdbd"
tab-text-color = "9a80ae"
hops-table-header-bg-color = "1f2a39"
hops-table-header-text-color = "bcbcbd"
hops-table-row-active-text-color = "7b998a"
hops-table-row-inactive-text-color = "7d8c9f"
hops-chart-selected-color = "7b998a"
hops-chart-unselected-color = "758292"
hops-chart-axis-color = "212c3b"
frequency-chart-bar-color = "69a3a4"
frequency-chart-text-color = "bcbdbd"
flows-chart-bar-selected-color = "7b998a"
flows-chart-bar-unselected-color = "212c3b"
flows-chart-text-current-color = "bcbcbd"
flows-chart-text-non-current-color = "7d8c9f"
samples-chart-color = "7b998a"
samples-chart-lost-color = "b26377"
help-dialog-bg-color = "1d2837"
help-dialog-text-color = "bcbdbd"
settings-dialog-bg-color = "1d2837"
settings-tab-text-color = "9f85b3"
settings-table-header-text-color = "bcbcbd"
settings-table-header-bg-color = "1f2a39"
settings-table-row-text-color = "bcbdbd"
map-world-color = "212c3b"
map-radius-color = "bba76f"
map-selected-color = "7b998a"
map-info-panel-border-color = "212c3b"
map-info-panel-bg-color = "1d2837"
map-info-panel-text-color = "bcbdbd"
info-bar-bg-color = "1f2a39"
info-bar-text-color = "bcbdbd"
