# Lvim Colorscheme GruvboxDark
[theme-colors]
bg-color = "181714"
border-color = "353231"
text-color = "645c54"
tab-text-color = "bb755e"
hops-table-header-bg-color = "2c2a29"
hops-table-header-text-color = "746c63"
hops-table-row-active-text-color = "75783a"
hops-table-row-inactive-text-color = "64584e"
hops-chart-selected-color = "75783a"
hops-chart-unselected-color = "64584e"
hops-chart-axis-color = "353231"
frequency-chart-bar-color = "527a57"
frequency-chart-text-color = "645c54"
flows-chart-bar-selected-color = "75783a"
flows-chart-bar-unselected-color = "353231"
flows-chart-text-current-color = "746c63"
flows-chart-text-non-current-color = "64584e"
samples-chart-color = "75783a"
samples-chart-lost-color = "cb4f4f"
help-dialog-bg-color = "222120"
help-dialog-text-color = "645c54"
settings-dialog-bg-color = "222120"
settings-tab-text-color = "bb755e"
settings-table-header-text-color = "746c63"
settings-table-header-bg-color = "2c2a29"
settings-table-row-text-color = "645c54"
map-world-color = "353231"
map-radius-color = "af9e6b"
map-selected-color = "75783a"
map-info-panel-border-color = "353231"
map-info-panel-bg-color = "222120"
map-info-panel-text-color = "645c54"
info-bar-bg-color = "2c2a29"
info-bar-text-color = "645c54"
