# Lvim Colorscheme NordDark
[theme-colors]
bg-color = "1a1e25"
border-color = "323946"
text-color = "b3bac6"
tab-text-color = "a58aa0"
hops-table-header-bg-color = "2b313c"
hops-table-header-text-color = "b4bac6"
hops-table-row-active-text-color = "97ab86"
hops-table-row-inactive-text-color = "677185"
hops-chart-selected-color = "97ab86"
hops-chart-unselected-color = "677185"
hops-chart-axis-color = "323946"
frequency-chart-bar-color = "7eaab7"
frequency-chart-text-color = "b3bac6"
flows-chart-bar-selected-color = "97ab86"
flows-chart-bar-unselected-color = "323946"
flows-chart-text-current-color = "b4bac6"
flows-chart-text-non-current-color = "677185"
samples-chart-color = "97ab86"
samples-chart-lost-color = "af7177"
help-dialog-bg-color = "232831"
help-dialog-text-color = "b3bac6"
settings-dialog-bg-color = "232831"
settings-tab-text-color = "a58aa0"
settings-table-header-text-color = "b4bac6"
settings-table-header-bg-color = "2b313c"
settings-table-row-text-color = "b3bac6"
map-world-color = "323946"
map-radius-color = "cbae72"
map-selected-color = "97ab86"
map-info-panel-border-color = "323946"
map-info-panel-bg-color = "232831"
map-info-panel-text-color = "b3bac6"
info-bar-bg-color = "2b313c"
info-bar-text-color = "b3bac6"
