# Lvim Colorscheme NordDarker
[theme-colors]
bg-color = "191d24"
border-color = "21252c"
text-color = "b3bac6"
tab-text-color = "a2869d"
hops-table-header-bg-color = "1f232a"
hops-table-header-text-color = "b4bac6"
hops-table-row-active-text-color = "879978"
hops-table-row-inactive-text-color = "677185"
hops-chart-selected-color = "879978"
hops-chart-unselected-color = "677185"
hops-chart-axis-color = "21252c"
frequency-chart-bar-color = "7097a3"
frequency-chart-text-color = "b3bac6"
flows-chart-bar-selected-color = "879978"
flows-chart-bar-unselected-color = "21252c"
flows-chart-text-current-color = "b4bac6"
flows-chart-text-non-current-color = "677185"
samples-chart-color = "879978"
samples-chart-lost-color = "ac6e74"
help-dialog-bg-color = "1d2128"
help-dialog-text-color = "b3bac6"
settings-dialog-bg-color = "1d2128"
settings-tab-text-color = "a2869d"
settings-table-header-text-color = "b4bac6"
settings-table-header-bg-color = "1f232a"
settings-table-row-text-color = "b3bac6"
map-world-color = "21252c"
map-radius-color = "c3a870"
map-selected-color = "879978"
map-info-panel-border-color = "21252c"
map-info-panel-bg-color = "1d2128"
map-info-panel-text-color = "b3bac6"
info-bar-bg-color = "1f232a"
info-bar-text-color = "b3bac6"
