# Lvim Colorscheme RosepineSoft
[theme-colors]
bg-color = "1f1d22"
border-color = "27252a"
text-color = "b3afb2"
tab-text-color = "9084a2"
hops-table-header-bg-color = "252328"
hops-table-header-text-color = "b9b4b5"
hops-table-row-active-text-color = "788b7c"
hops-table-row-inactive-text-color = "a5789c"
hops-chart-selected-color = "788b7c"
hops-chart-unselected-color = "896882"
hops-chart-axis-color = "27252a"
frequency-chart-bar-color = "788787"
frequency-chart-text-color = "b3afb2"
flows-chart-bar-selected-color = "788b7c"
flows-chart-bar-unselected-color = "27252a"
flows-chart-text-current-color = "b9b4b5"
flows-chart-text-non-current-color = "a5789c"
samples-chart-color = "788b7c"
samples-chart-lost-color = "a0727c"
help-dialog-bg-color = "232126"
help-dialog-text-color = "b3afb2"
settings-dialog-bg-color = "232126"
settings-tab-text-color = "9084a2"
settings-table-header-text-color = "b9b4b5"
settings-table-header-bg-color = "252328"
settings-table-row-text-color = "b3afb2"
map-world-color = "27252a"
map-radius-color = "b6a18b"
map-selected-color = "788b7c"
map-info-panel-border-color = "27252a"
map-info-panel-bg-color = "232126"
map-info-panel-text-color = "b3afb2"
info-bar-bg-color = "252328"
info-bar-text-color = "b3afb2"
