# Lvim Colorscheme MaterialSoft
[theme-colors]
bg-color = "1f282d"
border-color = "36464e"
text-color = "b2c7c7"
tab-text-color = "da596e"
hops-table-header-bg-color = "2f3d44"
hops-table-header-text-color = "b8bec2"
hops-table-row-active-text-color = "a6c974"
hops-table-row-inactive-text-color = "5e6a70"
hops-chart-selected-color = "a6c974"
hops-chart-unselected-color = "5e6a70"
hops-chart-axis-color = "36464e"
frequency-chart-bar-color = "63bbdf"
frequency-chart-text-color = "b2c7c7"
flows-chart-bar-selected-color = "a6c974"
flows-chart-bar-unselected-color = "36464e"
flows-chart-text-current-color = "b8bec2"
flows-chart-text-non-current-color = "5e6a70"
samples-chart-color = "a6c974"
samples-chart-lost-color = "d1676c"
help-dialog-bg-color = "273339"
help-dialog-text-color = "b2c7c7"
settings-dialog-bg-color = "273339"
settings-tab-text-color = "da596e"
settings-table-header-text-color = "b8bec2"
settings-table-header-bg-color = "2f3d44"
settings-table-row-text-color = "b2c7c7"
map-world-color = "36464e"
map-radius-color = "deb05c"
map-selected-color = "a6c974"
map-info-panel-border-color = "36464e"
map-info-panel-bg-color = "273339"
map-info-panel-text-color = "b2c7c7"
info-bar-bg-color = "2f3d44"
info-bar-text-color = "b2c7c7"
