# Lvim Colorscheme NightfoxDark
[theme-colors]
bg-color = "151f2c"
border-color = "1d2734"
text-color = "bcbdbd"
tab-text-color = "9a80ae"
hops-table-header-bg-color = "1b2532"
hops-table-header-text-color = "bcbcbd"
hops-table-row-active-text-color = "7b998a"
hops-table-row-inactive-text-color = "758292"
hops-chart-selected-color = "7b998a"
hops-chart-unselected-color = "758292"
hops-chart-axis-color = "1d2734"
frequency-chart-bar-color = "69a3a4"
frequency-chart-text-color = "bcbdbd"
flows-chart-bar-selected-color = "7b998a"
flows-chart-bar-unselected-color = "1d2734"
flows-chart-text-current-color = "bcbcbd"
flows-chart-text-non-current-color = "758292"
samples-chart-color = "7b998a"
samples-chart-lost-color = "b26377"
help-dialog-bg-color = "192330"
help-dialog-text-color = "bcbdbd"
settings-dialog-bg-color = "192330"
settings-tab-text-color = "9a80ae"
settings-table-header-text-color = "bcbcbd"
settings-table-header-bg-color = "1b2532"
settings-table-row-text-color = "bcbdbd"
map-world-color = "1d2734"
map-radius-color = "bba76f"
map-selected-color = "7b998a"
map-info-panel-border-color = "1d2734"
map-info-panel-bg-color = "192330"
map-info-panel-text-color = "bcbdbd"
info-bar-bg-color = "1b2532"
info-bar-text-color = "bcbdbd"
