# Lvim Colorscheme EverforestSoft
[theme-colors]
bg-color = "202527"
border-color = "32393f"
text-color = "82907e"
tab-text-color = "c37960"
hops-table-header-bg-color = "2e3439"
hops-table-header-text-color = "8f9f8b"
hops-table-row-active-text-color = "8c9031"
hops-table-row-inactive-text-color = "7c9370"
hops-chart-selected-color = "75783a"
hops-chart-unselected-color = "535d4e"
hops-chart-axis-color = "32393f"
frequency-chart-bar-color = "527a57"
frequency-chart-text-color = "82907e"
flows-chart-bar-selected-color = "75783a"
flows-chart-bar-unselected-color = "32393f"
flows-chart-text-current-color = "818e7e"
flows-chart-text-non-current-color = "7c9370"
samples-chart-color = "75783a"
samples-chart-lost-color = "cb4f4f"
help-dialog-bg-color = "292f33"
help-dialog-text-color = "8b9b86"
settings-dialog-bg-color = "292f33"
settings-tab-text-color = "d58163"
settings-table-header-text-color = "8f9f8b"
settings-table-header-bg-color = "2e3439"
settings-table-row-text-color = "8b9b86"
map-world-color = "32393f"
map-radius-color = "af9e6b"
map-selected-color = "75783a"
map-info-panel-border-color = "32393f"
map-info-panel-bg-color = "292f33"
map-info-panel-text-color = "8b9b86"
info-bar-bg-color = "2e3439"
info-bar-text-color = "8fa18a"
