# Lvim Colorscheme EverforestDarker
[theme-colors]
bg-color = "161b1d"
border-color = "282f35"
text-color = "5a6158"
tab-text-color = "bb755e"
hops-table-header-bg-color = "242a2f"
hops-table-header-text-color = "646c62"
hops-table-row-active-text-color = "75783a"
hops-table-row-inactive-text-color = "535d4e"
hops-chart-selected-color = "75783a"
hops-chart-unselected-color = "535d4e"
hops-chart-axis-color = "282f35"
frequency-chart-bar-color = "527a57"
frequency-chart-text-color = "5a6158"
flows-chart-bar-selected-color = "75783a"
flows-chart-bar-unselected-color = "282f35"
flows-chart-text-current-color = "646c62"
flows-chart-text-non-current-color = "535d4e"
samples-chart-color = "75783a"
samples-chart-lost-color = "cb4f4f"
help-dialog-bg-color = "1f2529"
help-dialog-text-color = "5a6158"
settings-dialog-bg-color = "1f2529"
settings-tab-text-color = "bb755e"
settings-table-header-text-color = "646c62"
settings-table-header-bg-color = "242a2f"
settings-table-row-text-color = "5a6158"
map-world-color = "282f35"
map-radius-color = "af9e6b"
map-selected-color = "75783a"
map-info-panel-border-color = "282f35"
map-info-panel-bg-color = "1f2529"
map-info-panel-text-color = "5a6158"
info-bar-bg-color = "242a2f"
info-bar-text-color = "5a6158"
