# Lvim Colorscheme GruvboxLight
[theme-colors]
bg-color = "dadada"
border-color = "eeeeee"
text-color = "5e8888"
tab-text-color = "915a47"
hops-table-header-bg-color = "e9e9e9"
hops-table-header-text-color = "55a6ab"
hops-table-row-active-text-color = "7a7d48"
hops-table-row-inactive-text-color = "a59283"
hops-chart-selected-color = "7a7d48"
hops-chart-unselected-color = "a59283"
hops-chart-axis-color = "eeeeee"
frequency-chart-bar-color = "5c8861"
frequency-chart-text-color = "5e8888"
flows-chart-bar-selected-color = "7a7d48"
flows-chart-bar-unselected-color = "eeeeee"
flows-chart-text-current-color = "55a6ab"
flows-chart-text-non-current-color = "a59283"
samples-chart-color = "7a7d48"
samples-chart-lost-color = "c74e4e"
help-dialog-bg-color = "E4E4E4"
help-dialog-text-color = "5e8888"
settings-dialog-bg-color = "E4E4E4"
settings-tab-text-color = "915a47"
settings-table-header-text-color = "55a6ab"
settings-table-header-bg-color = "e9e9e9"
settings-table-row-text-color = "5e8888"
map-world-color = "eeeeee"
map-radius-color = "8f8156"
map-selected-color = "7a7d48"
map-info-panel-border-color = "eeeeee"
map-info-panel-bg-color = "E4E4E4"
map-info-panel-text-color = "5e8888"
info-bar-bg-color = "e9e9e9"
info-bar-text-color = "5e8888"
