# Lvim Colorscheme SolarizedDarker
[theme-colors]
bg-color = "001318"
border-color = "0c404c"
text-color = "9da4a4"
tab-text-color = "b75283"
hops-table-header-bg-color = "06303a"
hops-table-header-text-color = "969e9e"
hops-table-row-active-text-color = "727f1a"
hops-table-row-inactive-text-color = "5d6a6f"
hops-chart-selected-color = "727f1a"
hops-chart-unselected-color = "5d6a6f"
hops-chart-axis-color = "0c404c"
frequency-chart-bar-color = "3e8d87"
frequency-chart-text-color = "9da4a4"
flows-chart-bar-selected-color = "727f1a"
flows-chart-bar-unselected-color = "0c404c"
flows-chart-text-current-color = "969e9e"
flows-chart-text-non-current-color = "5d6a6f"
samples-chart-color = "727f1a"
samples-chart-lost-color = "bf4e4c"
help-dialog-bg-color = "001f27"
help-dialog-text-color = "9da4a4"
settings-dialog-bg-color = "001f27"
settings-tab-text-color = "b75283"
settings-table-header-text-color = "969e9e"
settings-table-header-bg-color = "06303a"
settings-table-row-text-color = "9da4a4"
map-world-color = "0c404c"
map-radius-color = "96791f"
map-selected-color = "727f1a"
map-info-panel-border-color = "0c404c"
map-info-panel-bg-color = "001f27"
map-info-panel-text-color = "9da4a4"
info-bar-bg-color = "06303a"
info-bar-text-color = "9da4a4"
