# Lvim Colorscheme EverforestDark
--colors=path:fg:58,151,191
--colors=path:style:bold
--colors=line:fg:124,147,112
--colors=column:fg:124,147,112
--colors=match:fg:31,36,36
--colors=match:bg:175,158,107
--colors=match:style:nobold
