# Lvim Colorscheme CatppuccinDark
--colors=path:fg:103,147,218
--colors=path:style:bold
--colors=line:fg:108,115,147
--colors=column:fg:108,115,147
--colors=match:fg:17,17,27
--colors=match:bg:216,185,115
--colors=match:style:nobold
