# Lvim Colorscheme BaseDark
--colors=path:fg:62,146,197
--colors=path:style:bold
--colors=line:fg:101,147,149
--colors=column:fg:101,147,149
--colors=match:fg:28,35,39
--colors=match:bg:216,179,111
--colors=match:style:nobold
