# Lvim Colorscheme GruvboxLight
--colors=path:fg:75,101,117
--colors=path:style:bold
--colors=line:fg:106,97,90
--colors=column:fg:106,97,90
--colors=match:fg:255,255,255
--colors=match:bg:128,116,82
--colors=match:style:nobold
