# Lvim Colorscheme TokyonightSoft
--colors=path:fg:114,138,198
--colors=path:style:bold
--colors=line:fg:128,136,172
--colors=column:fg:128,136,172
--colors=match:fg:30,33,42
--colors=match:bg:183,157,123
--colors=match:style:nobold
