# Lvim Colorscheme SolarizedDark
--colors=path:fg:80,145,193
--colors=path:style:bold
--colors=line:fg:120,143,151
--colors=column:fg:120,143,151
--colors=match:fg:0,39,50
--colors=match:bg:162,135,73
--colors=match:style:nobold
