# Lvim Colorscheme KanagawaSoft
--colors=path:fg:77,105,155
--colors=path:style:bold
--colors=line:fg:78,78,115
--colors=column:fg:78,78,115
--colors=match:fg:29,30,34
--colors=match:bg:224,194,134
--colors=match:style:nobold
