# Lvim Colorscheme KanagawaLight
--colors=path:fg:99,133,194
--colors=path:style:bold
--colors=line:fg:157,157,181
--colors=column:fg:157,157,181
--colors=match:fg:218,218,218
--colors=match:bg:129,111,74
--colors=match:style:nobold
