# Lvim Colorscheme RosepineLight
--colors=path:fg:88,99,103
--colors=path:style:bold
--colors=line:fg:116,92,110
--colors=column:fg:116,92,110
--colors=match:fg:255,255,255
--colors=match:bg:131,116,101
--colors=match:style:nobold
