# Lvim Colorscheme TokyonightSoft
--colors=path:fg:101,137,215
--colors=path:style:bold
--colors=line:fg:97,103,132
--colors=column:fg:97,103,132
--colors=match:fg:24,24,32
--colors=match:bg:197,160,107
--colors=match:style:nobold
