# Lvim Colorscheme KanagawaDarker
--colors=path:fg:85,131,205
--colors=path:style:bold
--colors=line:fg:129,129,178
--colors=column:fg:129,129,178
--colors=match:fg:24,25,31
--colors=match:bg:209,181,124
--colors=match:style:nobold
