# Lvim Colorscheme KanagawaSoft
--colors=path:fg:87,142,224
--colors=path:style:bold
--colors=line:fg:137,137,185
--colors=column:fg:137,137,185
--colors=match:fg:34,35,41
--colors=match:bg:209,181,124
--colors=match:style:nobold
