# Lvim Colorscheme RosepineSoft
--colors=path:fg:115,141,152
--colors=path:style:bold
--colors=line:fg:169,123,159
--colors=column:fg:169,123,159
--colors=match:fg:31,29,34
--colors=match:bg:182,161,139
--colors=match:style:nobold
