# Lvim Colorscheme DraculaSoft
--colors=path:fg:99,137,147
--colors=path:style:bold
--colors=line:fg:114,122,152
--colors=column:fg:114,122,152
--colors=match:fg:37,39,50
--colors=match:bg:173,178,126
--colors=match:style:nobold
