# Lvim Colorscheme TokyonightDarker
--colors=path:fg:105,130,191
--colors=path:style:bold
--colors=line:fg:120,128,164
--colors=column:fg:120,128,164
--colors=match:fg:20,23,30
--colors=match:bg:183,157,123
--colors=match:style:nobold
