# Lvim Colorscheme EverforestSoft
--colors=path:fg:55,154,195
--colors=path:style:bold
--colors=line:fg:128,152,115
--colors=column:fg:128,152,115
--colors=match:fg:32,37,39
--colors=match:bg:175,158,107
--colors=match:style:nobold
