# Lvim Colorscheme MaterialSoft
--colors=path:fg:117,150,227
--colors=path:style:bold
--colors=line:fg:129,154,165
--colors=column:fg:129,154,165
--colors=match:fg:35,47,53
--colors=match:bg:207,169,106
--colors=match:style:nobold
