# Lvim Colorscheme GruvboxDarker
--colors=path:fg:76,138,170
--colors=path:style:bold
--colors=line:fg:152,128,107
--colors=column:fg:152,128,107
--colors=match:fg:26,25,24
--colors=match:bg:175,158,107
--colors=match:style:nobold
