# Lvim Colorscheme RosepineDark
--colors=path:fg:93,109,116
--colors=path:style:bold
--colors=line:fg:137,104,130
--colors=column:fg:137,104,130
--colors=match:fg:25,23,27
--colors=match:bg:182,161,139
--colors=match:style:nobold
