# Lvim Colorscheme EverforestLight
--colors=path:fg:71,102,119
--colors=path:style:bold
--colors=line:fg:94,101,90
--colors=column:fg:94,101,90
--colors=match:fg:255,255,255
--colors=match:bg:128,116,82
--colors=match:style:nobold
