# Lvim Colorscheme MaterialSoft
--colors=path:fg:91,127,203
--colors=path:style:bold
--colors=line:fg:94,106,112
--colors=column:fg:94,106,112
--colors=match:fg:35,47,53
--colors=match:bg:207,169,106
--colors=match:style:nobold
