# Lvim Colorscheme MaterialSoft
--colors=path:fg:97,138,223
--colors=path:style:bold
--colors=line:fg:94,106,112
--colors=column:fg:94,106,112
--colors=match:fg:31,40,45
--colors=match:bg:222,176,92
--colors=match:style:nobold
