# Lvim Colorscheme BaseSoft
--colors=path:fg:68,124,162
--colors=path:style:bold
--colors=line:fg:77,98,99
--colors=column:fg:77,98,99
--colors=match:fg:34,41,45
--colors=match:bg:216,179,111
--colors=match:style:nobold
