# Lvim Colorscheme NightfoxSoft
--colors=path:fg:114,146,189
--colors=path:style:bold
--colors=line:fg:117,130,146
--colors=column:fg:117,130,146
--colors=match:fg:23,31,43
--colors=match:bg:193,172,113
--colors=match:style:nobold
