# Lvim Colorscheme NordLight
--colors=path:fg:118,139,161
--colors=path:style:bold
--colors=line:fg:115,125,149
--colors=column:fg:115,125,149
--colors=match:fg:218,218,218
--colors=match:bg:135,115,74
--colors=match:style:nobold
