# Lvim Colorscheme DraculaDark
--colors=path:fg:101,200,221
--colors=path:style:bold
--colors=line:fg:114,122,152
--colors=column:fg:114,122,152
--colors=match:fg:27,29,37
--colors=match:bg:208,218,104
--colors=match:style:nobold
