# Lvim Colorscheme EverforestDark
--colors=path:fg:66,114,139
--colors=path:style:bold
--colors=line:fg:83,93,78
--colors=column:fg:83,93,78
--colors=match:fg:26,31,33
--colors=match:bg:175,158,107
--colors=match:style:nobold
