# Lvim Colorscheme LvimLight
--colors=path:fg:8,121,169
--colors=path:style:bold
--colors=line:fg:120,150,152
--colors=column:fg:120,150,152
--colors=match:fg:218,218,218
--colors=match:bg:126,101,47
--colors=match:style:nobold
