# Lvim Colorscheme RosepineLight
--colors=path:fg:115,135,143
--colors=path:style:bold
--colors=line:fg:149,113,141
--colors=column:fg:149,113,141
--colors=match:fg:218,218,218
--colors=match:bg:140,123,106
--colors=match:style:nobold
