# Lvim Colorscheme GruvboxDark
--colors=path:fg:76,144,178
--colors=path:style:bold
--colors=line:fg:155,131,109
--colors=column:fg:155,131,109
--colors=match:fg:30,29,28
--colors=match:bg:175,158,107
--colors=match:style:nobold
