# Lvim Colorscheme TokyonightDark
--colors=path:fg:108,133,193
--colors=path:style:bold
--colors=line:fg:125,133,169
--colors=column:fg:125,133,169
--colors=match:fg:25,28,36
--colors=match:bg:183,157,123
--colors=match:style:nobold
