# Lvim Colorscheme EverforestDarker
--colors=path:fg:61,145,182
--colors=path:style:bold
--colors=line:fg:120,141,109
--colors=column:fg:120,141,109
--colors=match:fg:22,27,29
--colors=match:bg:175,158,107
--colors=match:style:nobold
