# Lvim Colorscheme SolarizedDarker
--colors=path:fg:80,137,180
--colors=path:style:bold
--colors=line:fg:114,135,142
--colors=column:fg:114,135,142
--colors=match:fg:0,27,35
--colors=match:bg:159,133,73
--colors=match:style:nobold
