# Lvim Colorscheme BaseSoft
--colors=path:fg:57,155,211
--colors=path:style:bold
--colors=line:fg:104,153,155
--colors=column:fg:104,153,155
--colors=match:fg:34,41,45
--colors=match:bg:216,179,111
--colors=match:style:nobold
