# Lvim Colorscheme MaterialLight
--colors=path:fg:60,98,168
--colors=path:style:bold
--colors=line:fg:121,137,145
--colors=column:fg:121,137,145
--colors=match:fg:218,218,218
--colors=match:bg:139,109,55
--colors=match:style:nobold
