# Lvim Colorscheme CatppuccinDark
--colors=path:fg:105,133,186
--colors=path:style:bold
--colors=line:fg:126,133,166
--colors=column:fg:126,133,166
--colors=match:fg:25,26,35
--colors=match:bg:184,164,126
--colors=match:style:nobold
