# Lvim Colorscheme KanagawaSoft
--colors=path:fg:78,106,156
--colors=path:style:bold
--colors=line:fg:78,78,115
--colors=column:fg:78,78,115
--colors=match:fg:34,35,41
--colors=match:bg:209,181,124
--colors=match:style:nobold
