[colors]
foreground = "#a7afaf"
background = "#00323f"
cursor_bg = "#727c3e"
cursor_fg = "#00303d"
cursor_border = "#727c3e"
selection_fg = "#9da4a4"
selection_bg = "#023643"
scrollbar_thumb = "#023643"
split = "#023643"

ansi = [
  "#002a34",
  "#c24f4d",
  "#727c3e",
  "#9f8549",
  "#477193",
  "#c0578a",
  "#4b8580",
  "#747878",
]
brights = [
  "#113f4a",
  "#ea4440",
  "#7d8b25",
  "#b4912e",
  "#3680b0",
  "#e64d9d",
  "#37968f",
  "#767a7a",
]

[colors.tab_bar]
background = "#00303d"

[colors.tab_bar.active_tab]
bg_color = "#4f7ea3"
fg_color = "#00303d"

[colors.tab_bar.inactive_tab]
bg_color = "#023643"
fg_color = "#003441"