[colors]
foreground = "#bcbdbd"
background = "#151d28"
cursor_bg = "#89aa9a"
cursor_fg = "#131a24"
cursor_border = "#89aa9a"
selection_fg = "#bcbdbd"
selection_bg = "#212e40"
scrollbar_thumb = "#212e40"
split = "#212e40"

ansi = [
  "#141c26",
  "#b46478",
  "#89aa9a",
  "#c1ac71",
  "#5f84b4",
  "#9b82af",
  "#75bbbd",
  "#b1b5bc",
]
brights = [
  "#2b3b51",
  "#d76383",
  "#7ebda0",
  "#d6b95a",
  "#5192d8",
  "#b08acd",
  "#5cced0",
  "#bcbdbd",
]

[colors.tab_bar]
background = "#131a24"

[colors.tab_bar.active_tab]
bg_color = "#7292bd"
fg_color = "#131a24"

[colors.tab_bar.inactive_tab]
bg_color = "#212e40"
fg_color = "#192330"