[colors]
foreground = "#aa9782"
background = "#1c1b1a"
cursor_bg = "#757845"
cursor_fg = "#1a1918"
cursor_border = "#757845"
selection_fg = "#645c54"
selection_bg = "#201f1e"
scrollbar_thumb = "#201f1e"
split = "#201f1e"

ansi = [
  "#181716",
  "#ca4f4f",
  "#757845",
  "#af9e6b",
  "#3f6376",
  "#bb755e",
  "#527a57",
  "#645c54",
]
brights = [
  "#2a2724",
  "#ea4c4c",
  "#828633",
  "#c3ab58",
  "#33728d",
  "#dd7950",
  "#488b52",
  "#6f665c",
]

[colors.tab_bar]
background = "#1a1918"

[colors.tab_bar.active_tab]
bg_color = "#497188"
fg_color = "#1a1918"

[colors.tab_bar.inactive_tab]
bg_color = "#201f1e"
fg_color = "#1e1d1c"