[colors]
foreground = "#b4b2c7"
background = "#191724"
cursor_bg = "#83b2ba"
cursor_fg = "#0a0910"
cursor_border = "#83b2ba"
selection_fg = "#b4b2c7"
selection_bg = "#211f2c"
scrollbar_thumb = "#211f2c"
split = "#211f2c"

ansi = [
  "#0f0e16",
  "#cd6985",
  "#83b2ba",
  "#d6a765",
  "#3b6374",
  "#9f80c4",
  "#83b2ba",
  "#9694a3",
]
brights = [
  "#312f44",
  "#e57091",
  "#74c4d0",
  "#f0b246",
  "#2d728a",
  "#b189df",
  "#74c4d0",
  "#b4b2c7",
]

[colors.tab_bar]
background = "#0a0910"

[colors.tab_bar.active_tab]
bg_color = "#416d7f"
fg_color = "#0a0910"

[colors.tab_bar.inactive_tab]
bg_color = "#211f2c"
fg_color = "#13111b"