[colors]
foreground = "#bcbdbd"
background = "#1b2635"
cursor_bg = "#7b998a"
cursor_fg = "#192433"
cursor_border = "#7b998a"
selection_fg = "#bcbdbd"
selection_bg = "#1f2a39"
scrollbar_thumb = "#1f2a39"
split = "#1f2a39"

ansi = [
  "#17202c",
  "#b26377",
  "#7b998a",
  "#bba76f",
  "#5677a3",
  "#9a80ae",
  "#69a3a4",
  "#737474",
]
brights = [
  "#2b3543",
  "#d66182",
  "#72ab90",
  "#d0b459",
  "#4a85c6",
  "#af87cc",
  "#56b5b6",
  "#878888",
]

[colors.tab_bar]
background = "#192433"

[colors.tab_bar.active_tab]
bg_color = "#6885ad"
fg_color = "#192433"

[colors.tab_bar.inactive_tab]
bg_color = "#1f2a39"
fg_color = "#1d2837"