[colors]
foreground = "#6aaeae"
background = "#1e2529"
cursor_bg = "#7e965a"
cursor_fg = "#1c2327"
cursor_border = "#7e965a"
selection_fg = "#5e8888"
selection_bg = "#22292d"
scrollbar_thumb = "#22292d"
split = "#22292d"

ansi = [
  "#1a1f22",
  "#d75e52",
  "#7e965a",
  "#d8b36f",
  "#3b6d8d",
  "#c6614d",
  "#448595",
  "#547373",
]
brights = [
  "#263336",
  "#f06455",
  "#84a647",
  "#f0bf51",
  "#237ca8",
  "#ea5f3a",
  "#2595ab",
  "#557575",
]

[colors.tab_bar]
background = "#1c2327"

[colors.tab_bar.active_tab]
bg_color = "#447ca2"
fg_color = "#1c2327"

[colors.tab_bar.inactive_tab]
bg_color = "#22292d"
fg_color = "#20272b"