[colors]
foreground = "#b2b7c7"
background = "#20212b"
cursor_bg = "#6b8d69"
cursor_fg = "#1e1f29"
cursor_border = "#6b8d69"
selection_fg = "#b2b7c7"
selection_bg = "#24252f"
scrollbar_thumb = "#24252f"
split = "#24252f"

ansi = [
  "#1b1c24",
  "#b7657a",
  "#6b8d69",
  "#b8a47e",
  "#546891",
  "#b976a7",
  "#65878e",
  "#6a6e7d",
]
brights = [
  "#2f303b",
  "#d86685",
  "#649f5f",
  "#ceb06f",
  "#4f74b5",
  "#d57abe",
  "#5b97a2",
  "#7c8296",
]

[colors.tab_bar]
background = "#1e1f29"

[colors.tab_bar.active_tab]
bg_color = "#6076a0"
fg_color = "#1e1f29"

[colors.tab_bar.inactive_tab]
bg_color = "#24252f"
fg_color = "#22232d"