[colors]
foreground = "#9da4a4"
background = "#001d25"
cursor_bg = "#727c3e"
cursor_fg = "#001b23"
cursor_border = "#727c3e"
selection_fg = "#9da4a4"
selection_bg = "#022129"
scrollbar_thumb = "#022129"
split = "#022129"

ansi = [
  "#00191f",
  "#c24f4d",
  "#727c3e",
  "#9f8549",
  "#477193",
  "#c0578a",
  "#4b8580",
  "#626666",
]
brights = [
  "#102b32",
  "#ea4440",
  "#7d8b25",
  "#b4912e",
  "#3680b0",
  "#e64d9d",
  "#37968f",
  "#6c7070",
]

[colors.tab_bar]
background = "#001b23"

[colors.tab_bar.active_tab]
bg_color = "#4f7ea3"
fg_color = "#001b23"

[colors.tab_bar.inactive_tab]
bg_color = "#022129"
fg_color = "#001f27"