# Lvim Colorscheme SolarizedDarker

[styles.cpu]
all_entry_color = "#9da4a4"
avg_entry_color = "#cf5a93"
cpu_core_colors = ["#5089b4", "#7e8a3c", "#9f8549", "#c16a49", "#7f81a2", "#4a8f74", "#4c8e88", "#dd5755"]

[styles.memory]
ram_color = "#7e8a3c"
cache_color = "#4c8e88"
swap_color = "#c16a49"
arc_color = "#4a8f74"

[styles.network]
rx_color = "#7e8a3c"
tx_color = "#cf5a93"
rx_total_color = "#7d8a2f"
tx_total_color = "#d55193"

[styles.battery]
high_battery_color = "#7e8a3c"
medium_battery_color = "#9f8549"
low_battery_color = "#dd5755"

[styles.tables]
headers = { color = "#5089b4", bold = true }

[styles.graphs]
graph_color = "#5d6a6f"
legend_text = "#75878d"

[styles.widgets]
border_color = "#04232b"
selected_border_color = "#4f7ea3"
widget_title = { color = "#969e9e", bold = true }
text = "#9da4a4"
selected_text = { color = "#ffffff", bg_color = "#4e7b9f" }
disabled_text = "#72878e"
