# Lvim Colorscheme SolarizedSoft

[styles.cpu]
all_entry_color = "#9da4a4"
avg_entry_color = "#b75283"
cpu_core_colors = ["#4386b5", "#727f1a", "#96791f", "#ac5835", "#8385a2", "#3e8d87", "#3e8d87", "#bf4e4c"]

[styles.memory]
ram_color = "#727f1a"
cache_color = "#3e8d87"
swap_color = "#ac5835"
arc_color = "#3e8d87"

[styles.network]
rx_color = "#727f1a"
tx_color = "#b75283"
rx_total_color = "#687418"
tx_total_color = "#aa4777"

[styles.battery]
high_battery_color = "#727f1a"
medium_battery_color = "#96791f"
low_battery_color = "#bf4e4c"

[styles.tables]
headers = { color = "#4386b5", bold = true }

[styles.graphs]
graph_color = "#5d6a6f"
legend_text = "#5f6a6e"

[styles.widgets]
border_color = "#105363"
selected_border_color = "#4386b5"
widget_title = { color = "#969e9e", bold = true }
text = "#9da4a4"
selected_text = { color = "#002832", bg_color = "#4386b5" }
disabled_text = "#5d6a6f"
