# Lvim Colorscheme KanagawaDarker

[styles.cpu]
all_entry_color = "#80809f"
avg_entry_color = "#c4726c"
cpu_core_colors = ["#5583cd", "#748a58", "#d1b57c", "#bf8f62", "#897ea6", "#558ba1", "#5f8b83", "#d35f5f"]

[styles.memory]
ram_color = "#748a58"
cache_color = "#5f8b83"
swap_color = "#bf8f62"
arc_color = "#558ba1"

[styles.network]
rx_color = "#748a58"
tx_color = "#c4726c"
rx_total_color = "#748b55"
tx_total_color = "#c06c65"

[styles.battery]
high_battery_color = "#748a58"
medium_battery_color = "#d1b57c"
low_battery_color = "#d35f5f"

[styles.tables]
headers = { color = "#5583cd", bold = true }

[styles.graphs]
graph_color = "#4e4e73"
legend_text = "#80809f"

[styles.widgets]
border_color = "#202127"
selected_border_color = "#4e6a9c"
widget_title = { color = "#8080a0", bold = true }
text = "#80809f"
selected_text = { color = "#ffffff", bg_color = "#4e6a9c" }
disabled_text = "#8181b2"
