# Lvim Colorscheme BaseDark

[styles.cpu]
all_entry_color = "#629393"
avg_entry_color = "#de684e"
cpu_core_colors = ["#3e92c5", "#7e965a", "#d8b36f", "#e19556", "#3392d2", "#3b9986", "#4097aa", "#e1655a"]

[styles.memory]
ram_color = "#7e965a"
cache_color = "#4097aa"
swap_color = "#e19556"
arc_color = "#3b9986"

[styles.network]
rx_color = "#7e965a"
tx_color = "#de684e"
rx_total_color = "#7b9452"
tx_total_color = "#e36245"

[styles.battery]
high_battery_color = "#7e965a"
medium_battery_color = "#d8b36f"
low_battery_color = "#e1655a"

[styles.tables]
headers = { color = "#3e92c5", bold = true }

[styles.graphs]
graph_color = "#4d6263"
legend_text = "#539595"

[styles.widgets]
border_color = "#242b2f"
selected_border_color = "#447ca2"
widget_title = { color = "#55a6ab", bold = true }
text = "#629393"
selected_text = { color = "#ffffff", bg_color = "#447ca2" }
disabled_text = "#659395"
