# Lvim Colorscheme LvimLight

[styles.cpu]
all_entry_color = "#5e8888"
avg_entry_color = "#bc533c"
cpu_core_colors = ["#0879a9", "#748c50", "#7e652f", "#a96400", "#1981bd", "#228773", "#01778a", "#ac4135"]

[styles.memory]
ram_color = "#748c50"
cache_color = "#01778a"
swap_color = "#a96400"
arc_color = "#228773"

[styles.network]
rx_color = "#748c50"
tx_color = "#bc533c"
rx_total_color = "#556738"
tx_total_color = "#d15a3f"

[styles.battery]
high_battery_color = "#748c50"
medium_battery_color = "#7e652f"
low_battery_color = "#ac4135"

[styles.tables]
headers = { color = "#0879a9", bold = true }

[styles.graphs]
graph_color = "#789698"
legend_text = "#93b6b6"

[styles.widgets]
border_color = "#eeeeee"
selected_border_color = "#0879a9"
widget_title = { color = "#55a6ab", bold = true }
text = "#5e8888"
selected_text = { color = "#dadada", bg_color = "#0879a9" }
disabled_text = "#789698"
