# Lvim Colorscheme BaseDark

[styles.cpu]
all_entry_color = "#5e8888"
avg_entry_color = "#c6614d"
cpu_core_colors = ["#447ca2", "#7e965a", "#d8b36f", "#e19556", "#40719a", "#407e70", "#448595", "#d75e52"]

[styles.memory]
ram_color = "#7e965a"
cache_color = "#448595"
swap_color = "#e19556"
arc_color = "#407e70"

[styles.network]
rx_color = "#7e965a"
tx_color = "#c6614d"
rx_total_color = "#718650"
tx_total_color = "#b65745"

[styles.battery]
high_battery_color = "#7e965a"
medium_battery_color = "#d8b36f"
low_battery_color = "#d75e52"

[styles.tables]
headers = { color = "#447ca2", bold = true }

[styles.graphs]
graph_color = "#4d6263"
legend_text = "#374646"

[styles.widgets]
border_color = "#242b2f"
selected_border_color = "#447ca2"
widget_title = { color = "#55a6ab", bold = true }
text = "#5e8888"
selected_text = { color = "#1c2327", bg_color = "#447ca2" }
disabled_text = "#4d6263"
