# Lvim Colorscheme NightfoxDark

[styles.cpu]
all_entry_color = "#bcbdbd"
avg_entry_color = "#9a80ae"
cpu_core_colors = ["#6b8ab5", "#7b998a", "#bba76f", "#c88e62", "#937db4", "#66a492", "#69a3a4", "#c46e83"]

[styles.memory]
ram_color = "#7b998a"
cache_color = "#69a3a4"
swap_color = "#c88e62"
arc_color = "#66a492"

[styles.network]
rx_color = "#7b998a"
tx_color = "#9a80ae"
rx_total_color = "#6d9180"
tx_total_color = "#9a7db1"

[styles.battery]
high_battery_color = "#7b998a"
medium_battery_color = "#bba76f"
low_battery_color = "#c46e83"

[styles.tables]
headers = { color = "#6b8ab5", bold = true }

[styles.graphs]
graph_color = "#758292"
legend_text = "#828992"

[styles.widgets]
border_color = "#1d2734"
selected_border_color = "#6885ad"
widget_title = { color = "#bcbcbd", bold = true }
text = "#bcbdbd"
selected_text = { color = "#151f2c", bg_color = "#6988b1" }
disabled_text = "#7b8a9c"
