# Lvim Colorscheme NordLight

[styles.cpu]
all_entry_color = "#5e8888"
avg_entry_color = "#6e5a6b"
cpu_core_colors = ["#596a7c", "#7e8f70", "#8b774e", "#7a564b", "#71687d", "#739190", "#6c919d", "#976065"]

[styles.memory]
ram_color = "#7e8f70"
cache_color = "#6c919d"
swap_color = "#7a564b"
arc_color = "#739190"

[styles.network]
rx_color = "#7e8f70"
tx_color = "#6e5a6b"
rx_total_color = "#5d6d50"
tx_total_color = "#7f667a"

[styles.battery]
high_battery_color = "#7e8f70"
medium_battery_color = "#8b774e"
low_battery_color = "#976065"

[styles.tables]
headers = { color = "#596a7c", bold = true }

[styles.graphs]
graph_color = "#737d95"
legend_text = "#5f646e"

[styles.widgets]
border_color = "#eeeeee"
selected_border_color = "#596a7c"
widget_title = { color = "#55a6ab", bold = true }
text = "#5e8888"
selected_text = { color = "#dadada", bg_color = "#596a7c" }
disabled_text = "#737d95"
