# Lvim Colorscheme GruvboxDarker

[styles.cpu]
all_entry_color = "#928373"
avg_entry_color = "#bb755e"
cpu_core_colors = ["#4c8aaa", "#848846", "#af9e6b", "#c47d54", "#877f98", "#439180", "#5a9162", "#dc5a5a"]

[styles.memory]
ram_color = "#848846"
cache_color = "#5a9162"
swap_color = "#c47d54"
arc_color = "#439180"

[styles.network]
rx_color = "#848846"
tx_color = "#bb755e"
rx_total_color = "#838838"
tx_total_color = "#c36e51"

[styles.battery]
high_battery_color = "#848846"
medium_battery_color = "#af9e6b"
low_battery_color = "#dc5a5a"

[styles.tables]
headers = { color = "#4c8aaa", bold = true }

[styles.graphs]
graph_color = "#64584e"
legend_text = "#94806d"

[styles.widgets]
border_color = "#222120"
selected_border_color = "#497188"
widget_title = { color = "#8d8275", bold = true }
text = "#928373"
selected_text = { color = "#ffffff", bg_color = "#497188" }
disabled_text = "#98806b"
