# Lvim Colorscheme NightfoxDarker

[styles.cpu]
all_entry_color = "#bcbdbd"
avg_entry_color = "#9a80ae"
cpu_core_colors = ["#6885ad", "#7b998a", "#bba76f", "#c88e62", "#8e78af", "#66a492", "#69a3a4", "#bf687e"]

[styles.memory]
ram_color = "#7b998a"
cache_color = "#69a3a4"
swap_color = "#c88e62"
arc_color = "#66a492"

[styles.network]
rx_color = "#7b998a"
tx_color = "#9a80ae"
rx_total_color = "#6a8b7b"
tx_total_color = "#9578ac"

[styles.battery]
high_battery_color = "#7b998a"
medium_battery_color = "#bba76f"
low_battery_color = "#bf687e"

[styles.tables]
headers = { color = "#6885ad", bold = true }

[styles.graphs]
graph_color = "#758292"
legend_text = "#7d848c"

[styles.widgets]
border_color = "#18202a"
selected_border_color = "#6885ad"
widget_title = { color = "#bcbcbd", bold = true }
text = "#bcbdbd"
selected_text = { color = "#101822", bg_color = "#6885ad" }
disabled_text = "#778595"
