# Lvim Colorscheme TokyonightDark

[styles.cpu]
all_entry_color = "#b2b6c7"
avg_entry_color = "#907bba"
cpu_core_colors = ["#6c85c1", "#7a8d68", "#b79d7b", "#bb866d", "#8f7eac", "#619085", "#688aa4", "#c86b7b"]

[styles.memory]
ram_color = "#7a8d68"
cache_color = "#688aa4"
swap_color = "#bb866d"
arc_color = "#619085"

[styles.network]
rx_color = "#7a8d68"
tx_color = "#907bba"
rx_total_color = "#758c5f"
tx_total_color = "#917bc1"

[styles.battery]
high_battery_color = "#7a8d68"
medium_battery_color = "#b79d7b"
low_battery_color = "#c86b7b"

[styles.tables]
headers = { color = "#6c85c1", bold = true }

[styles.graphs]
graph_color = "#616784"
legend_text = "#7f859f"

[styles.widgets]
border_color = "#21242c"
selected_border_color = "#6073a4"
widget_title = { color = "#b5b9ca", bold = true }
text = "#b2b6c7"
selected_text = { color = "#ffffff", bg_color = "#6073a4" }
disabled_text = "#7d85a9"
