[colors.primary]
background = "#16171e"
foreground = "#b2b7c7"

[colors.cursor]
text = "#14151c"
cursor = "#6b8d69"

[colors.selection]
text = "#b2b7c7"
background = "#1a1b22"

[colors.normal]
black = "#13141a"
red = "#b7657a"
green = "#6b8d69"
yellow = "#b8a47e"
blue = "#546891"
magenta = "#b976a7"
cyan = "#65878e"
white = "#6a6e7d"

[colors.bright]
black = "#26272f"
red = "#d86685"
green = "#649f5f"
yellow = "#ceb06f"
blue = "#4f74b5"
magenta = "#d57abe"
cyan = "#5b97a2"
white = "#7c8296"