[colors.primary]
background = "#17212e"
foreground = "#bcbdbd"

[colors.cursor]
text = "#151f2c"
cursor = "#7b998a"

[colors.selection]
text = "#bcbdbd"
background = "#1b2532"

[colors.normal]
black = "#141c26"
red = "#b26377"
green = "#7b998a"
yellow = "#bba76f"
blue = "#5677a3"
magenta = "#9a80ae"
cyan = "#69a3a4"
white = "#737474"

[colors.bright]
black = "#28313c"
red = "#d66182"
green = "#72ab90"
yellow = "#d0b459"
blue = "#4a85c6"
magenta = "#af87cc"
cyan = "#56b5b6"
white = "#878888"