[colors.primary]
background = "#24252b"
foreground = "#a0a0bc"

[colors.cursor]
text = "#222329"
cursor = "#6c7f54"

[colors.selection]
text = "#54546d"
background = "#28292f"

[colors.normal]
black = "#1e1f24"
red = "#ba5454"
green = "#6c7f54"
yellow = "#d1b57c"
blue = "#496291"
magenta = "#c4726c"
cyan = "#587a74"
white = "#62627e"

[colors.bright]
black = "#30313a"
red = "#e14c4c"
green = "#728f48"
yellow = "#e8c165"
blue = "#406eb5"
magenta = "#dd7a72"
cyan = "#4f8a81"
white = "#6c6c89"