[colors.primary]
background = "#10161e"
foreground = "#bcbdbd"

[colors.cursor]
text = "#0e131a"
cursor = "#89aa9a"

[colors.selection]
text = "#bcbdbd"
background = "#1c2736"

[colors.normal]
black = "#10161e"
red = "#b46478"
green = "#89aa9a"
yellow = "#c1ac71"
blue = "#5f84b4"
magenta = "#9b82af"
cyan = "#75bbbd"
white = "#b1b5bc"

[colors.bright]
black = "#2b3b51"
red = "#d76383"
green = "#7ebda0"
yellow = "#d6b95a"
blue = "#5192d8"
magenta = "#b08acd"
cyan = "#5cced0"
white = "#bcbdbd"