[colors.primary]
background = "#002934"
foreground = "#9da4a4"

[colors.cursor]
text = "#002732"
cursor = "#727c3e"

[colors.selection]
text = "#9da4a4"
background = "#022d38"

[colors.normal]
black = "#00222b"
red = "#c24f4d"
green = "#727c3e"
yellow = "#9f8549"
blue = "#477193"
magenta = "#c0578a"
cyan = "#4b8580"
white = "#636666"

[colors.bright]
black = "#10353f"
red = "#ea4440"
green = "#7d8b25"
yellow = "#b4912e"
blue = "#3680b0"
magenta = "#e64d9d"
cyan = "#37968f"
white = "#6c7070"