[colors.primary]
background = "#1a2023"
foreground = "#68a8a8"

[colors.cursor]
text = "#181e21"
cursor = "#7e965a"

[colors.selection]
text = "#5e8888"
background = "#1e2427"

[colors.normal]
black = "#161b1e"
red = "#d75e52"
green = "#7e965a"
yellow = "#d8b36f"
blue = "#3b6d8d"
magenta = "#c6614d"
cyan = "#448595"
white = "#4d6464"

[colors.bright]
black = "#222e30"
red = "#f06455"
green = "#84a647"
yellow = "#f0bf51"
blue = "#237ca8"
magenta = "#ea5f3a"
cyan = "#2595ab"
white = "#536f6f"