[colors.primary]
background = "#1b2023"
foreground = "#5a6158"

[colors.cursor]
text = "#161b1d"
cursor = "#75783a"

[colors.selection]
text = "#5a6158"
background = "#242a2f"

[colors.normal]
black = "#191e21"
red = "#cb4f4f"
green = "#75783a"
yellow = "#af9e6b"
blue = "#3a6479"
magenta = "#bb755e"
cyan = "#527a57"
white = "#555c53"

[colors.bright]
black = "#7a8478"
red = "#eb4d4d"
green = "#82861f"
yellow = "#c3ab58"
blue = "#2a7390"
magenta = "#dd7950"
cyan = "#488b52"
white = "#5a6158"