[colors.primary]
background = "#191a21"
foreground = "#c7c7b3"

[colors.cursor]
text = "#15161c"
cursor = "#58d879"

[colors.selection]
text = "#c7c7b3"
background = "#252731"

[colors.normal]
black = "#17191f"
red = "#dd5757"
green = "#58d879"
yellow = "#d0da68"
blue = "#4dc0d8"
magenta = "#dc61a8"
cyan = "#61dfca"
white = "#919186"

[colors.bright]
black = "#2a2b30"
red = "#f16161"
green = "#0eed68"
yellow = "#ddea2f"
blue = "#00d2f0"
magenta = "#f269b8"
cyan = "#07f3d8"
white = "#a6a698"