[colors.primary]
background = "#272934"
foreground = "#c7c7b3"

[colors.cursor]
text = "#252732"
cursor = "#62966d"

[colors.selection]
text = "#c7c7b3"
background = "#2b2d38"

[colors.normal]
black = "#21222b"
red = "#bc6060"
green = "#62966d"
yellow = "#adb27e"
blue = "#597c86"
magenta = "#bf6f9a"
cyan = "#66938a"
white = "#7c7c74"

[colors.bright]
black = "#373941"
red = "#da6262"
green = "#54a869"
yellow = "#bac26c"
blue = "#4f8c9b"
magenta = "#da73ac"
cyan = "#59a597"
white = "#919186"