[colors.primary]
background = "#00323f"
foreground = "#a7afaf"

[colors.cursor]
text = "#00303d"
cursor = "#727c3e"

[colors.selection]
text = "#9da4a4"
background = "#023643"

[colors.normal]
black = "#002a34"
red = "#c24f4d"
green = "#727c3e"
yellow = "#9f8549"
blue = "#477193"
magenta = "#c0578a"
cyan = "#4b8580"
white = "#747878"

[colors.bright]
black = "#113f4a"
red = "#ea4440"
green = "#7d8b25"
yellow = "#b4912e"
blue = "#3680b0"
magenta = "#e64d9d"
cyan = "#37968f"
white = "#767a7a"