# Palette fragment — appended after prompt.toml by clipack's config.sh.
# Not a complete starship configuration.
[palettes.lvim]
teal_dark = "#588b7e"
cyan_dark = "#6287a4"
yellow_dark = "#ad9170"
green_dark = "#73895e"
red_dark = "#cb6172"
orange_dark = "#ad7862"
purple_dark = "#8d79b0"
magenta_dark = "#8c76bc"
blue_dark = "#6480c6"
lua = "#51A0CF"
python = "#FFBC03"
ruby = "#ff2529"
nodejs = "#89E051"
golang = "#519ABA"
java = "#ed454c"
rust = "#DEA584"
php = "#A074C4"
elixir = "#A074C4"
swift = "#E37933"
kotlin = "#8a66ff"
gradle = "#008cc4"
crystal = "#C8C8C8"
nim = "#F3D400"
dart = "#0085e8"
erlang = "#e62bbc"
haskell = "#A074C4"
c = "#599EFF"
shell = "#89E051"
ocaml = "#E37933"
scala = "#ed454c"
perl = "#519ABA"
haxe = "#EA8220"