# Palette fragment — appended after prompt.toml by clipack's config.sh.
# Not a complete starship configuration.
[palettes.lvim]
teal_dark = "#496774"
cyan_dark = "#526763"
yellow_dark = "#6f6045"
green_dark = "#5b674c"
red_dark = "#964b4b"
orange_dark = "#785e49"
purple_dark = "#665f79"
magenta_dark = "#8f524e"
blue_dark = "#526284"
lua = "#49667c"
python = "#735e42"
ruby = "#701516"
nodejs = "#516848"
golang = "#476575"
java = "#ac3d41"
rust = "#735d52"
php = "#73548c"
elixir = "#73548c"
swift = "#8b563d"
kotlin = "#6b3fe0"
gradle = "#005F87"
crystal = "#626262"
nim = "#696143"
dart = "#03589C"
erlang = "#9e3a83"
haskell = "#73548c"
c = "#426399"
shell = "#516848"
ocaml = "#8b563d"
scala = "#ac3d41"
perl = "#476575"
haxe = "#87573b"