# Palette fragment — appended after prompt.toml by clipack's config.sh.
# Not a complete starship configuration.
[palettes.lvim]
teal_dark = "#009e88"
cyan_dark = "#569a5e"
yellow_dark = "#a6935a"
green_dark = "#8e9300"
red_dark = "#f55252"
orange_dark = "#ce7637"
purple_dark = "#9289a5"
magenta_dark = "#d3724e"
blue_dark = "#1e97c1"
lua = "#51A0CF"
python = "#FFBC03"
ruby = "#ff4b4d"
nodejs = "#89E051"
golang = "#519ABA"
java = "#f2545a"
rust = "#DEA584"
php = "#a579c9"
elixir = "#a579c9"
swift = "#E37933"
kotlin = "#9375ff"
gradle = "#0097d3"
crystal = "#C8C8C8"
nim = "#F3D400"
dart = "#0090fa"
erlang = "#fd1cce"
haskell = "#a579c9"
c = "#599EFF"
shell = "#89E051"
ocaml = "#E37933"
scala = "#f2545a"
perl = "#519ABA"
haxe = "#EA8220"