# Palette fragment — appended after prompt.toml by clipack's config.sh.
# Not a complete starship configuration.
[palettes.lvim]
teal_dark = "#4c798b"
cyan_dark = "#52716b"
yellow_dark = "#cbae75"
green_dark = "#64754e"
red_dark = "#b34b4b"
orange_dark = "#b7875b"
purple_dark = "#695e82"
magenta_dark = "#bc6a64"
blue_dark = "#496291"
lua = "#51A0CF"
python = "#FFBC03"
ruby = "#701516"
nodejs = "#89E051"
golang = "#519ABA"
java = "#CC3E44"
rust = "#DEA584"
php = "#A074C4"
elixir = "#A074C4"
swift = "#E37933"
kotlin = "#7F52FF"
gradle = "#005F87"
crystal = "#C8C8C8"
nim = "#F3D400"
dart = "#03589C"
erlang = "#B83998"
haskell = "#A074C4"
c = "#599EFF"
shell = "#89E051"
ocaml = "#E37933"
scala = "#CC3E44"
perl = "#519ABA"
haxe = "#EA8220"