# Palette fragment — appended after prompt.toml by clipack's config.sh.
# Not a complete starship configuration.
[palettes.lvim]
teal_dark = "#309381"
cyan_dark = "#54915c"
yellow_dark = "#a5935f"
green_dark = "#838838"
red_dark = "#e74d4d"
orange_dark = "#b9744b"
purple_dark = "#887e9b"
magenta_dark = "#c36e51"
blue_dark = "#3d8caf"
lua = "#51A0CF"
python = "#FFBC03"
ruby = "#ff2529"
nodejs = "#89E051"
golang = "#519ABA"
java = "#ed454c"
rust = "#DEA584"
php = "#A074C4"
elixir = "#A074C4"
swift = "#E37933"
kotlin = "#8c6aff"
gradle = "#008cc4"
crystal = "#C8C8C8"
nim = "#F3D400"
dart = "#0085e8"
erlang = "#ec27c0"
haskell = "#A074C4"
c = "#599EFF"
shell = "#89E051"
ocaml = "#E37933"
scala = "#ed454c"
perl = "#519ABA"
haxe = "#EA8220"