# Palette fragment — appended after prompt.toml by clipack's config.sh.
# Not a complete starship configuration.
[palettes.lvim]
teal_dark = "#479e8d"
cyan_dark = "#67976d"
yellow_dark = "#998853"
green_dark = "#8a8e46"
red_dark = "#e44a4a"
orange_dark = "#a05e33"
purple_dark = "#9f9aa9"
magenta_dark = "#a96047"
blue_dark = "#5b97b6"
lua = "#51A0CF"
python = "#FFBC03"
ruby = "#701516"
nodejs = "#89E051"
golang = "#519ABA"
java = "#CC3E44"
rust = "#DEA584"
php = "#A074C4"
elixir = "#A074C4"
swift = "#E37933"
kotlin = "#7F52FF"
gradle = "#005F87"
crystal = "#C8C8C8"
nim = "#F3D400"
dart = "#03589C"
erlang = "#B83998"
haskell = "#A074C4"
c = "#599EFF"
shell = "#89E051"
ocaml = "#E37933"
scala = "#CC3E44"
perl = "#519ABA"
haxe = "#EA8220"