# Palette fragment — appended after prompt.toml by clipack's config.sh.
# Not a complete starship configuration.
[palettes.lvim]
teal_dark = "#68897e"
cyan_dark = "#748787"
yellow_dark = "#ac9682"
green_dark = "#718875"
red_dark = "#b07280"
orange_dark = "#9d7978"
purple_dark = "#83808f"
magenta_dark = "#8b7d9f"
blue_dark = "#6a8690"
lua = "#51A0CF"
python = "#FFBC03"
ruby = "#ff2529"
nodejs = "#89E051"
golang = "#519ABA"
java = "#ed454c"
rust = "#DEA584"
php = "#A074C4"
elixir = "#A074C4"
swift = "#E37933"
kotlin = "#8a66ff"
gradle = "#008cc4"
crystal = "#C8C8C8"
nim = "#F3D400"
dart = "#0085e8"
erlang = "#e62bbc"
haskell = "#A074C4"
c = "#599EFF"
shell = "#89E051"
ocaml = "#E37933"
scala = "#ed454c"
perl = "#519ABA"
haxe = "#EA8220"