"$schema" = "https://starship.rs/config-schema.json"

add_newline = true

format = "$all$username$time$character"

[memory_usage]
format = "[󰍛 ${ram}]($style) "
disabled = false
threshold = -1
symbol = "󰍛 "
style = "bold #1c7060"

[time]
format = "[$time]($style) "
time_format = "%T"
style = "bold #01798d"
disabled = false

[username]
format = "[](#eab749) [$user]($style) "
disabled = false
show_always = true
style_user = "#7d9654 bold"
style_root = "#e34a39 bold"

[character]
success_symbol = "[ ](bold #7d9654)"
error_symbol = "[ ](bold #e34a39)"
vimcmd_replace_one_symbol = "[ ](bold ${orange_dark_dark})"
vimcmd_replace_symbol = "[ ](bold #ff9010)"
vimcmd_symbol = "[ ](bold dimmed #7d9654)"
vimcmd_visual_symbol = "[ ](bold dimmed #7d9654)"

[directory]
truncation_length = 3
truncate_to_repo = false
truncation_symbol = " …/"
home_symbol = " "
style = "bold #146b9c"
read_only_style = "bold #e34a39"

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = " "
style = "bold #eab749"

[git_commit]
format = '[ $hash$tag]($style) '
commit_hash_length = 7
style = "bold #b84e36"

[git_status]
format = '([](#eab749) [$all_status$ahead_behind]($style)[](#eab749) )'
ahead = " "
behind = " "
diverged = " "
untracked = " "
stashed = " "
modified = " "
staged = " "
conflicted = " "

[hostname]
ssh_only = true
style = "bold dimmed #7d9654"

[jobs]
symbol = "✦ "
style = "bold #0974a1"

[line_break]
disabled = false

[cmd_duration]
format = '[$duration]($style)'
min_time = 500
show_milliseconds = true
style = "bold #e34a39"

[package]
format = '[ $version](bold #ff9010) '

[lua]
format = '[󰢱 $version]($style) '
style = "bold #51A0CF"

[python]
format = '[ $version]($style) '
style = "bold #FFBC03"

[ruby]
format = '[ $version]($style) '
style = "bold #701516"

[nodejs]
format = '[ $version]($style) '
style = "bold #89E051"

[golang]
format = '[ $version]($style) '
style = "bold #519ABA"

[java]
format = '[ $version]($style) '
style = "bold #CC3E44"

[rust]
format = '[ $version]($style) '
style = "bold #DEA584"

[php]
format = '[ $version]($style) '
style = "bold #A074C4"

[elixir]
format = '[ $version]($style) '
style = "bold #A074C4"

[swift]
format = '[ $version]($style) '
style = "bold #E37933"

[kotlin]
format = '[ $version]($style) '
style = "bold #7F52FF"

[gradle]
format = '[ $version]($style) '
style = "bold #005F87"

[crystal]
format = '[ $version]($style) '
style = "bold #C8C8C8"

[nim]
format = '[ $version]($style) '
style = "bold #F3D400"

[dart]
format = '[ $version]($style) '
style = "bold #03589C"

[erlang]
format = '[ $version]$style) '
style = "bold #B83998"

[haskell]
format = '[ $version]($style) '
style = "bold #A074C4"

[c]
format = '[ $version]($style) '
style = "bold #599EFF"

[shell]
format = '[ $version]($style) '
style = "bold #89E051"

[ocaml]
format = '[ $version]($style) '
style = "bold #E37933"

[scala]
format = '[ $version]($style) '
style = "bold #CC3E44"

[perl]
format = '[ $version]($style) '
style = "bold #519ABA"

[haxe]
format = '[ $version]($style) '
style = "bold #EA8220"
    