# Palette fragment — appended after prompt.toml by clipack's config.sh.
# Not a complete starship configuration.
[palettes.lvim]
teal_dark = "#7b958d"
cyan_dark = "#6a7a7a"
yellow_dark = "#958270"
green_dark = "#677b6b"
red_dark = "#a36e7a"
orange_dark = "#846564"
purple_dark = "#8c8995"
magenta_dark = "#7b6d90"
blue_dark = "#7e949d"
lua = "#51A0CF"
python = "#FFBC03"
ruby = "#701516"
nodejs = "#89E051"
golang = "#519ABA"
java = "#CC3E44"
rust = "#DEA584"
php = "#A074C4"
elixir = "#A074C4"
swift = "#E37933"
kotlin = "#7F52FF"
gradle = "#005F87"
crystal = "#C8C8C8"
nim = "#F3D400"
dart = "#03589C"
erlang = "#B83998"
haskell = "#A074C4"
c = "#599EFF"
shell = "#89E051"
ocaml = "#E37933"
scala = "#CC3E44"
perl = "#519ABA"
haxe = "#EA8220"