# Palette fragment — appended after prompt.toml by clipack's config.sh.
# Not a complete starship configuration.
[palettes.lvim]
teal_dark = "#4b869b"
cyan_dark = "#55756f"
yellow_dark = "#debe7e"
green_dark = "#697b52"
red_dark = "#b24b4b"
orange_dark = "#c68f58"
purple_dark = "#71678a"
magenta_dark = "#c16d67"
blue_dark = "#4a6494"
lua = "#51A0CF"
python = "#FFBC03"
ruby = "#701516"
nodejs = "#89E051"
golang = "#519ABA"
java = "#CC3E44"
rust = "#DEA584"
php = "#A074C4"
elixir = "#A074C4"
swift = "#E37933"
kotlin = "#7F52FF"
gradle = "#005F87"
crystal = "#C8C8C8"
nim = "#F3D400"
dart = "#03589C"
erlang = "#B83998"
haskell = "#A074C4"
c = "#599EFF"
shell = "#89E051"
ocaml = "#E37933"
scala = "#CC3E44"
perl = "#519ABA"
haxe = "#EA8220"