# Palette fragment — appended after prompt.toml by clipack's config.sh.
# Not a complete starship configuration.
[palettes.lvim]
teal_dark = "#4a6962"
cyan_dark = "#4f6752"
yellow_dark = "#696048"
green_dark = "#626446"
red_dark = "#a04747"
orange_dark = "#86573e"
purple_dark = "#64606d"
magenta_dark = "#8a5544"
blue_dark = "#4f6674"
lua = "#49667c"
python = "#735e42"
ruby = "#701516"
nodejs = "#516848"
golang = "#476575"
java = "#ac3d41"
rust = "#735d52"
php = "#73548c"
elixir = "#73548c"
swift = "#8b563d"
kotlin = "#6b3fe0"
gradle = "#005F87"
crystal = "#626262"
nim = "#696143"
dart = "#03589C"
erlang = "#9e3a83"
haskell = "#73548c"
c = "#426399"
shell = "#516848"
ocaml = "#8b563d"
scala = "#ac3d41"
perl = "#476575"
haxe = "#87573b"