# Palette fragment — appended after prompt.toml by clipack's config.sh.
# Not a complete starship configuration.
[palettes.lvim]
teal_dark = "#00a48e"
cyan_dark = "#57a060"
yellow_dark = "#a6935a"
green_dark = "#909600"
red_dark = "#f75c5c"
orange_dark = "#d77a34"
purple_dark = "#958ba8"
magenta_dark = "#dc754e"
blue_dark = "#0b9dc9"
lua = "#51A0CF"
python = "#FFBC03"
ruby = "#ff5253"
nodejs = "#89E051"
golang = "#519ABA"
java = "#f45d62"
rust = "#DEA584"
php = "#aa7fce"
elixir = "#aa7fce"
swift = "#E37933"
kotlin = "#987cff"
gradle = "#0099d7"
crystal = "#C8C8C8"
nim = "#F3D400"
dart = "#0092fe"
erlang = "#ff34d1"
haskell = "#aa7fce"
c = "#599EFF"
shell = "#89E051"
ocaml = "#E37933"
scala = "#f45d62"
perl = "#519ABA"
haxe = "#EA8220"