background = #dfdfdf
foreground = #5e8888
cursor-color = #748c50
cursor-text = #dadada
selection-background = #e9e9e9
selection-foreground = #5e8888

palette = 0=#b6b6b6
palette = 1=#ac4135
palette = 2=#748c50
palette = 3=#7e652f
palette = 4=#0d8abf
palette = 5=#bc533c
palette = 6=#01778a
palette = 7=#3c7478
palette = 8=#2a9b86
palette = 9=#cf3a21
palette = 10=#7a9c3d
palette = 11=#91700f
palette = 12=#0098d2
palette = 13=#de5123
palette = 14=#00859a
palette = 15=#5e8888