background = #dfdfdf
foreground = #5e8888
cursor-color = #707c19
cursor-text = #dadada
selection-background = #e9e9e9
selection-foreground = #5e8888

palette = 0=#b6b6b6
palette = 1=#cc5452
palette = 2=#707c19
palette = 3=#896f1c
palette = 4=#407fac
palette = 5=#bd5588
palette = 6=#347873
palette = 7=#3c7478
palette = 8=#36cbef
palette = 9=#ea5552
palette = 10=#7c8a00
palette = 11=#9a7b00
palette = 12=#168ecb
palette = 13=#e6479c
palette = 14=#0d8882
palette = 15=#5e8888