background = #00323f
foreground = #a7afaf
cursor-color = #727c3e
cursor-text = #00303d
selection-background = #023643
selection-foreground = #a7afaf

palette = 0=#002a34
palette = 1=#c24f4d
palette = 2=#727c3e
palette = 3=#9f8549
palette = 4=#477193
palette = 5=#c0578a
palette = 6=#4b8580
palette = 7=#747878
palette = 8=#113f4a
palette = 9=#ea4440
palette = 10=#7d8b25
palette = 11=#b4912e
palette = 12=#3680b0
palette = 13=#e64d9d
palette = 14=#37968f
palette = 15=#767a7a