background = #dfdfdf
foreground = #425353
cursor-color = #466d4e
cursor-text = #dadada
selection-background = #e9e9e9
selection-foreground = #425353

palette = 0=#b6b6b6
palette = 1=#af5959
palette = 2=#466d4e
palette = 3=#777b56
palette = 4=#5a7d87
palette = 5=#905274
palette = 6=#496b64
palette = 7=#619494
palette = 8=#cfd1d1
palette = 9=#d95151
palette = 10=#3d7e4c
palette = 11=#83894b
palette = 12=#508d9c
palette = 13=#b44d8a
palette = 14=#417b70
palette = 15=#5d8989