background = #dfdfdf
foreground = #425353
cursor-color = #606f52
cursor-text = #dadada
selection-background = #e9e9e9
selection-foreground = #425353

palette = 0=#b6b6b6
palette = 1=#ab5867
palette = 2=#606f52
palette = 3=#927d61
palette = 4=#7487bd
palette = 5=#765ba6
palette = 6=#587387
palette = 7=#619494
palette = 8=#cfd1d1
palette = 9=#d4506d
palette = 10=#657e4b
palette = 11=#a88857
palette = 12=#7994d9
palette = 13=#8860ca
palette = 14=#5182a1
palette = 15=#5d8989