background = #dfdfdf
foreground = #425353
cursor-color = #697b51
cursor-text = #dadada
selection-background = #e9e9e9
selection-foreground = #425353

palette = 0=#b6b6b6
palette = 1=#c35959
palette = 2=#697b51
palette = 3=#816f4a
palette = 4=#6c8dcc
palette = 5=#94544f
palette = 6=#5e827b
palette = 7=#619494
palette = 8=#cfd1d1
palette = 9=#e25a5a
palette = 10=#6f8b45
palette = 11=#947b3d
palette = 12=#709ae6
palette = 13=#b85349
palette = 14=#549388
palette = 15=#5d8989