background = #1c1c2c
foreground = #b2b7c7
cursor-color = #84c27f
cursor-text = #151522
selection-background = #2e2f40
selection-foreground = #b2b7c7

palette = 0=#1b1b2a
palette = 1=#d36d89
palette = 2=#84c27f
palette = 3=#d8b973
palette = 4=#5082d4
palette = 5=#d07fba
palette = 6=#71becc
palette = 7=#9b9eaa
palette = 8=#4a4d5e
palette = 9=#e97596
palette = 10=#75d66b
palette = 11=#efc655
palette = 12=#458ff6
palette = 13=#e787cd
palette = 14=#53d0e4
palette = 15=#b2b7c7