background = #002d39
foreground = #9da4a4
cursor-color = #727f1a
cursor-text = #002832
selection-background = #084452
selection-foreground = #9da4a4

palette = 0=#002a34
palette = 1=#bf4e4c
palette = 2=#727f1a
palette = 3=#96791f
palette = 4=#3d7aa5
palette = 5=#b75283
palette = 6=#3e8d87
palette = 7=#6c777b
palette = 8=#0a3f4c
palette = 9=#e7433f
palette = 10=#7e8d00
palette = 11=#a78500
palette = 12=#1589c3
palette = 13=#df4597
palette = 14=#109e96
palette = 15=#9da4a4