background = #242134
foreground = #b4b2c7
cursor-color = #83b2ba
cursor-text = #141321
selection-background = #2d2a3b
selection-foreground = #b4b2c7

palette = 0=#181622
palette = 1=#cd6985
palette = 2=#83b2ba
palette = 3=#d6a765
palette = 4=#3b6374
palette = 5=#9f80c4
palette = 6=#83b2ba
palette = 7=#9694a3
palette = 8=#312f44
palette = 9=#e57091
palette = 10=#74c4d0
palette = 11=#f0b246
palette = 12=#2d728a
palette = 13=#b189df
palette = 14=#74c4d0
palette = 15=#b4b2c7