background = #dfdfdf
foreground = #425353
cursor-color = #7e8f70
cursor-text = #dadada
selection-background = #e9e9e9
selection-foreground = #425353

palette = 0=#b6b6b6
palette = 1=#976065
palette = 2=#7e8f70
palette = 3=#8b774e
palette = 4=#60788f
palette = 5=#6e5a6b
palette = 6=#6c919d
palette = 7=#619494
palette = 8=#cfd1d1
palette = 9=#c15c67
palette = 10=#82a067
palette = 11=#9f833f
palette = 12=#5a87ac
palette = 13=#8e5c87
palette = 14=#61a1b4
palette = 15=#5d8989