background = #242b2f
foreground = #6bb4b4
cursor-color = #7e965a
cursor-text = #22292d
selection-background = #282f33
selection-foreground = #6bb4b4

palette = 0=#1e2427
palette = 1=#d75e52
palette = 2=#7e965a
palette = 3=#d8b36f
palette = 4=#3b6d8d
palette = 5=#c6614d
palette = 6=#448595
palette = 7=#587979
palette = 8=#2b393c
palette = 9=#f06455
palette = 10=#84a647
palette = 11=#f0bf51
palette = 12=#237ca8
palette = 13=#ea5f3a
palette = 14=#2595ab
palette = 15=#587a7a