background = #dfdfdf
foreground = #425353
cursor-color = #727c3e
cursor-text = #dadada
selection-background = #e9e9e9
selection-foreground = #425353

palette = 0=#b6b6b6
palette = 1=#ca5350
palette = 2=#727c3e
palette = 3=#786435
palette = 4=#5586ae
palette = 5=#b35181
palette = 6=#467c77
palette = 7=#619494
palette = 8=#cfd1d1
palette = 9=#eb514c
palette = 10=#7d8b25
palette = 11=#8b7020
palette = 12=#4195cd
palette = 13=#da4595
palette = 14=#348d85
palette = 15=#5d8989