background = #1a2327
foreground = #b2c7c7
cursor-color = #90ad68
cursor-text = #182125
selection-background = #1e272b
selection-foreground = #b2c7c7

palette = 0=#161e21
palette = 1=#d05e64
palette = 2=#90ad68
palette = 3=#cfa96a
palette = 4=#4f6fbb
palette = 5=#d75d70
palette = 6=#65a1bd
palette = 7=#727b7b
palette = 8=#293337
palette = 9=#e6666d
palette = 10=#95be51
palette = 11=#e7b44e
palette = 12=#3e7ae8
palette = 13=#ec667b
palette = 14=#4eb2d9
palette = 15=#849090