# Lvim Colorscheme for Helix

"ui.background" = { bg = "bg_dark" }
"ui.text" = "fg"
"ui.text.focus" = "ui_fg_light"
"ui.cursor" = { fg = "on_green", bg = "strip_green" }
"ui.cursor.primary" = { fg = "on_green", bg = "strip_green" }
"ui.cursorline.primary" = { bg = "bg" }
"ui.selection" = { bg = "bg_visual" }
"ui.linenr" = "ui_fg_dark"
"ui.linenr.selected" = "ui_fg_light"
"ui.statusline" = { fg = "ui_fg", bg = "bg" }
"ui.statusline.inactive" = { fg = "ui_fg_dark", bg = "bg" }
"ui.popup" = { fg = "ui_fg", bg = "bg_float" }
"ui.window" = { fg = "bg_highlight" }
"ui.help" = { fg = "ui_fg", bg = "bg_float" }
"ui.menu" = { fg = "ui_fg", bg = "bg_float" }
"ui.menu.selected" = { fg = "on_blue", bg = "strip_blue" }
"ui.virtual.whitespace" = "bg_highlight"
"ui.virtual.ruler" = { bg = "bg" }
"ui.virtual.inlay-hint" = "comment"

"comment" = { fg = "comment", modifiers = ["italic"] }
"variable" = "fg"
"variable.builtin" = "red"
"variable.parameter" = "fg_light"
"constant" = "orange"
"constant.builtin" = "orange"
"constant.numeric" = "orange"
"string" = "green"
"string.regexp" = "cyan"
"keyword" = "purple"
"keyword.control" = "purple"
"function" = "blue"
"function.builtin" = "blue"
"function.macro" = "cyan"
"type" = "yellow"
"type.builtin" = "yellow"
"constructor" = "yellow"
"operator" = "cyan"
"punctuation" = "fg_dark"
"label" = "red"
"tag" = "red"
"namespace" = "yellow"
"attribute" = "cyan"

"markup.heading" = { fg = "blue", modifiers = ["bold"] }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "cyan", modifiers = ["underlined"] }
"markup.link.text" = "red"
"markup.raw" = "green"

"diff.plus" = "git.add"
"diff.delta" = "git.change"
"diff.minus" = "git.delete"

"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.hint" = { underline = { color = "cyan", style = "curl" } }
"error" = "text_red"
"warning" = "text_yellow"
"info" = "text_blue"
"hint" = "text_cyan"

[palette]
bg_dark = "#101822"
bg = "#141c26"
bg_float = "#101822"
bg_highlight = "#161e28"
bg_visual = "#161e28"
fg = "#bcbdbd"
fg_light = "#bcbcbd"
fg_dark = "#7b8189"
comment = "#758292"
blue = "#6885ad"
cyan = "#69a3a4"
green = "#7b998a"
orange = "#c88e62"
purple = "#8670a7"
red = "#b26377"
yellow = "#bba76f"
"git.add" = "#7b998a"
"git.change" = "#bba76f"
"git.delete" = "#b26377"
ui_fg = "#bcbdbd"
ui_fg_light = "#bcbcbd"
ui_fg_dark = "#80868f"
text_red = "#c26b81"
text_yellow = "#bba76f"
text_blue = "#6988b1"
text_cyan = "#69a3a4"
on_blue = "#101822"
strip_blue = "#6885ad"
on_green = "#101822"
strip_green = "#7b998a"