# Lvim Colorscheme for Helix

"ui.background" = { bg = "bg_dark" }
"ui.text" = "fg"
"ui.text.focus" = "ui_fg_light"
"ui.cursor" = { fg = "on_green", bg = "strip_green" }
"ui.cursor.primary" = { fg = "on_green", bg = "strip_green" }
"ui.cursorline.primary" = { bg = "bg" }
"ui.selection" = { bg = "bg_visual" }
"ui.linenr" = "ui_fg_dark"
"ui.linenr.selected" = "ui_fg_light"
"ui.statusline" = { fg = "ui_fg", bg = "bg" }
"ui.statusline.inactive" = { fg = "ui_fg_dark", bg = "bg" }
"ui.popup" = { fg = "ui_fg", bg = "bg_float" }
"ui.window" = { fg = "bg_highlight" }
"ui.help" = { fg = "ui_fg", bg = "bg_float" }
"ui.menu" = { fg = "ui_fg", bg = "bg_float" }
"ui.menu.selected" = { fg = "on_blue", bg = "strip_blue" }
"ui.virtual.whitespace" = "bg_highlight"
"ui.virtual.ruler" = { bg = "bg" }
"ui.virtual.inlay-hint" = "comment"

"comment" = { fg = "comment", modifiers = ["italic"] }
"variable" = "fg"
"variable.builtin" = "red"
"variable.parameter" = "fg_light"
"constant" = "orange"
"constant.builtin" = "orange"
"constant.numeric" = "orange"
"string" = "green"
"string.regexp" = "cyan"
"keyword" = "purple"
"keyword.control" = "purple"
"function" = "blue"
"function.builtin" = "blue"
"function.macro" = "cyan"
"type" = "yellow"
"type.builtin" = "yellow"
"constructor" = "yellow"
"operator" = "cyan"
"punctuation" = "fg_dark"
"label" = "red"
"tag" = "red"
"namespace" = "yellow"
"attribute" = "cyan"

"markup.heading" = { fg = "blue", modifiers = ["bold"] }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "cyan", modifiers = ["underlined"] }
"markup.link.text" = "red"
"markup.raw" = "green"

"diff.plus" = "git.add"
"diff.delta" = "git.change"
"diff.minus" = "git.delete"

"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.hint" = { underline = { color = "cyan", style = "curl" } }
"error" = "text_red"
"warning" = "text_yellow"
"info" = "text_blue"
"hint" = "text_cyan"

[palette]
bg_dark = "#22292d"
bg = "#262d31"
bg_float = "#22292d"
bg_highlight = "#282f33"
bg_visual = "#282f33"
fg = "#5e8888"
fg_light = "#55a6ab"
fg_dark = "#374646"
comment = "#4d6263"
blue = "#447ca2"
cyan = "#448595"
green = "#7e965a"
orange = "#e19556"
purple = "#40719a"
red = "#d75e52"
yellow = "#d8b36f"
"git.add" = "#7e965a"
"git.change" = "#d8b36f"
"git.delete" = "#d75e52"
ui_fg = "#669f9f"
ui_fg_light = "#55a6ab"
ui_fg_dark = "#54a1a1"
text_red = "#e6756b"
text_yellow = "#d8b36f"
text_blue = "#369ed7"
text_cyan = "#3aa3b9"
on_blue = "#ffffff"
strip_blue = "#447ca2"
on_green = "#22292d"
strip_green = "#80995b"