# Lvim Colorscheme for Helix

"ui.background" = { bg = "bg_dark" }
"ui.text" = "fg"
"ui.text.focus" = "fg_light"
"ui.cursor" = { fg = "bg_dark", bg = "green" }
"ui.cursor.primary" = { fg = "bg_dark", bg = "green" }
"ui.cursorline.primary" = { bg = "bg" }
"ui.selection" = { bg = "bg_visual" }
"ui.linenr" = "fg_dark"
"ui.linenr.selected" = "fg_light"
"ui.statusline" = { fg = "fg", bg = "bg" }
"ui.statusline.inactive" = { fg = "fg_dark", bg = "bg" }
"ui.popup" = { fg = "fg", bg = "bg_float" }
"ui.window" = { fg = "bg_highlight" }
"ui.help" = { fg = "fg", bg = "bg_float" }
"ui.menu" = { fg = "fg", bg = "bg_float" }
"ui.menu.selected" = { fg = "bg_dark", bg = "blue" }
"ui.virtual.whitespace" = "bg_highlight"
"ui.virtual.ruler" = { bg = "bg" }
"ui.virtual.inlay-hint" = "comment"

"comment" = { fg = "comment", modifiers = ["italic"] }
"variable" = "fg"
"variable.builtin" = "red"
"variable.parameter" = "fg_light"
"constant" = "orange"
"constant.builtin" = "orange"
"constant.numeric" = "orange"
"string" = "green"
"string.regexp" = "cyan"
"keyword" = "purple"
"keyword.control" = "purple"
"function" = "blue"
"function.builtin" = "blue"
"function.macro" = "cyan"
"type" = "yellow"
"type.builtin" = "yellow"
"constructor" = "yellow"
"operator" = "cyan"
"punctuation" = "fg_dark"
"label" = "red"
"tag" = "red"
"namespace" = "yellow"
"attribute" = "cyan"

"markup.heading" = { fg = "blue", modifiers = ["bold"] }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "cyan", modifiers = ["underlined"] }
"markup.link.text" = "red"
"markup.raw" = "green"

"diff.plus" = "git.add"
"diff.delta" = "git.change"
"diff.minus" = "git.delete"

"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.hint" = { underline = { color = "cyan", style = "curl" } }
"error" = "red"
"warning" = "yellow"
"info" = "blue"
"hint" = "cyan"

[palette]
bg_dark = "#181820"
bg = "#1f202d"
bg_float = "#181820"
bg_highlight = "#262a3b"
bg_visual = "#262a3b"
fg = "#b2b6c7"
fg_light = "#b5b9ca"
fg_dark = "#5e6274"
comment = "#63677c"
blue = "#6589d7"
cyan = "#60b0de"
green = "#9dbd7b"
orange = "#dd8b5a"
purple = "#9381b3"
red = "#d76479"
yellow = "#c5a06b"
"git.add" = "#9dbd7b"
"git.change" = "#c5a06b"
"git.delete" = "#d76479"