# Lvim Colorscheme for Helix

"ui.background" = { bg = "bg_dark" }
"ui.text" = "fg"
"ui.text.focus" = "ui_fg_light"
"ui.cursor" = { fg = "on_green", bg = "strip_green" }
"ui.cursor.primary" = { fg = "on_green", bg = "strip_green" }
"ui.cursorline.primary" = { bg = "bg" }
"ui.selection" = { bg = "bg_visual" }
"ui.linenr" = "ui_fg_dark"
"ui.linenr.selected" = "ui_fg_light"
"ui.statusline" = { fg = "ui_fg", bg = "bg" }
"ui.statusline.inactive" = { fg = "ui_fg_dark", bg = "bg" }
"ui.popup" = { fg = "ui_fg", bg = "bg_float" }
"ui.window" = { fg = "bg_highlight" }
"ui.help" = { fg = "ui_fg", bg = "bg_float" }
"ui.menu" = { fg = "ui_fg", bg = "bg_float" }
"ui.menu.selected" = { fg = "on_blue", bg = "strip_blue" }
"ui.virtual.whitespace" = "bg_highlight"
"ui.virtual.ruler" = { bg = "bg" }
"ui.virtual.inlay-hint" = "comment"

"comment" = { fg = "comment", modifiers = ["italic"] }
"variable" = "fg"
"variable.builtin" = "red"
"variable.parameter" = "fg_light"
"constant" = "orange"
"constant.builtin" = "orange"
"constant.numeric" = "orange"
"string" = "green"
"string.regexp" = "cyan"
"keyword" = "purple"
"keyword.control" = "purple"
"function" = "blue"
"function.builtin" = "blue"
"function.macro" = "cyan"
"type" = "yellow"
"type.builtin" = "yellow"
"constructor" = "yellow"
"operator" = "cyan"
"punctuation" = "fg_dark"
"label" = "red"
"tag" = "red"
"namespace" = "yellow"
"attribute" = "cyan"

"markup.heading" = { fg = "blue", modifiers = ["bold"] }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "cyan", modifiers = ["underlined"] }
"markup.link.text" = "red"
"markup.raw" = "green"

"diff.plus" = "git.add"
"diff.delta" = "git.change"
"diff.minus" = "git.delete"

"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.hint" = { underline = { color = "cyan", style = "curl" } }
"error" = "text_red"
"warning" = "text_yellow"
"info" = "text_blue"
"hint" = "text_cyan"

[palette]
bg_dark = "#131115"
bg = "#171519"
bg_float = "#131115"
bg_highlight = "#19171b"
bg_visual = "#19171b"
fg = "#b3afb2"
fg_light = "#b9b4b5"
fg_dark = "#757174"
comment = "#896882"
blue = "#5d6d74"
cyan = "#788787"
green = "#788b7c"
orange = "#a98a89"
purple = "#726f7c"
red = "#a0727c"
yellow = "#b6a18b"
"git.add" = "#788b7c"
"git.change" = "#b6a18b"
"git.delete" = "#a0727c"
ui_fg = "#b3afb2"
ui_fg_light = "#b9b4b5"
ui_fg_dark = "#858084"
text_red = "#a4747e"
text_yellow = "#b6a18b"
text_blue = "#6d858f"
text_cyan = "#788787"
on_blue = "#ffffff"
strip_blue = "#5d6d74"
on_green = "#131115"
strip_green = "#788b7c"