# Lvim Colorscheme for Helix

"ui.background" = { bg = "bg_dark" }
"ui.text" = "fg"
"ui.text.focus" = "ui_fg_light"
"ui.cursor" = { fg = "on_green", bg = "strip_green" }
"ui.cursor.primary" = { fg = "on_green", bg = "strip_green" }
"ui.cursorline.primary" = { bg = "bg" }
"ui.selection" = { bg = "bg_visual" }
"ui.linenr" = "ui_fg_dark"
"ui.linenr.selected" = "ui_fg_light"
"ui.statusline" = { fg = "ui_fg", bg = "bg" }
"ui.statusline.inactive" = { fg = "ui_fg_dark", bg = "bg" }
"ui.popup" = { fg = "ui_fg", bg = "bg_float" }
"ui.window" = { fg = "bg_highlight" }
"ui.help" = { fg = "ui_fg", bg = "bg_float" }
"ui.menu" = { fg = "ui_fg", bg = "bg_float" }
"ui.menu.selected" = { fg = "on_blue", bg = "strip_blue" }
"ui.virtual.whitespace" = "bg_highlight"
"ui.virtual.ruler" = { bg = "bg" }
"ui.virtual.inlay-hint" = "comment"

"comment" = { fg = "comment", modifiers = ["italic"] }
"variable" = "fg"
"variable.builtin" = "red"
"variable.parameter" = "fg_light"
"constant" = "orange"
"constant.builtin" = "orange"
"constant.numeric" = "orange"
"string" = "green"
"string.regexp" = "cyan"
"keyword" = "purple"
"keyword.control" = "purple"
"function" = "blue"
"function.builtin" = "blue"
"function.macro" = "cyan"
"type" = "yellow"
"type.builtin" = "yellow"
"constructor" = "yellow"
"operator" = "cyan"
"punctuation" = "fg_dark"
"label" = "red"
"tag" = "red"
"namespace" = "yellow"
"attribute" = "cyan"

"markup.heading" = { fg = "blue", modifiers = ["bold"] }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "cyan", modifiers = ["underlined"] }
"markup.link.text" = "red"
"markup.raw" = "green"

"diff.plus" = "git.add"
"diff.delta" = "git.change"
"diff.minus" = "git.delete"

"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.hint" = { underline = { color = "cyan", style = "curl" } }
"error" = "text_red"
"warning" = "text_yellow"
"info" = "text_blue"
"hint" = "text_cyan"

[palette]
bg_dark = "#202527"
bg = "#292f33"
bg_float = "#202527"
bg_highlight = "#2e3439"
bg_visual = "#2e3439"
fg = "#5a6158"
fg_light = "#646c62"
fg_dark = "#50574e"
comment = "#535d4e"
blue = "#42728b"
cyan = "#527a57"
green = "#75783a"
orange = "#cc7942"
purple = "#635d71"
red = "#cb4f4f"
yellow = "#af9e6b"
"git.add" = "#75783a"
"git.change" = "#af9e6b"
"git.delete" = "#cb4f4f"
ui_fg = "#8fa18a"
ui_fg_light = "#8f9f8b"
ui_fg_dark = "#8ca186"
text_red = "#e97d7d"
text_yellow = "#af9e6b"
text_blue = "#2ba6d4"
text_cyan = "#61ad6c"
on_blue = "#ffffff"
strip_blue = "#42728b"
on_green = "#ffffff"
strip_green = "#75783a"