# Palette for the layout in tmux.conf.
thm_bg="#192330"
thm_bg_dark="#151f2c"
thm_bg_soft_dark="#17212e"
thm_fg="#bcbdbd"
thm_green="#7b998a"
thm_green_dark="#6a8b7b"
thm_red="#b26377"
thm_red_dark="#ab5268"
thm_orange="#c88e62"
thm_orange_dark="#bd8055"
thm_blue_dark="#5677a3"
thm_teal_dark="#5a9887"

set -g mode-style "fg=#17212e,bg=#bd8055"

set -g message-style "fg=#5a9887,bg=#151f2c"

set -g status-style "fg=#5677a3,bg=#151f2c"

setw -g window-status-style "fg=#7b998a,bold,bg=#151f2c"
setw -g window-status-current-style "fg=#17212e,bold,bg=#7b998a"
setw -g window-status-activity-style "fg=#bd8055"

setw -g pane-border-style "fg=#6a8b7b"
setw -g pane-active-border-style "fg=#6a8b7b"

set -g @sysstat_cpu_color_low "#7b998a"
set -g @sysstat_cpu_color_medium "#c88e62"
set -g @sysstat_cpu_color_stress "#ab5268"

set -g @sysstat_mem_color_low "#7b998a"
set -g @sysstat_mem_color_medium "#c88e62"
set -g @sysstat_mem_color_stress "#ab5268"

set -g @prefix_highlight_fg "#b26377,bold"
set -g @prefix_highlight_bg "#17212e"
set -g @prefix_highlight_copy_mode_attr "fg=#b26377,bold,bg=#151f2c"
