# Palette for the layout in tmux.conf.
thm_bg="#E4E4E4"
thm_bg_dark="#dadada"
thm_bg_soft_dark="#dfdfdf"
thm_fg="#5e8888"
thm_green="#557f51"
thm_green_dark="#52884d"
thm_red="#9d445e"
thm_red_dark="#b54c69"
thm_orange="#aa724e"
thm_orange_dark="#bf7546"
thm_blue_dark="#416cb1"
thm_teal_dark="#47847a"

set -g mode-style "fg=#dfdfdf,bg=#bf7546"

set -g message-style "fg=#47847a,bg=#dadada"

set -g status-style "fg=#416cb1,bg=#dadada"

setw -g window-status-style "fg=#557f51,bold,bg=#dadada"
setw -g window-status-current-style "fg=#dfdfdf,bold,bg=#557f51"
setw -g window-status-activity-style "fg=#bf7546"

setw -g pane-border-style "fg=#52884d"
setw -g pane-active-border-style "fg=#52884d"

set -g @sysstat_cpu_color_low "#557f51"
set -g @sysstat_cpu_color_medium "#aa724e"
set -g @sysstat_cpu_color_stress "#b54c69"

set -g @sysstat_mem_color_low "#557f51"
set -g @sysstat_mem_color_medium "#aa724e"
set -g @sysstat_mem_color_stress "#b54c69"

set -g @prefix_highlight_fg "#9d445e,bold"
set -g @prefix_highlight_bg "#dfdfdf"
set -g @prefix_highlight_copy_mode_attr "fg=#9d445e,bold,bg=#dadada"
