# Palette for the layout in tmux.conf.
thm_bg="#001f27"
thm_bg_dark="#001b23"
thm_bg_soft_dark="#001d25"
thm_fg="#9da4a4"
thm_green="#727c3e"
thm_green_dark="#666f37"
thm_red="#c24f4d"
thm_red_dark="#b34644"
thm_orange="#b46548"
thm_orange_dark="#a35b41"
thm_blue_dark="#477193"
thm_teal_dark="#407862"

set -g mode-style "fg=#ffffff,bg=#a35b41"

set -g message-style "fg=#3f9072,bg=#001b23"

set -g status-style "fg=#4887b5,bg=#001b23"

setw -g window-status-style "fg=#7b873d,bold,bg=#001b23"
setw -g window-status-current-style "fg=#ffffff,bold,bg=#70793e"
setw -g window-status-activity-style "fg=#a35b41"

setw -g pane-border-style "fg=#666f37"
setw -g pane-active-border-style "fg=#666f37"

set -g @sysstat_cpu_color_low "#727c3e"
set -g @sysstat_cpu_color_medium "#b46548"
set -g @sysstat_cpu_color_stress "#b34644"

set -g @sysstat_mem_color_low "#727c3e"
set -g @sysstat_mem_color_medium "#b46548"
set -g @sysstat_mem_color_stress "#b34644"

set -g @prefix_highlight_fg "#dd5755,bold"
set -g @prefix_highlight_bg "#001d25"
set -g @prefix_highlight_copy_mode_attr "fg=#dc5351,bold,bg=#001b23"
