# Palette for the layout in tmux.conf.
thm_bg="#292f33"
thm_bg_dark="#202527"
thm_bg_soft_dark="#252a2d"
thm_fg="#5a6158"
thm_green="#75783a"
thm_green_dark="#656831"
thm_red="#cb4f4f"
thm_red_dark="#c53b3b"
thm_orange="#cc7942"
thm_orange_dark="#b86d3c"
thm_blue_dark="#3a6479"
thm_teal_dark="#2d695d"

set -g mode-style "fg=#252a2d,bg=#b86d3c"

set -g message-style "fg=#2d695d,bg=#202527"

set -g status-style "fg=#3a6479,bg=#202527"

setw -g window-status-style "fg=#75783a,bold,bg=#202527"
setw -g window-status-current-style "fg=#252a2d,bold,bg=#75783a"
setw -g window-status-activity-style "fg=#b86d3c"

setw -g pane-border-style "fg=#656831"
setw -g pane-active-border-style "fg=#656831"

set -g @sysstat_cpu_color_low "#75783a"
set -g @sysstat_cpu_color_medium "#cc7942"
set -g @sysstat_cpu_color_stress "#c53b3b"

set -g @sysstat_mem_color_low "#75783a"
set -g @sysstat_mem_color_medium "#cc7942"
set -g @sysstat_mem_color_stress "#c53b3b"

set -g @prefix_highlight_fg "#cb4f4f,bold"
set -g @prefix_highlight_bg "#252a2d"
set -g @prefix_highlight_copy_mode_attr "fg=#cb4f4f,bold,bg=#202527"
