# Palette for the layout in tmux.conf.
thm_bg="#E4E4E4"
thm_bg_dark="#dadada"
thm_bg_soft_dark="#dfdfdf"
thm_fg="#5e8888"
thm_green="#2f7a42"
thm_green_dark="#25803c"
thm_red="#ba4040"
thm_red_dark="#d63f3f"
thm_orange="#9e703f"
thm_orange_dark="#ae7435"
thm_blue_dark="#307f90"
thm_teal_dark="#307f90"

set -g mode-style "fg=#dfdfdf,bg=#ae7435"

set -g message-style "fg=#307f90,bg=#dadada"

set -g status-style "fg=#307f90,bg=#dadada"

setw -g window-status-style "fg=#2f7a42,bold,bg=#dadada"
setw -g window-status-current-style "fg=#dfdfdf,bold,bg=#2f7a42"
setw -g window-status-activity-style "fg=#ae7435"

setw -g pane-border-style "fg=#25803c"
setw -g pane-active-border-style "fg=#25803c"

set -g @sysstat_cpu_color_low "#2f7a42"
set -g @sysstat_cpu_color_medium "#9e703f"
set -g @sysstat_cpu_color_stress "#d63f3f"

set -g @sysstat_mem_color_low "#2f7a42"
set -g @sysstat_mem_color_medium "#9e703f"
set -g @sysstat_mem_color_stress "#d63f3f"

set -g @prefix_highlight_fg "#ba4040,bold"
set -g @prefix_highlight_bg "#dfdfdf"
set -g @prefix_highlight_copy_mode_attr "fg=#ba4040,bold,bg=#dadada"
