# Palette for the layout in tmux.conf.
thm_bg="#202127"
thm_bg_dark="#17181c"
thm_bg_soft_dark="#1b1c21"
thm_fg="#54546d"
thm_green="#6e8156"
thm_green_dark="#697b52"
thm_red="#b65252"
thm_red_dark="#b24b4b"
thm_orange="#c99460"
thm_orange_dark="#c68f58"
thm_blue_dark="#4a6494"
thm_teal_dark="#4b869b"

set -g mode-style "fg=#1b1c21,bg=#c68f58"

set -g message-style "fg=#4b869b,bg=#17181c"

set -g status-style "fg=#4a6494,bg=#17181c"

setw -g window-status-style "fg=#6e8156,bold,bg=#17181c"
setw -g window-status-current-style "fg=#1b1c21,bold,bg=#6e8156"
setw -g window-status-activity-style "fg=#c68f58"

setw -g pane-border-style "fg=#697b52"
setw -g pane-active-border-style "fg=#697b52"

set -g @sysstat_cpu_color_low "#6e8156"
set -g @sysstat_cpu_color_medium "#c99460"
set -g @sysstat_cpu_color_stress "#b24b4b"

set -g @sysstat_mem_color_low "#6e8156"
set -g @sysstat_mem_color_medium "#c99460"
set -g @sysstat_mem_color_stress "#b24b4b"

set -g @prefix_highlight_fg "#b65252,bold"
set -g @prefix_highlight_bg "#1b1c21"
set -g @prefix_highlight_copy_mode_attr "fg=#b65252,bold,bg=#17181c"
