# Palette for the layout in tmux.conf.
thm_bg="#E4E4E4"
thm_bg_dark="#dadada"
thm_bg_soft_dark="#dfdfdf"
thm_fg="#5e8888"
thm_green="#55673c"
thm_green_dark="#637646"
thm_red="#ae4b41"
thm_red_dark="#c54e44"
thm_orange="#aa703f"
thm_orange_dark="#b87342"
thm_blue_dark="#4e8db5"
thm_teal_dark="#4f9987"

set -g mode-style "fg=#dfdfdf,bg=#b87342"

set -g message-style "fg=#4f9987,bg=#dadada"

set -g status-style "fg=#4e8db5,bg=#dadada"

setw -g window-status-style "fg=#55673c,bold,bg=#dadada"
setw -g window-status-current-style "fg=#dfdfdf,bold,bg=#55673c"
setw -g window-status-activity-style "fg=#b87342"

setw -g pane-border-style "fg=#637646"
setw -g pane-active-border-style "fg=#637646"

set -g @sysstat_cpu_color_low "#55673c"
set -g @sysstat_cpu_color_medium "#aa703f"
set -g @sysstat_cpu_color_stress "#c54e44"

set -g @sysstat_mem_color_low "#55673c"
set -g @sysstat_mem_color_medium "#aa703f"
set -g @sysstat_mem_color_stress "#c54e44"

set -g @prefix_highlight_fg "#ae4b41,bold"
set -g @prefix_highlight_bg "#dfdfdf"
set -g @prefix_highlight_copy_mode_attr "fg=#ae4b41,bold,bg=#dadada"
