# Palette for the layout in tmux.conf.
thm_bg="#E4E4E4"
thm_bg_dark="#dadada"
thm_bg_soft_dark="#dfdfdf"
thm_fg="#5e8888"
thm_green="#738366"
thm_green_dark="#788c67"
thm_red="#935d63"
thm_red_dark="#ae656c"
thm_orange="#b27f6f"
thm_orange_dark="#905e4f"
thm_blue_dark="#556a80"
thm_teal_dark="#6a8d8b"

set -g mode-style "fg=#dfdfdf,bg=#905e4f"

set -g message-style "fg=#6a8d8b,bg=#dadada"

set -g status-style "fg=#556a80,bg=#dadada"

setw -g window-status-style "fg=#738366,bold,bg=#dadada"
setw -g window-status-current-style "fg=#dfdfdf,bold,bg=#738366"
setw -g window-status-activity-style "fg=#905e4f"

setw -g pane-border-style "fg=#788c67"
setw -g pane-active-border-style "fg=#788c67"

set -g @sysstat_cpu_color_low "#738366"
set -g @sysstat_cpu_color_medium "#b27f6f"
set -g @sysstat_cpu_color_stress "#ae656c"

set -g @sysstat_mem_color_low "#738366"
set -g @sysstat_mem_color_medium "#b27f6f"
set -g @sysstat_mem_color_stress "#ae656c"

set -g @prefix_highlight_fg "#935d63,bold"
set -g @prefix_highlight_bg "#dfdfdf"
set -g @prefix_highlight_copy_mode_attr "fg=#935d63,bold,bg=#dadada"
