# Palette for the layout in tmux.conf.
thm_bg="#1c1d23"
thm_bg_dark="#18191f"
thm_bg_soft_dark="#1a1b21"
thm_fg="#54546d"
thm_green="#6c7f54"
thm_green_dark="#64754e"
thm_red="#ba5454"
thm_red_dark="#b34b4b"
thm_orange="#bf8f62"
thm_orange_dark="#b7875b"
thm_blue_dark="#496291"
thm_teal_dark="#4c798b"

set -g mode-style "fg=#1a1b21,bg=#b7875b"

set -g message-style "fg=#4c798b,bg=#18191f"

set -g status-style "fg=#496291,bg=#18191f"

setw -g window-status-style "fg=#6c7f54,bold,bg=#18191f"
setw -g window-status-current-style "fg=#1a1b21,bold,bg=#6c7f54"
setw -g window-status-activity-style "fg=#b7875b"

setw -g pane-border-style "fg=#64754e"
setw -g pane-active-border-style "fg=#64754e"

set -g @sysstat_cpu_color_low "#6c7f54"
set -g @sysstat_cpu_color_medium "#bf8f62"
set -g @sysstat_cpu_color_stress "#b34b4b"

set -g @sysstat_mem_color_low "#6c7f54"
set -g @sysstat_mem_color_medium "#bf8f62"
set -g @sysstat_mem_color_stress "#b34b4b"

set -g @prefix_highlight_fg "#ba5454,bold"
set -g @prefix_highlight_bg "#1a1b21"
set -g @prefix_highlight_copy_mode_attr "fg=#ba5454,bold,bg=#18191f"
