# Palette for the layout in tmux.conf.
thm_bg="#E4E4E4"
thm_bg_dark="#dadada"
thm_bg_soft_dark="#dfdfdf"
thm_fg="#5e8888"
thm_green="#7a7d48"
thm_green_dark="#8a8e52"
thm_red="#c74e4e"
thm_red_dark="#db5353"
thm_orange="#875537"
thm_orange_dark="#9a6140"
thm_blue_dark="#6397b3"
thm_teal_dark="#599c8e"

set -g mode-style "fg=#dfdfdf,bg=#9a6140"

set -g message-style "fg=#599c8e,bg=#dadada"

set -g status-style "fg=#6397b3,bg=#dadada"

setw -g window-status-style "fg=#7a7d48,bold,bg=#dadada"
setw -g window-status-current-style "fg=#dfdfdf,bold,bg=#7a7d48"
setw -g window-status-activity-style "fg=#9a6140"

setw -g pane-border-style "fg=#8a8e52"
setw -g pane-active-border-style "fg=#8a8e52"

set -g @sysstat_cpu_color_low "#7a7d48"
set -g @sysstat_cpu_color_medium "#875537"
set -g @sysstat_cpu_color_stress "#db5353"

set -g @sysstat_mem_color_low "#7a7d48"
set -g @sysstat_mem_color_medium "#875537"
set -g @sysstat_mem_color_stress "#db5353"

set -g @prefix_highlight_fg "#c74e4e,bold"
set -g @prefix_highlight_bg "#dfdfdf"
set -g @prefix_highlight_copy_mode_attr "fg=#c74e4e,bold,bg=#dadada"
