# Palette for the layout in tmux.conf.
thm_bg="#292b36"
thm_bg_dark="#252732"
thm_bg_soft_dark="#272934"
thm_fg="#c7c7b3"
thm_green="#62966d"
thm_green_dark="#598861"
thm_red="#bc6060"
thm_red_dark="#b15353"
thm_orange="#b58f70"
thm_orange_dark="#aa8162"
thm_blue_dark="#597c86"
thm_teal_dark="#577f74"

set -g mode-style "fg=#272934,bg=#b58865"

set -g message-style "fg=#60998a,bg=#252732"

set -g status-style "fg=#6398a6,bg=#252732"

setw -g window-status-style "fg=#649c70,bold,bg=#252732"
setw -g window-status-current-style "fg=#272934,bold,bg=#659f72"
setw -g window-status-activity-style "fg=#aa8162"

setw -g pane-border-style "fg=#598861"
setw -g pane-active-border-style "fg=#598861"

set -g @sysstat_cpu_color_low "#62966d"
set -g @sysstat_cpu_color_medium "#b58f70"
set -g @sysstat_cpu_color_stress "#b15353"

set -g @sysstat_mem_color_low "#62966d"
set -g @sysstat_mem_color_medium "#b58f70"
set -g @sysstat_mem_color_stress "#b15353"

set -g @prefix_highlight_fg "#cd7878,bold"
set -g @prefix_highlight_bg "#272934"
set -g @prefix_highlight_copy_mode_attr "fg=#cc7575,bold,bg=#252732"
