# Palette for the layout in tmux.conf.
thm_bg="#222120"
thm_bg_dark="#1e1d1c"
thm_bg_soft_dark="#201f1e"
thm_fg="#645c54"
thm_green="#757845"
thm_green_dark="#65683b"
thm_red="#ca4f4f"
thm_red_dark="#bd4343"
thm_orange="#c47d54"
thm_orange_dark="#b1704b"
thm_blue_dark="#3f6376"
thm_teal_dark="#39675d"

set -g mode-style "fg=#201f1e,bg=#be764c"

set -g message-style "fg=#309381,bg=#1e1d1c"

set -g status-style "fg=#3c8fb3,bg=#1e1d1c"

setw -g window-status-style "fg=#878b46,bold,bg=#1e1d1c"
setw -g window-status-current-style "fg=#ffffff,bold,bg=#757845"
setw -g window-status-activity-style "fg=#b1704b"

setw -g pane-border-style "fg=#65683b"
setw -g pane-active-border-style "fg=#65683b"

set -g @sysstat_cpu_color_low "#757845"
set -g @sysstat_cpu_color_medium "#c47d54"
set -g @sysstat_cpu_color_stress "#bd4343"

set -g @sysstat_mem_color_low "#757845"
set -g @sysstat_mem_color_medium "#c47d54"
set -g @sysstat_mem_color_stress "#bd4343"

set -g @prefix_highlight_fg "#de5e5e,bold"
set -g @prefix_highlight_bg "#201f1e"
set -g @prefix_highlight_copy_mode_attr "fg=#dc5a5a,bold,bg=#1e1d1c"
