# Palette for the layout in tmux.conf.
thm_bg="#232831"
thm_bg_dark="#1f242d"
thm_bg_soft_dark="#21262f"
thm_fg="#b3bac6"
thm_green="#879978"
thm_green_dark="#788c67"
thm_red="#ac6e74"
thm_red_dark="#a35e65"
thm_orange="#b88473"
thm_orange_dark="#af7461"
thm_blue_dark="#637b93"
thm_teal_dark="#688a88"

set -g mode-style "fg=#21262f,bg=#af7461"

set -g message-style "fg=#688a88,bg=#1f242d"

set -g status-style "fg=#637b93,bg=#1f242d"

setw -g window-status-style "fg=#879978,bold,bg=#1f242d"
setw -g window-status-current-style "fg=#21262f,bold,bg=#879978"
setw -g window-status-activity-style "fg=#af7461"

setw -g pane-border-style "fg=#788c67"
setw -g pane-active-border-style "fg=#788c67"

set -g @sysstat_cpu_color_low "#879978"
set -g @sysstat_cpu_color_medium "#b88473"
set -g @sysstat_cpu_color_stress "#a35e65"

set -g @sysstat_mem_color_low "#879978"
set -g @sysstat_mem_color_medium "#b88473"
set -g @sysstat_mem_color_stress "#a35e65"

set -g @prefix_highlight_fg "#ac6e74,bold"
set -g @prefix_highlight_bg "#21262f"
set -g @prefix_highlight_copy_mode_attr "fg=#ac6e74,bold,bg=#1f242d"
