# Palette for the layout in tmux.conf.
thm_bg="#1d1e27"
thm_bg_dark="#191a23"
thm_bg_soft_dark="#1b1c25"
thm_fg="#b2b7c7"
thm_green="#6b8d69"
thm_green_dark="#5b7e59"
thm_red="#b7657a"
thm_red_dark="#a85a6d"
thm_orange="#b88970"
thm_orange_dark="#ac7a63"
thm_blue_dark="#546891"
thm_teal_dark="#577972"

set -g mode-style "fg=#1b1c25,bg=#ac7a63"

set -g message-style "fg=#5f8d84,bg=#191a23"

set -g status-style "fg=#6284c2,bg=#191a23"

setw -g window-status-style "fg=#6b8d69,bold,bg=#191a23"
setw -g window-status-current-style "fg=#1b1c25,bold,bg=#6b8d69"
setw -g window-status-activity-style "fg=#ac7a63"

setw -g pane-border-style "fg=#5b7e59"
setw -g pane-active-border-style "fg=#5b7e59"

set -g @sysstat_cpu_color_low "#6b8d69"
set -g @sysstat_cpu_color_medium "#b88970"
set -g @sysstat_cpu_color_stress "#a85a6d"

set -g @sysstat_mem_color_low "#6b8d69"
set -g @sysstat_mem_color_medium "#b88970"
set -g @sysstat_mem_color_stress "#a85a6d"

set -g @prefix_highlight_fg "#c26b81,bold"
set -g @prefix_highlight_bg "#1b1c25"
set -g @prefix_highlight_copy_mode_attr "fg=#c0687f,bold,bg=#191a23"
