# Palette for the layout in tmux.conf.
thm_bg="#232929"
thm_bg_dark="#1f2424"
thm_bg_soft_dark="#212626"
thm_fg="#5a6158"
thm_green="#75783a"
thm_green_dark="#656831"
thm_red="#cb4f4f"
thm_red_dark="#c53b3b"
thm_orange="#cc7942"
thm_orange_dark="#b86d3c"
thm_blue_dark="#3a6479"
thm_teal_dark="#2d695d"

set -g mode-style "fg=#ffffff,bg=#a7653d"

set -g message-style "fg=#009b86,bg=#1f2424"

set -g status-style "fg=#2394bc,bg=#1f2424"

setw -g window-status-style "fg=#8c9031,bold,bg=#1f2424"
setw -g window-status-current-style "fg=#ffffff,bold,bg=#75783a"
setw -g window-status-activity-style "fg=#b86d3c"

setw -g pane-border-style "fg=#656831"
setw -g pane-active-border-style "fg=#656831"

set -g @sysstat_cpu_color_low "#75783a"
set -g @sysstat_cpu_color_medium "#cc7942"
set -g @sysstat_cpu_color_stress "#c53b3b"

set -g @sysstat_mem_color_low "#75783a"
set -g @sysstat_mem_color_medium "#cc7942"
set -g @sysstat_mem_color_stress "#c53b3b"

set -g @prefix_highlight_fg "#e16666,bold"
set -g @prefix_highlight_bg "#212626"
set -g @prefix_highlight_copy_mode_attr "fg=#e06262,bold,bg=#1f2424"
