# Palette for the layout in tmux.conf.
thm_bg="#E4E4E4"
thm_bg_dark="#dadada"
thm_bg_soft_dark="#dfdfdf"
thm_fg="#5e8888"
thm_green="#667b4f"
thm_green_dark="#68844b"
thm_red="#a94357"
thm_red_dark="#c4485f"
thm_orange="#b57148"
thm_orange_dark="#cb733e"
thm_blue_dark="#4971c5"
thm_teal_dark="#277767"

set -g mode-style "fg=#dfdfdf,bg=#cb733e"

set -g message-style "fg=#277767,bg=#dadada"

set -g status-style "fg=#4971c5,bg=#dadada"

setw -g window-status-style "fg=#667b4f,bold,bg=#dadada"
setw -g window-status-current-style "fg=#dfdfdf,bold,bg=#667b4f"
setw -g window-status-activity-style "fg=#cb733e"

setw -g pane-border-style "fg=#68844b"
setw -g pane-active-border-style "fg=#68844b"

set -g @sysstat_cpu_color_low "#667b4f"
set -g @sysstat_cpu_color_medium "#b57148"
set -g @sysstat_cpu_color_stress "#c4485f"

set -g @sysstat_mem_color_low "#667b4f"
set -g @sysstat_mem_color_medium "#b57148"
set -g @sysstat_mem_color_stress "#c4485f"

set -g @prefix_highlight_fg "#a94357,bold"
set -g @prefix_highlight_bg "#dfdfdf"
set -g @prefix_highlight_copy_mode_attr "fg=#a94357,bold,bg=#dadada"
