# Palette for the layout in tmux.conf.
thm_bg="#E4E4E4"
thm_bg_dark="#dadada"
thm_bg_soft_dark="#dfdfdf"
thm_fg="#5e8888"
thm_green="#6b8578"
thm_green_dark="#6d8f7f"
thm_red="#a65c6e"
thm_red_dark="#c35f78"
thm_orange="#a9754b"
thm_orange_dark="#bc7843"
thm_blue_dark="#4f6e97"
thm_teal_dark="#498789"

set -g mode-style "fg=#dfdfdf,bg=#bc7843"

set -g message-style "fg=#498789,bg=#dadada"

set -g status-style "fg=#4f6e97,bg=#dadada"

setw -g window-status-style "fg=#6b8578,bold,bg=#dadada"
setw -g window-status-current-style "fg=#dfdfdf,bold,bg=#6b8578"
setw -g window-status-activity-style "fg=#bc7843"

setw -g pane-border-style "fg=#6d8f7f"
setw -g pane-active-border-style "fg=#6d8f7f"

set -g @sysstat_cpu_color_low "#6b8578"
set -g @sysstat_cpu_color_medium "#a9754b"
set -g @sysstat_cpu_color_stress "#c35f78"

set -g @sysstat_mem_color_low "#6b8578"
set -g @sysstat_mem_color_medium "#a9754b"
set -g @sysstat_mem_color_stress "#c35f78"

set -g @prefix_highlight_fg "#a65c6e,bold"
set -g @prefix_highlight_bg "#dfdfdf"
set -g @prefix_highlight_copy_mode_attr "fg=#a65c6e,bold,bg=#dadada"
