set -g mode-style "fg=#dfdfdf,bg=#ab7b4b"

set -g message-style "fg=#42778a,bg=#dadada"

set -g status-style "fg=#688bcb,bg=#dadada"

setw -g window-status-style "fg=#677951,bold,bg=#dadada"
setw -g window-status-format " #I:#W "
setw -g window-status-current-style "fg=#dfdfdf,bold,bg=#677951"
setw -g window-status-current-format " #I:#W "

setw -g window-status-activity-style "fg=#ab7b4b"

setw -g pane-border-style "fg=#6d7f55"
setw -g pane-active-border-style "fg=#6d7f55"

set -g status on
set -g status-interval 5
set -g status-position bottom
set -g status-justify left
set -g status-right-length 100

wg_session="#[bg=#677951,bold,fg=#dfdfdf] #S #[default]"
wg_user_host="#[bg=#dadada,bold,fg=#c85b5b] #(whoami)@#H"
wg_is_zoomed="#[fg=#dadada,bg=#c85b5b]#{?window_zoomed_flag, ZOOM ,}#[default]"
wg_is_keys_off="#[fg=#dfdfdf,bg=#c85b5b]#([ $(tmux show-option -qv key-table) = 'off' ] && echo ' KEYS OFF ')#[default]"
wg_date="#[bg=#677951,bold,fg=#dfdfdf] %h %d %H:%M #[default]"

set -g status-left "$wg_session"
set -g status-right "#{prefix_highlight} $wg_is_keys_off $wg_is_zoomed #{sysstat_cpu} | #{sysstat_mem} $wg_user_host #{online_status} $wg_date"

set -g @online_icon "#[fg=#677951]●#[default]"
set -g @offline_icon "#[fg=#d15e5e]●#[default]"

set -g @sysstat_mem_view_tmpl 'MEM:#[fg=#{mem.color}]#{mem.pused}#[default] #{mem.used}'

set -g @sysstat_cpu_color_low "#677951"
set -g @sysstat_cpu_color_medium "#a5794e"
set -g @sysstat_cpu_color_stress "#d15e5e"

set -g @sysstat_mem_color_low "#677951"
set -g @sysstat_mem_color_medium "#a5794e"
set -g @sysstat_mem_color_stress "#d15e5e"

set -g @prefix_highlight_output_prefix '['
set -g @prefix_highlight_output_suffix ']'
set -g @prefix_highlight_fg "#c85b5b,bold"
set -g @prefix_highlight_bg "#dfdfdf"
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_copy_mode_attr "fg=#c85b5b,bold,bg=#dadada"
