-- lvim-colorscheme.extra.atuin: generate an atuin theme file from the lvim-colorscheme palette.
--
-- atuin reads a theme from `<config dir>/themes/<name>.toml` (`~/.config/atuin/themes/`, or
-- `$ATUIN_THEME_DIR` / `$ATUIN_CONFIG_DIR` when set) and selects it by name:
--
--     mkdir -p ~/.config/atuin/themes
--     cp extras/atuin/*.toml ~/.config/atuin/themes/
--
-- then, in `~/.config/atuin/config.toml`:
--
--     [theme]
--     name = "LvimNord_dark"
--
-- The file is a map of "meanings" to colours. `#rrggbb` is accepted verbatim (theme.rs parses a
-- leading `#` as three hex pairs), so the palette goes in unmodified — no ANSI approximation.
--
-- Every meaning atuin knows is written out, deliberately. A missing one does not fall back to the
-- rest of THIS theme: `from_map` fills the gap from atuin's own DEFAULT_THEME, so a partial file
-- silently mixes lvim colours with atuin's built-in DarkRed / DarkGreen / Grey.
--
-- Colour choices follow extra/clipack.lua, for the same reason: both paint on the terminal
-- background rather than the editor one, so each value clears a contrast floor measured there.
--
---@module "lvim-colorscheme.extra.atuin"

local util = require("lvim-colorscheme.util")

local M = {}

--- @param colors ColorScheme
--- @param _ table  highlight groups, unused: atuin maps from the palette
--- @param opts table
function M.generate(colors, _, opts)
    local bg = colors.terminal.background

    colors.atuin_theme_name = "Lvim" .. (opts.style:gsub("^%l", string.upper))

    -- Ordinary text, at the body-text floor.
    colors.atuin_base = util.ensure_contrast(colors.terminal.foreground, bg, 4.5)

    -- Alerts. Kept at the accent floor rather than the body one: they are short, coloured strings
    -- whose job is to be identifiable, and lifting them to 4.5 pulls red and yellow toward pastel.
    colors.atuin_alert_error = util.ensure_contrast(colors.red, bg, 3)
    colors.atuin_alert_warn = util.ensure_contrast(colors.yellow, bg, 3)
    colors.atuin_alert_info = util.ensure_contrast(colors.green, bg, 3)

    -- Two tiers of secondary text. atuin's defaults make Muted (Grey) brighter than Annotation
    -- (DarkGrey), so both tiers are placed RELATIVE to Base rather than at fixed floors: a floor
    -- can only push a colour away from the background, and `fg_soft_dark` is already brighter than
    -- the terminal foreground in 12 of these 48 styles (all of dracula, material and nightfox), so
    -- flooring it left Muted level with Base and the tier disappeared. Base clears 6:1 by
    -- construction, so 0.6 and 0.35 of it never sink below 3.6:1 and 2.1:1 respectively.
    local base_contrast = util.contrast(colors.atuin_base, bg)
    colors.atuin_muted = util.to_contrast(colors.fg_soft_dark, bg, base_contrast * 0.6)
    colors.atuin_annotation = util.to_contrast(colors.comment, bg, math.max(base_contrast * 0.35, 2.2))

    -- The selected entry and the section headings. Same accent pair as clipack: `magenta` leads,
    -- `blue` is the alternate, because `purple` reads as a desaturated grey in most of these
    -- palettes and `cyan` collapses onto `green` in several.
    colors.atuin_important = util.ensure_contrast(colors.magenta, bg, 3)
    colors.atuin_title = util.ensure_contrast(colors.blue, bg, 3)
    -- Keybinding hints along the bottom. Distinct from Title, which is also blue.
    colors.atuin_guidance = util.ensure_contrast(colors.cyan, bg, 3)

    -- Syntax highlighting of the command being previewed.
    colors.atuin_syntax_command = util.ensure_contrast(colors.green, bg, 3)
    colors.atuin_syntax_flag = util.ensure_contrast(colors.cyan, bg, 3)
    colors.atuin_syntax_string = util.ensure_contrast(colors.orange, bg, 3)
    colors.atuin_syntax_variable = util.ensure_contrast(colors.magenta, bg, 3)
    -- Operators are plain text in atuin's default; keeping them at the base colour preserves that
    -- while still pinning them to this palette rather than the terminal's.
    colors.atuin_syntax_operator = colors.atuin_base
    colors.atuin_syntax_comment = colors.atuin_annotation

    return util.template(
        [[# ${_style_name}
# Generated by lvim-colorscheme for atuin — https://github.com/atuinsh/atuin
#
# Install:
#   mkdir -p ~/.config/atuin/themes
#   cp extras/atuin/*.toml ~/.config/atuin/themes/
#
# Use, in ~/.config/atuin/config.toml:
#   [theme]
#   name = "${atuin_theme_name}"

[theme]
name = "${atuin_theme_name}"

[colors]
# Default foreground.
Base = "${atuin_base}"
# Failures.
AlertError = "${atuin_alert_error}"
# Non-fatal problems.
AlertWarn = "${atuin_alert_warn}"
# Informational notices.
AlertInfo = "${atuin_alert_info}"
# Secondary text.
Muted = "${atuin_muted}"
# Tertiary text: timestamps, durations, exit codes.
Annotation = "${atuin_annotation}"
# The selected entry.
Important = "${atuin_important}"
# Section headings.
Title = "${atuin_title}"
# Keybinding hints.
Guidance = "${atuin_guidance}"
# Command preview.
SyntaxCommand = "${atuin_syntax_command}"
SyntaxFlag = "${atuin_syntax_flag}"
SyntaxString = "${atuin_syntax_string}"
SyntaxVariable = "${atuin_syntax_variable}"
SyntaxOperator = "${atuin_syntax_operator}"
SyntaxComment = "${atuin_syntax_comment}"
]],
        colors
    )
end

return M
