-- lvim-colorscheme.extra.clipack: generate a clipack theme file from the lvim-colorscheme palette.
--
-- clipack is a terminal package manager whose Bubble Tea interface reads its palette from
-- `~/.config/clipack/themes/<name>.yaml`. The generated file is a COMPLETE theme — colours,
-- border and glyph set — so dropping it in is all that is needed:
--
--     mkdir -p ~/.config/clipack/themes
--     cp extras/clipack/*.yaml ~/.config/clipack/themes/
--
-- and then, in `~/.config/clipack/config.yaml`:
--
--     theme:
--       name: LvimNord_dark
--
-- Colour choices, measured against the palettes rather than assumed:
--   * `magenta` / `blue` are the accents. `purple` reads as a desaturated grey in most styles
--     (nord #9b93a4, gruvbox #635d71, rosepine #958fa7) and `cyan` collapses onto `green` in
--     several of them (rosepine has them identical), so neither survives as an accent across
--     all 48 styles.
--   * Foregrounds go through `ensure_contrast` against the TERMINAL background, not the editor
--     one. Several palettes carry a deliberately muted `fg` that is tuned for syntax
--     highlighting — gruvbox_dark's `fg` (#645c54) and `comment` (#63584f) are nearly the same
--     colour — and a TUI that paints them as plain text on the terminal background needs a
--     readability floor the editor never asked for.
--
---@module "lvim-colorscheme.extra.clipack"

local util = require("lvim-colorscheme.util")

local M = {}

--- @param colors ColorScheme
--- @param _ table  highlight groups, unused: clipack maps from the palette
--- @param opts table
function M.generate(colors, _, opts)
    local term_bg = colors.terminal.background

    -- clipack draws these directly on the terminal background, so each one has to clear a
    -- legibility floor there. The floors mirror the ones the terminal palette itself uses:
    -- ordinary text well clear of the background, secondary text a step below it.
    local text = util.ensure_contrast(colors.terminal.foreground, term_bg, 4.5)
    local muted = util.ensure_contrast(colors.comment, term_bg, 3)
    local accent = util.ensure_contrast(colors.magenta, term_bg, 3)
    local accent_alt = util.ensure_contrast(colors.blue, term_bg, 3)
    local success = util.ensure_contrast(colors.green, term_bg, 3)
    local warning = util.ensure_contrast(colors.yellow, term_bg, 3)
    local error_color = util.ensure_contrast(colors.red, term_bg, 3)

    -- The title badge is the one place clipack paints a background: its text sits ON `accent`,
    -- so it takes the editor background and is checked against the accent, not the terminal.
    local title_fg = util.ensure_contrast(colors.bg, accent, 3)

    -- Unfocused pane borders. `bg_light` is the palette's own "one step off the background"
    -- value, which is what a quiet border wants — but it is a step off the EDITOR background,
    -- and on the light styles that lands close enough to the terminal background to vanish
    -- (gruvbox_light gives #eeeeee). A low floor keeps the border drawn without promoting it
    -- to a foreground colour.
    local subtle = util.ensure_contrast(colors.bg_light, term_bg, 1.6)

    -- The theme name is the file basename, so `theme.name` in config.yaml matches the file
    -- that gets copied into ~/.config/clipack/themes/.
    colors.clipack_theme_name = "Lvim" .. (opts.style:gsub("^%l", string.upper))
    colors.clipack_text = text
    colors.clipack_muted = muted
    colors.clipack_accent = accent
    colors.clipack_accent_alt = accent_alt
    colors.clipack_success = success
    colors.clipack_warning = warning
    colors.clipack_error = error_color
    colors.clipack_title_fg = title_fg
    colors.clipack_subtle = subtle

    return util.template(
        [[---
# ${_style_name}
# Generated by lvim-colorscheme for clipack — https://github.com/lvim-tech/clipack
#
# Install:
#   mkdir -p ~/.config/clipack/themes
#   cp extras/clipack/*.yaml ~/.config/clipack/themes/
#
# Use, in ~/.config/clipack/config.yaml:
#   theme:
#     name: ${clipack_theme_name}
#
# Anything here can be overridden per-machine from config.yaml; only the keys you
# repeat there are replaced, the rest still come from this file.

name: ${clipack_theme_name}

# rounded | normal | thick | double | hidden | none
border: normal

# unicode | ascii
icons: unicode

colors:
    # Selection cursor, focused pane border and the title badge background.
    accent: "${clipack_accent}"
    # Section headings, the active tab and step markers.
    accent_alt: "${clipack_accent_alt}"
    # Default foreground.
    text: "${clipack_text}"
    # Descriptions, field labels, hints, streamed build output.
    muted: "${clipack_muted}"
    # Unfocused pane borders.
    subtle: "${clipack_subtle}"
    # Installed packages and completed operations.
    success: "${clipack_success}"
    # Available updates and non-fatal problems.
    warning: "${clipack_warning}"
    # Failures.
    error: "${clipack_error}"
    # Text of the title badge, drawn on `accent`.
    title_fg: "${clipack_title_fg}"
]],
        colors
    )
end

return M
