-- lvim-colorscheme.extra.fsel: generate an fsel colour config from the lvim-colorscheme palette.
--
-- fsel reads one `~/.config/fsel/config.toml` (or the path given to `--config`), so the generated
-- files are meant to be symlinked:
--
--     mkdir -p ~/.config/fsel
--     ln -sf .../extras/fsel/LvimNord_dark.toml ~/.config/fsel/config.toml
--
-- Only colour keys are written. That is a complete, valid config: every key in fsel's schema is
-- `#[serde(default)]`, so behaviour, keybinds and layout keep their built-in values instead of
-- being frozen at whatever this generator happened to think they should be. It also means a
-- generated file will NOT preserve settings you had in config.toml — keep those in a copy and
-- merge, or point `--config` at the generated file only for the modes you theme.
--
-- Colours are `#rrggbb`: `string_to_color` tries `parse_hex_color` first, ahead of the `rgb(r,g,b)`
-- form and the named palette.
--
-- fsel also honours `FSEL_*` environment variables, but only `FSEL_HIGHLIGHT_COLOR` exists for the
-- launcher's own colours — the border, text, header and pin colours have no variable — so an
-- env-based theme could not cover the main UI. The file is the only complete route.
--
-- The three modes (launcher, dmenu, cclip) are themed identically; dmenu and cclip name their list
-- panel `items_` where the launcher calls it `apps_`.
--
---@module "lvim-colorscheme.extra.fsel"

local util = require("lvim-colorscheme.util")

local M = {}

--- @param colors ColorScheme
--- @param _ table  highlight groups, unused: fsel maps from the palette
--- @param opts table
function M.generate(colors, _, opts)
    local bg = colors.terminal.background
    local function c(color, min)
        return util.ensure_contrast(color, bg, min or 3)
    end

    colors.fsel_theme_name = "Lvim" .. (opts.style:gsub("^%l", string.upper))

    -- Text sits at the body floor; borders are allowed to be quiet, but not so quiet they vanish
    -- on the light styles — the same 1.6 floor extra/clipack.lua uses for its unfocused panes.
    colors.fsel_text = c(colors.terminal.foreground, 4.5)
    colors.fsel_border = util.ensure_contrast(colors.bg_light, bg, 1.6)
    -- Selection cursor and the panel titles: the clipack accent pair, for the same reasons.
    colors.fsel_highlight = c(colors.magenta)
    colors.fsel_title = c(colors.blue)
    -- Pinned entries. Warm, so a pin reads as a mark rather than as selection.
    colors.fsel_pin = c(colors.orange)

    return util.template(
        [[# ${_style_name}
# Generated by lvim-colorscheme for fsel — https://github.com/Mjoyufull/fsel
#
# Install:
#   mkdir -p ~/.config/fsel
#   ln -sf extras/fsel/${fsel_theme_name}.toml ~/.config/fsel/config.toml
#
# Colour keys only. Everything else — keybinds, matching, layout, launch behaviour — keeps
# fsel's defaults, so this file can be replaced wholesale when the palette changes.

# --- app launcher (root level) ---------------------------------------------

# Selected item and cursor.
highlight_color = "${fsel_highlight}"
# Panel titles.
header_title_color = "${fsel_title}"
# Pin icon on pinned entries.
pin_color = "${fsel_pin}"

# Panel borders.
main_border_color = "${fsel_border}"
apps_border_color = "${fsel_border}"
input_border_color = "${fsel_border}"

# Panel text.
main_text_color = "${fsel_text}"
apps_text_color = "${fsel_text}"
input_text_color = "${fsel_text}"

# --- dmenu mode ------------------------------------------------------------

[dmenu]
highlight_color = "${fsel_highlight}"
header_title_color = "${fsel_title}"
main_border_color = "${fsel_border}"
items_border_color = "${fsel_border}"
input_border_color = "${fsel_border}"
main_text_color = "${fsel_text}"
items_text_color = "${fsel_text}"
input_text_color = "${fsel_text}"

# --- cclip mode ------------------------------------------------------------

[cclip]
highlight_color = "${fsel_highlight}"
header_title_color = "${fsel_title}"
main_border_color = "${fsel_border}"
items_border_color = "${fsel_border}"
input_border_color = "${fsel_border}"
main_text_color = "${fsel_text}"
items_text_color = "${fsel_text}"
input_text_color = "${fsel_text}"
]],
        colors
    )
end

return M
