-- lvim-colorscheme.extra.yazi: generate a Yazi flavor from the lvim-colorscheme palette.
--
-- Targets Yazi 26. Version 26 reshaped the theme schema, and a flavor written for 25 does not
-- merely lose styling — it aborts startup with a TOML parse error, so the changes are not
-- cosmetic:
--
--   [manager]                    -> [mgr]
--   [completion]                 -> [cmp]
--   hovered / preview_hovered    -> [indicator] current / preview (and `parent`, new)
--   tab_active / tab_inactive    -> [tabs] active / inactive
--   tab_width                    -> gone
--   [status] separator_open/close-> [status] sep_left / sep_right, each { open, close }
--   [confirm] content            -> [confirm] body
--   [filetype] rules: name =     -> url =
--
-- `[icon]` is deliberately not emitted. Yazi merges a flavor over its own preset, so leaving the
-- section out keeps upstream's icon set; writing one would freeze a glyph list into every palette
-- and overwrite whatever the user had. `[flavor]` is likewise absent — that key selects a flavor,
-- and a flavor selecting itself is circular.
--
---@module "lvim-colorscheme.extra.yazi"

local util = require("lvim-colorscheme.util")

local M = {}

--- @param colors ColorScheme
function M.generate(colors)
    colors.bg_search = util.blend_bg(colors.info, 0.1)

    local yazi = util.template(
        [[
#:schema https://yazi-rs.github.io/schemas/theme.json
# ${_style_name}
# Generated by lvim-colorscheme for Yazi 26 — https://github.com/sxyazi/yazi

[mgr]
cwd = { fg = "${fg_dark}", italic = true }

# Find
find_keyword  = { fg = "${bg_dark}", bg = "${orange}", bold = true }
find_position = { fg = "${blue_dark}", bg = "${bg_search}", bold = true }

# Symlink
symlink_target = { fg = "${comment}", italic = true }

# Marker
marker_copied   = { fg = "${yellow_dark}", bg = "${yellow_dark}" }
marker_cut      = { fg = "${red}", bg = "${red}" }
marker_marked   = { fg = "${magenta}", bg = "${magenta}" }
marker_selected = { fg = "${blue}", bg = "${blue}" }
marker_symbol   = "│"

# Count
count_copied   = { fg = "${fg}", bg = "${green_dark}" }
count_cut      = { fg = "${fg}", bg = "${red_dark}" }
count_selected = { fg = "${fg}", bg = "${teal_dark}" }

# Border
border_symbol = "│"
border_style  = { fg = "${border_highlight}" }

# The row under the cursor in each pane. In 25 this was `hovered` and
# `preview_hovered` under [manager]; 26 gives the parent pane one of its own.
[indicator]
parent  = { bg = "${bg_visual}" }
current = { bg = "${bg_highlight}" }
preview = { bg = "${bg_highlight}" }
padding = { open = "", close = "" }

[tabs]
active   = { fg = "${fg}", bg = "${bg_highlight}", bold = true }
inactive = { fg = "${fg_soft_dark}", bg = "${bg}" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
normal_main = { fg = "${black}", bg = "${blue}", bold = true }
normal_alt  = { fg = "${blue}", bg = "${fg_soft_dark}" }

select_main = { fg = "${black}", bg = "${magenta}", bold = true }
select_alt  = { fg = "${magenta}", bg = "${fg_soft_dark}" }

unset_main  = { fg = "${black}", bg = "${purple}", bold = true }
unset_alt   = { fg = "${purple}", bg = "${fg_soft_dark}" }

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label  = { fg = "${fg_dark}", bold = true }
progress_normal = { fg = "${green}", bg = "${bg_dark}" }
progress_error  = { fg = "${bg_dark}", bg = "${red}" }

# Permissions
perm_type  = { fg = "${blue}" }
perm_read  = { fg = "${yellow}" }
perm_write = { fg = "${red}" }
perm_exec  = { fg = "${green}" }
perm_sep   = { fg = "${comment}" }

[pick]
border   = { fg = "${border_highlight}" }
active   = { fg = "${fg}",  bg = "${bg_visual}" }
inactive = { fg = "${fg}" }

[input]
border   = { fg = "${blue_dark}" }
title    = { fg = "${blue_dark}" }
value    = { fg = "${purple}" }
selected = { bg = "${bg_visual}" }

[cmp]
border   = { fg = "${blue_dark}" }
active   = { fg = "${fg}", bg = "${bg_visual}" }
inactive = { fg = "${fg}" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

[tasks]
border  = { fg = "${border_highlight}" }
title   = { fg = "${border_highlight}" }
hovered = { fg = "${fg}", bg = "${bg_visual}" }

[which]
cols            = 3
mask            = { bg = "${bg_dark}" }
cand            = { fg = "${cyan}" }
rest            = { fg = "${blue}" }
desc            = { fg = "${magenta}" }
separator       = " ➜ "
separator_style = { fg = "${comment}" }

[confirm]
border  = { fg = "${blue_dark}" }
title   = { fg = "${border_highlight}" }
body    = {}
list    = {}
btn_yes = { bg = "${bg_visual}" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

[spot]
border   = { fg = "${border_highlight}" }
title    = { fg = "${border_highlight}" }
tbl_col  = { fg = "${blue}" }
tbl_cell = { fg = "${yellow}", bg = "${bg_visual}" }

[notify]
title_info  = { fg = "${info}" }
title_warn  = { fg = "${warning}" }
title_error = { fg = "${error}" }

icon_info  = ""
icon_warn  = ""
icon_error = ""

[help]
on      = { fg = "${green}" }
run     = { fg = "${magenta}" }
desc    = { fg = "${fg_soft_dark}" }
hovered = { bg = "${bg_highlight}", bold = true }
footer  = { fg = "${fg}", bg = "${bg}" }

[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "${yellow}" },

	# Media
	{ mime = "{audio,video}/*", fg = "${magenta}" },

	# Archives
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "${red}" },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "${cyan}" },

	# Virtual file system — 26 reports unreachable remote entries through this
	{ mime = "vfs/{absent,stale}", fg = "${comment}" },

	# Special files. `url` here was `name` before 26.
	{ url = "*", is = "orphan", bg = "${red}" },
	{ url = "*", is = "exec"  , fg = "${green}" },
	{ url = "*", is = "dummy", bg = "${red}" },
	{ url = "*/", is = "dummy", bg = "${red}" },

	# Fallback
	{ url = "*/", fg = "${blue}" }
]
    ]],
        colors
    )
    return yazi
end

return M
