[style]
header = "67"
unit = "240"
tree = "236"

[style.by_percentage]
color_000 = "67"
color_025 = "101"
color_050 = "179"
color_075 = "173"
color_100 = "167"

[style.by_state]
color_d = "167"
color_r = "101"
color_s = "67"
color_t = "179"
color_z = "167"
color_x = "240"

[style.by_unit]
color_k = "67"
color_m = "101"
color_g = "179"
color_t = "173"
color_p = "167"
color_x = "240"
