[style]
header = "67"
unit = "102"
tree = "234"

[style.by_percentage]
color_000 = "67"
color_025 = "245"
color_050 = "143"
color_075 = "173"
color_100 = "132"

[style.by_state]
color_d = "132"
color_r = "245"
color_s = "67"
color_t = "143"
color_z = "103"
color_x = "102"

[style.by_unit]
color_k = "67"
color_m = "245"
color_g = "143"
color_t = "173"
color_p = "132"
color_x = "102"
