[style]
header = "68"
unit = "248"
tree = "255"

[style.by_percentage]
color_000 = "68"
color_025 = "65"
color_050 = "95"
color_075 = "137"
color_100 = "167"

[style.by_state]
color_d = "167"
color_r = "65"
color_s = "68"
color_t = "95"
color_z = "95"
color_x = "248"

[style.by_unit]
color_k = "68"
color_m = "65"
color_g = "95"
color_t = "137"
color_p = "167"
color_x = "248"
