[style]
header = "241"
unit = "242"
tree = "255"

[style.by_percentage]
color_000 = "241"
color_025 = "59"
color_050 = "241"
color_075 = "241"
color_100 = "95"

[style.by_state]
color_d = "95"
color_r = "59"
color_s = "241"
color_t = "241"
color_z = "60"
color_x = "242"

[style.by_unit]
color_k = "241"
color_m = "59"
color_g = "241"
color_t = "241"
color_p = "95"
color_x = "242"
