[style]
header = "60"
unit = "59"
tree = "255"

[style.by_percentage]
color_000 = "60"
color_025 = "240"
color_050 = "59"
color_075 = "94"
color_100 = "131"

[style.by_state]
color_d = "131"
color_r = "240"
color_s = "60"
color_t = "59"
color_z = "95"
color_x = "59"

[style.by_unit]
color_k = "60"
color_m = "240"
color_g = "59"
color_t = "94"
color_p = "131"
color_x = "59"
