[style]
header = "103"
unit = "244"
tree = "255"

[style.by_percentage]
color_000 = "103"
color_025 = "243"
color_050 = "95"
color_075 = "137"
color_100 = "95"

[style.by_state]
color_d = "95"
color_r = "243"
color_s = "103"
color_t = "95"
color_z = "246"
color_x = "244"

[style.by_unit]
color_k = "103"
color_m = "243"
color_g = "95"
color_t = "137"
color_p = "95"
color_x = "244"
