[style]
header = "60"
unit = "240"
tree = "234"

[style.by_percentage]
color_000 = "60"
color_025 = "101"
color_050 = "143"
color_075 = "173"
color_100 = "167"

[style.by_state]
color_d = "167"
color_r = "101"
color_s = "60"
color_t = "143"
color_z = "137"
color_x = "240"

[style.by_unit]
color_k = "60"
color_m = "101"
color_g = "143"
color_t = "173"
color_p = "167"
color_x = "240"
