[style]
header = "61"
unit = "60"
tree = "234"

[style.by_percentage]
color_000 = "61"
color_025 = "101"
color_050 = "144"
color_075 = "137"
color_100 = "131"

[style.by_state]
color_d = "131"
color_r = "101"
color_s = "61"
color_t = "144"
color_z = "103"
color_x = "60"

[style.by_unit]
color_k = "61"
color_m = "101"
color_g = "144"
color_t = "137"
color_p = "131"
color_x = "60"
