[style]
header = "67"
unit = "103"
tree = "255"

[style.by_percentage]
color_000 = "67"
color_025 = "59"
color_050 = "101"
color_075 = "137"
color_100 = "131"

[style.by_state]
color_d = "131"
color_r = "59"
color_s = "67"
color_t = "101"
color_z = "97"
color_x = "103"

[style.by_unit]
color_k = "67"
color_m = "59"
color_g = "101"
color_t = "137"
color_p = "131"
color_x = "103"
