background #002934
foreground #9da4a4
selection_background #022d38
selection_foreground #9da4a4
url_color #4f7ea3
cursor #727c3e
cursor_text_color #002732

# Tabs
active_tab_background #4f7ea3
active_tab_foreground #002732
inactive_tab_background #022d38
inactive_tab_foreground #002b36
tab_bar_background #00222b

# Windows
active_border_color #4f7ea3
inactive_border_color #022d38

# normal
color0 #00222b
color1 #c24f4d
color2 #727c3e
color3 #9f8549
color4 #477193
color5 #c0578a
color6 #4b8580
color7 #636666

# bright
color8  #10353f
color9  #ea4440
color10 #7d8b25
color11 #b4912e
color12 #3680b0
color13 #e64d9d
color14 #37968f
color15 #6c7070

# extended colors
color16 #b46548
color17 #c24f4d