background #232933
foreground #b3bac6
selection_background #303643
selection_foreground #b3bac6
url_color #8097af
cursor #97ab86
cursor_text_color #1f232c

# Tabs
active_tab_background #8097af
active_tab_foreground #1f232c
inactive_tab_background #303643
inactive_tab_foreground #282d38
tab_bar_background #20242d

# Windows
active_border_color #8097af
inactive_border_color #303643

# normal
color0 #20242d
color1 #af7177
color2 #97ab86
color3 #cbae72
color4 #20242d
color5 #a58aa0
color6 #7eaab7
color7 #b0b3ba

# bright
color8  #465062
color9  #cd757f
color10 #9abd7a
color11 #e2ba59
color12 #6798c3
color13 #c48eba
color14 #70bbcf
color15 #b3bac6

# extended colors
color16 #ba8574
color17 #af7177