background #1b191d
foreground #b3afb2
selection_background #1f1d21
selection_foreground #b3afb2
url_color #5d6d74
cursor #788b7c
cursor_text_color #19171b

# Tabs
active_tab_background #5d6d74
active_tab_foreground #19171b
inactive_tab_background #1f1d21
inactive_tab_foreground #1d1b1f
tab_bar_background #171619

# Windows
active_border_color #5d6d74
inactive_border_color #1f1d21

# normal
color0 #171619
color1 #a0727c
color2 #788b7c
color3 #b6a18b
color4 #526167
color5 #9084a2
color6 #788787
color7 #696769

# bright
color8  #2a282c
color9  #c47387
color10 #729d7c
color11 #d0ac80
color12 #50707b
color13 #a38dc1
color14 #749898
color15 #7e7b7d

# extended colors
color16 #a98a89
color17 #a0727c