background #181825
foreground #b2b7c7
selection_background #292a39
selection_foreground #b2b7c7
url_color #6793da
cursor #84c27f
cursor_text_color #11111b

# Tabs
active_tab_background #6793da
active_tab_foreground #11111b
inactive_tab_background #292a39
inactive_tab_foreground #1e1e2e
tab_bar_background #181825

# Windows
active_border_color #6793da
inactive_border_color #292a39

# normal
color0 #181825
color1 #d36d89
color2 #84c27f
color3 #d8b973
color4 #181825
color5 #d07fba
color6 #71becc
color7 #9b9eaa

# bright
color8  #4a4d5e
color9  #e97596
color10 #75d66b
color11 #efc655
color12 #458ff6
color13 #e787cd
color14 #53d0e4
color15 #b2b7c7

# extended colors
color16 #da9366
color17 #d36d89