background #dfdfdf
foreground #425353
selection_background #e9e9e9
selection_foreground #425353
url_color #6579ac
cursor #606f52
cursor_text_color #dadada

# Tabs
active_tab_background #6579ac
active_tab_foreground #dadada
inactive_tab_background #e9e9e9
inactive_tab_foreground #E4E4E4
tab_bar_background #b6b6b6

# Windows
active_border_color #6579ac
inactive_border_color #e9e9e9

# normal
color0 #b6b6b6
color1 #ab5867
color2 #606f52
color3 #927d61
color4 #7487bd
color5 #765ba6
color6 #587387
color7 #619494

# bright
color8  #cfd1d1
color9  #d4506d
color10 #657e4b
color11 #a88857
color12 #7994d9
color13 #8860ca
color14 #5182a1
color15 #5d8989

# extended colors
color16 #b17f67
color17 #ab5867