background #242134
foreground #b4b2c7
selection_background #2d2a3b
selection_foreground #b4b2c7
url_color #416d7f
cursor #83b2ba
cursor_text_color #141321

# Tabs
active_tab_background #416d7f
active_tab_foreground #141321
inactive_tab_background #2d2a3b
inactive_tab_foreground #1e1b2b
tab_bar_background #181622

# Windows
active_border_color #416d7f
inactive_border_color #2d2a3b

# normal
color0 #181622
color1 #cd6985
color2 #83b2ba
color3 #d6a765
color4 #181622
color5 #9f80c4
color6 #83b2ba
color7 #9694a3

# bright
color8  #312f44
color9  #e57091
color10 #74c4d0
color11 #f0b246
color12 #2d728a
color13 #b189df
color14 #74c4d0
color15 #b4b2c7

# extended colors
color16 #c68784
color17 #cd6985