background #dfdfdf
foreground #425353
selection_background #e9e9e9
selection_foreground #425353
url_color #6385c2
cursor #697b51
cursor_text_color #dadada

# Tabs
active_tab_background #6385c2
active_tab_foreground #dadada
inactive_tab_background #e9e9e9
inactive_tab_foreground #E4E4E4
tab_bar_background #b6b6b6

# Windows
active_border_color #6385c2
inactive_border_color #e9e9e9

# normal
color0 #b6b6b6
color1 #c35959
color2 #697b51
color3 #816f4a
color4 #6c8dcc
color5 #94544f
color6 #5e827b
color7 #619494

# bright
color8  #cfd1d1
color9  #e25a5a
color10 #6f8b45
color11 #947b3d
color12 #709ae6
color13 #b85349
color14 #549388
color15 #5d8989

# extended colors
color16 #a87e56
color17 #c35959