background #1e2529
foreground #6aaeae
selection_background #22292d
selection_foreground #6aaeae
url_color #447ca2
cursor #7e965a
cursor_text_color #1c2327

# Tabs
active_tab_background #447ca2
active_tab_foreground #1c2327
inactive_tab_background #22292d
inactive_tab_foreground #20272b
tab_bar_background #1a1f22

# Windows
active_border_color #447ca2
inactive_border_color #22292d

# normal
color0 #1a1f22
color1 #d75e52
color2 #7e965a
color3 #d8b36f
color4 #3b6d8d
color5 #c6614d
color6 #448595
color7 #547373

# bright
color8  #263336
color9  #f06455
color10 #84a647
color11 #f0bf51
color12 #237ca8
color13 #ea5f3a
color14 #2595ab
color15 #557575

# extended colors
color16 #e19556
color17 #d75e52