background #1e282c
foreground #b2c7c7
selection_background #2a373d
selection_foreground #b2c7c7
url_color #618adf
cursor #a6c974
cursor_text_color #1a2226

# Tabs
active_tab_background #618adf
active_tab_foreground #1a2226
inactive_tab_background #2a373d
inactive_tab_foreground #222d32
tab_bar_background #1b2428

# Windows
active_border_color #618adf
inactive_border_color #2a373d

# normal
color0 #1b2428
color1 #d1676c
color2 #a6c974
color3 #deb05c
color4 #1b2428
color5 #da596e
color6 #63bbdf
color7 #bbc8cd

# bright
color8  #314549
color9  #e76f75
color10 #aadb56
color11 #f7bb2d
color12 #4584fa
color13 #ef6279
color14 #3fccfb
color15 #b2c7c7

# extended colors
color16 #d77c61
color17 #d1676c