background #1a1b21
foreground #9898b5
selection_background #1e1f25
selection_foreground #9898b5
url_color #4e6a9c
cursor #6c7f54
cursor_text_color #18191f

# Tabs
active_tab_background #4e6a9c
active_tab_foreground #18191f
inactive_tab_background #1e1f25
inactive_tab_foreground #1c1d23
tab_bar_background #16171c

# Windows
active_border_color #4e6a9c
inactive_border_color #1e1f25

# normal
color0 #16171c
color1 #ba5454
color2 #6c7f54
color3 #d1b57c
color4 #496291
color5 #c4726c
color6 #587a74
color7 #5b5b76

# bright
color8  #272830
color9  #e14c4c
color10 #728f48
color11 #e8c165
color12 #406eb5
color13 #dd7a72
color14 #4f8a81
color15 #656581

# extended colors
color16 #bf8f62
color17 #ba5454