background #1b2023
foreground #5a6158
selection_background #242a2f
selection_foreground #5a6158
url_color #42728b
cursor #75783a
cursor_text_color #161b1d

# Tabs
active_tab_background #42728b
active_tab_foreground #161b1d
inactive_tab_background #242a2f
inactive_tab_foreground #1f2529
tab_bar_background #191e21

# Windows
active_border_color #42728b
inactive_border_color #242a2f

# normal
color0 #191e21
color1 #cb4f4f
color2 #75783a
color3 #af9e6b
color4 #191e21
color5 #bb755e
color6 #527a57
color7 #555c53

# bright
color8  #7a8478
color9  #eb4d4d
color10 #82861f
color11 #c3ab58
color12 #727619
color13 #dd7950
color14 #488b52
color15 #5a6158

# extended colors
color16 #cc7942
color17 #cb4f4f