background #10161e
foreground #bcbdbd
selection_background #1c2736
selection_foreground #bcbdbd
url_color #7292bd
cursor #89aa9a
cursor_text_color #0e131a

# Tabs
active_tab_background #7292bd
active_tab_foreground #0e131a
inactive_tab_background #1c2736
inactive_tab_foreground #141c26
tab_bar_background #10161e

# Windows
active_border_color #7292bd
inactive_border_color #1c2736

# normal
color0 #10161e
color1 #b46478
color2 #89aa9a
color3 #c1ac71
color4 #10161e
color5 #9b82af
color6 #75bbbd
color7 #b1b5bc

# bright
color8  #2b3b51
color9  #d76383
color10 #7ebda0
color11 #d6b95a
color12 #5192d8
color13 #b08acd
color14 #5cced0
color15 #bcbdbd

# extended colors
color16 #d49360
color17 #b46478