background #dfdfdf
foreground #425353
selection_background #e9e9e9
selection_foreground #425353
url_color #73878f
cursor #5d6c60
cursor_text_color #dadada

# Tabs
active_tab_background #73878f
active_tab_foreground #dadada
inactive_tab_background #e9e9e9
inactive_tab_foreground #E4E4E4
tab_bar_background #b6b6b6

# Windows
active_border_color #73878f
inactive_border_color #e9e9e9

# normal
color0 #b6b6b6
color1 #8e656e
color2 #5d6c60
color3 #8c7b6a
color4 #7e949d
color5 #6d5f81
color6 #606d6d
color7 #619494

# bright
color8  #cfd1d1
color9  #b86278
color10 #5a7d62
color11 #a48563
color12 #78a4b5
color13 #8263a9
color14 #5e7d7d
color15 #5d8989

# extended colors
color16 #a58382
color17 #8e656e