background #00323f
foreground #a7afaf
selection_background #023643
selection_foreground #a7afaf
url_color #4f7ea3
cursor #727c3e
cursor_text_color #00303d

# Tabs
active_tab_background #4f7ea3
active_tab_foreground #00303d
inactive_tab_background #023643
inactive_tab_foreground #003441
tab_bar_background #002a34

# Windows
active_border_color #4f7ea3
inactive_border_color #023643

# normal
color0 #002a34
color1 #c24f4d
color2 #727c3e
color3 #9f8549
color4 #477193
color5 #c0578a
color6 #4b8580
color7 #747878

# bright
color8  #113f4a
color9  #ea4440
color10 #7d8b25
color11 #b4912e
color12 #3680b0
color13 #e64d9d
color14 #37968f
color15 #767a7a

# extended colors
color16 #b46548
color17 #c24f4d