background #24252b
foreground #a0a0bc
selection_background #28292f
selection_foreground #a0a0bc
url_color #4e6a9c
cursor #6c7f54
cursor_text_color #222329

# Tabs
active_tab_background #4e6a9c
active_tab_foreground #222329
inactive_tab_background #28292f
inactive_tab_foreground #26272d
tab_bar_background #1e1f24

# Windows
active_border_color #4e6a9c
inactive_border_color #28292f

# normal
color0 #1e1f24
color1 #ba5454
color2 #6c7f54
color3 #d1b57c
color4 #496291
color5 #c4726c
color6 #587a74
color7 #62627e

# bright
color8  #30313a
color9  #e14c4c
color10 #728f48
color11 #e8c165
color12 #406eb5
color13 #dd7a72
color14 #4f8a81
color15 #6c6c89

# extended colors
color16 #bf8f62
color17 #ba5454