background #1b2635
foreground #bcbdbd
selection_background #1f2a39
selection_foreground #bcbdbd
url_color #6885ad
cursor #7b998a
cursor_text_color #192433

# Tabs
active_tab_background #6885ad
active_tab_foreground #192433
inactive_tab_background #1f2a39
inactive_tab_foreground #1d2837
tab_bar_background #17202c

# Windows
active_border_color #6885ad
inactive_border_color #1f2a39

# normal
color0 #17202c
color1 #b26377
color2 #7b998a
color3 #bba76f
color4 #5677a3
color5 #9a80ae
color6 #69a3a4
color7 #737474

# bright
color8  #2b3543
color9  #d66182
color10 #72ab90
color11 #d0b459
color12 #4a85c6
color13 #af87cc
color14 #56b5b6
color15 #878888

# extended colors
color16 #c88e62
color17 #b26377