background #19222f
foreground #bcbdbd
selection_background #253347
selection_foreground #bcbdbd
url_color #7292bd
cursor #89aa9a
cursor_text_color #171f2b

# Tabs
active_tab_background #7292bd
active_tab_foreground #171f2b
inactive_tab_background #253347
inactive_tab_foreground #1d2837
tab_bar_background #17202c

# Windows
active_border_color #7292bd
inactive_border_color #253347

# normal
color0 #17202c
color1 #b46478
color2 #89aa9a
color3 #c1ac71
color4 #17202c
color5 #9b82af
color6 #75bbbd
color7 #b1b5bc

# bright
color8  #2b3b51
color9  #d76383
color10 #7ebda0
color11 #d6b95a
color12 #5192d8
color13 #b08acd
color14 #5cced0
color15 #bcbdbd

# extended colors
color16 #d49360
color17 #b46478