background #262524
foreground #b49f88
selection_background #2a2928
selection_foreground #b49f88
url_color #497188
cursor #757845
cursor_text_color #242322

# Tabs
active_tab_background #497188
active_tab_foreground #242322
inactive_tab_background #2a2928
inactive_tab_foreground #282726
tab_bar_background #201f1e

# Windows
active_border_color #497188
inactive_border_color #2a2928

# normal
color0 #201f1e
color1 #ca4f4f
color2 #757845
color3 #af9e6b
color4 #3f6376
color5 #bb755e
color6 #527a57
color7 #786d61

# bright
color8  #34312e
color9  #ea4c4c
color10 #828633
color11 #c3ab58
color12 #33728d
color13 #dd7950
color14 #488b52
color15 #786d62

# extended colors
color16 #c47d54
color17 #ca4f4f