background #201f1e
foreground #ad9984
selection_background #242322
selection_foreground #ad9984
url_color #497188
cursor #757845
cursor_text_color #1e1d1c

# Tabs
active_tab_background #497188
active_tab_foreground #1e1d1c
inactive_tab_background #242322
inactive_tab_foreground #222120
tab_bar_background #1b1a1a

# Windows
active_border_color #497188
inactive_border_color #242322

# normal
color0 #1b1a1a
color1 #ca4f4f
color2 #757845
color3 #af9e6b
color4 #3f6376
color5 #bb755e
color6 #527a57
color7 #665e56

# bright
color8  #2e2b28
color9  #ea4c4c
color10 #828633
color11 #c3ab58
color12 #33728d
color13 #dd7950
color14 #488b52
color15 #71675e

# extended colors
color16 #c47d54
color17 #ca4f4f