background #242b2f
foreground #6bb4b4
selection_background #282f33
selection_foreground #6bb4b4
url_color #447ca2
cursor #7e965a
cursor_text_color #22292d

# Tabs
active_tab_background #447ca2
active_tab_foreground #22292d
inactive_tab_background #282f33
inactive_tab_foreground #262d31
tab_bar_background #1e2427

# Windows
active_border_color #447ca2
inactive_border_color #282f33

# normal
color0 #1e2427
color1 #d75e52
color2 #7e965a
color3 #d8b36f
color4 #3b6d8d
color5 #c6614d
color6 #448595
color7 #587979

# bright
color8  #2b393c
color9  #f06455
color10 #84a647
color11 #f0bf51
color12 #237ca8
color13 #ea5f3a
color14 #2595ab
color15 #587a7a

# extended colors
color16 #e19556
color17 #d75e52